### ISSUE TITLE
Missing dependency on `eslint-visitor-keys`

### ISSUE THREAD

**Issue by SirWindfield** [sindresorhus/eslint-plugin-unicorn#1099]
I migrated to yarn v2 plug'n'play and I get errors about this package missing a dependency declaration.

The package misses a dependency declaration on `eslint-visitor-keys`, which is used inside of the rules.

I can open up a PR if you want. Since the dependency is used directly, it has to be inside of `dependencies`, right?

**Comment by fisker** [comment]
> Since the dependency is used directly, it has to be inside of dependencies, right?

Yes.

> I can open up a PR if you want.

PR welcome.
