### ISSUE TITLE
Prefer `Array.isArray()` over `arr instanceof Array`

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/eslint-plugin-unicorn#11]
The latter doesn't work across realms (frames/tabs in the browser, `vm` in Node.js). I still see people using the latter, so would be nice to prevent them.

-

Should be possible to make this autofixable.

-

New to making ESLint rules? Check out this quick guide on [how to get started](https://gist.github.com/sindresorhus/1656c46f23545deff8cc713649dcff26).

**Comment by pvskarthikeya** [comment]
Hey! I am new to this project. Can I work on this?

**Comment by sindresorhus** [comment]
@pvskarthikeya Go ahead :)

See https://github.com/sindresorhus/eslint-plugin-unicorn/issues/55#issuecomment-252567394 on how to get started.

**Comment by pvskarthikeya** [comment]
@sindresorhus Thanks for the info.

**Comment by pvskarthikeya** [comment]
#58 Hey @sindresorhus. Added a pull request.
