### ISSUE TITLE
[no-array-for-each] incorrect autofix for ts files

### ISSUE THREAD

**Issue by JounQin** [sindresorhus/eslint-plugin-unicorn#1107]
```js
// const elements: NodeListOf<Element> = ...

elements.forEach((el: HTMLDivElement) => {})

// autofixed
for (const el: HTMLDivElement of elements) {
}
```

Errors:

```log
error TS2483: The left-hand side of a 'for...of' statement cannot use a type annotation.

error TS2488: Type 'NodeListOf<Element>' must have a '[Symbol.iterator]()' method that returns an iterator.
```

**Comment by fisker** [comment]
I don't use TS, what's correct fix? Or does it fixable?

**Comment by fisker** [comment]
When I implement this rule, I added a comment here https://github.com/sindresorhus/eslint-plugin-unicorn/blob/fbb0fc438ea242f048b5661d6f10aa53a771b6ba/rules/no-array-for-each.js#L301, is it correct for two parameters?

**Comment by JounQin** [comment]
@fisker 

The first error could be fixed with `for (const el of elements as HTMLDivElement[])` but the type here is actually wrong.

And the second error I don't think it's fixable.

**Comment by fisker** [comment]
This `NodeListOf` not builtin `NodeList` in browser, right?

**Comment by JounQin** [comment]
> When I implement this rule, I added a comment here
> 
> https://github.com/sindresorhus/eslint-plugin-unicorn/blob/fbb0fc438ea242f048b5661d6f10aa53a771b6ba/rules/no-array-for-each.js#L301
> 
> , is it correct for two parameters?

Nope, see [playground](https://www.typescriptlang.org/play?#code/GYewTgBAFAxiB2BnALhA2gS3gEwKYA8AaCXAG1wFtd5kBdALnXgFcKAjXMYl9z2iEMAgB5NgCtcMZADpqyMBlyIoAbwC+ASghaVAWABQECHCQhy00iADmULHiIlyVGhoNqDQA)

**Comment by fisker** [comment]
I see, thanks.

`no-for-loop` have this auto-fix, https://github.com/sindresorhus/eslint-plugin-unicorn/blob/fbb0fc438ea242f048b5661d6f10aa53a771b6ba/rules/no-for-loop.js#L394-L397

**Comment by JounQin** [comment]
> This `NodeListOf` not builtin `NodeList` in browser, right?

No, it's not. It's a built-in ts DOM type.

**Comment by fisker** [comment]
```text
Symbol.iterator in NodeList.prototype
true
```

But NodeList has `Symbol.iterator`

**Comment by JounQin** [comment]
It can be fixed by `for (const el of Array.from(elements) as HTMLDivElement[]) {}`

further reference: https://mariusschulz.com/blog/downlevel-iteration-for-es3-es5-in-typescript

**Comment by sindresorhus** [comment]
> It can be fixed by for (const el of Array.from(elements) as HTMLDivElement[]) {}

`Array.from()` should not be needed. Can you explain why you're saying it is?

**Comment by JounQin** [comment]
> > It can be fixed by for (const el of Array.from(elements) as HTMLDivElement[]) {}
> 
> `Array.from()` should not be needed. Can you explain why you're saying it is?

When targeting `es3` or `es5` without `downlevelIteration` option in TypeScript, it'll just fail to compile, you can check https://www.typescriptlang.org/tsconfig/#downlevelIteration as reference.

**Comment by sindresorhus** [comment]
> When targeting es3 or es5 without downlevelIteration option in TypeScript, the built-in NodeList is not iterable

We can maybe note that in the rule docs, but that's not a concern for us. Our rules are for modern environments.
