### ISSUE TITLE
Can `prefer-ternary` be merged into eslint core rule `no-else-return`?

### ISSUE THREAD

**Issue by JounQin** [sindresorhus/eslint-plugin-unicorn#1116]
I think they achieve similar functionality.

**Comment by fisker** [comment]
I don't think they can.

```js
function a() {
  if (test) {
	return 1;
  } else {
    return 2;
 }
}
```

`no-else-return` enforce

```js
function a() {
  if (test) {
	return 1;
  }

  return 2;
}
```


`prefer-ternary` enforce

```js
function a() {
  return test ? 1 : 2;
}
```

And `prefer-ternary` do more then just checking `return`.

**Comment by JounQin** [comment]
Oh, I mean add an option into `no-else-return` like `preferTernary: true`. They are both enforcing return style IMO.

**Comment by fisker** [comment]
You can try to make a proposal there.

**Comment by JounQin** [comment]
post https://github.com/eslint/eslint/issues/14121

**Comment by fisker** [comment]
Let's close this one then.

**Comment by JounQin** [comment]
@fisker The eslint proposal is closed, is that possible to adopt `no-else-return` into `unicorn`?

```js
function a() {
  if (test) {
	return 1;
  } else {
    return 2;
 }
}

// autofixed by eslint's `no-else-return`
function a() {
  if (test) {
	return 1;
  }

  return 2;
}

But for now `prefer-ternary` won't fix the fixed codes again.
```

**Comment by fisker** [comment]
I think easier way is handle

```js
function a() {
  if (test) {
	return 1;
  }

  return 2;
}
```

in `prefer-ternary`.

**Comment by JounQin** [comment]
Yes, I understand your point, but I still think the two rules are similar, if we can merge then the built-in one could be disabled.

Of course, it's just my poor personal idea.

**Comment by fisker** [comment]
`no-else-return` don't require `else` block to be `return`

```js
function a() {
  if (test) {
	return 1;
  } else {
    doSomethingElse()
 }
}
```

This is also the invalid case for `no-else-return`.

It also has [an option `allowElseIf`](https://eslint.org/docs/rules/no-else-return#allowelseif-true).

I think this rule should work together with `prefer-ternary`.

**Comment by fisker** [comment]
It's not hard to detect the fixed case. Some logic from `no-array-push-push` may help.

**Comment by fisker** [comment]
Close in favor of #1219

**Comment by fregante** [comment]
I think rather than merging them, `prefer-ternary` could detect the result of `no-else-return` as I mentioned in https://github.com/sindresorhus/eslint-plugin-unicorn/issues/1219

This way it also works on existing code where `no-else-return` already ran.

**Comment by fregante** [comment]
Closing following the discussion in the last PR
