### ISSUE TITLE
Rule proposal: Regex shorthands

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/eslint-plugin-unicorn#112]
Prefer:

- `\d` instead of `[0-9]`
- `\D` instead of `[^0-9]`
- `\w` instead of `[A-Za-z0-9_]` or `[A-Za-z\d_]`
- `\w` instead of `[a-z0-9_]` or `[a-z\d_]` with the `i` flag
- `\W` instead of `[^A-Za-z0-9_]` or `[^A-Za-z\d_]`
- `\W` instead of `[^a-z0-9_]` or `[^a-z\d_]` with the `i` flag

For regex literals and the `RegExp` constructor (As long as it's a simple string).

Any order inside the brackets should work.

Might be more shorthands we can infer, but this would be a good start. I have to comment about the first case in PRs all the time.

---

@SamVerschueren @jfmengels Thoughts?

**Comment by SamVerschueren** [comment]
Yes, we can always add more in the future. Having it auto-fixable would be super sweet!

**Comment by SamVerschueren** [comment]
@sindresorhus You probably mean `\W` instead of `\w` for the last example

> `\W` instead of `[^a-z0-9_]` or `[^a-z\d_]` with the `i` flag

**Comment by sindresorhus** [comment]
Yes

**Comment by SamVerschueren** [comment]
As I was implementing this, I just realised that for this regex `[A-Za-z0-9_]`, we actually have a permutation of 4, thus having 24 combinations (4! = 1 * 2 * 3 * 4 = 24).

- `[a-zA-Z0-9_]`
- `[a-zA-Z_0-9]`
- `[a-z0-9A-Z_]`
- `[a-z0-9_A-Z]`
- `[a-z_A-Z0-9]`
- `[a-z_0-9A-Z]`
- `[A-Za-z0-9_]`
- `[A-Za-z_0-9]`
- `[A-Z0-9a-z_]`
- `[A-Z0-9_a-z]`
- `[A-Z_a-z0-9]`
- `[A-Z_0-9a-z]`
- `[0-9a-zA-Z_]`
- `[0-9a-z_A-Z]`
- `[0-9A-Za-z_]`
- `[0-9A-Z_a-z]`
- `[0-9_a-zA-Z]`
- `[0-9_A-Za-z]`
- `[_a-zA-Z0-9]`
- `[_a-z0-9A-Z]`
- `[_A-Za-z0-9]`
- `[_A-Z0-9a-z]`
- `[_0-9a-zA-Z]`
- `[_0-9A-Za-z]`

Just want to dump it in here as a reference :).

**Comment by devinrhode2** [comment]
really awesome idea+work guys 👍
