### ISSUE TITLE
custom-error-definition inserts constructor before the class when there’s no body

### ISSUE THREAD

**Issue by j-f1** [sindresorhus/eslint-plugin-unicorn#114]
Original:

```js
export class ShellError extends Error {}
//     ^ Add a constructor to your error
```

“Fixed”:

```js
  constructor() {
    super();
    this.name = 'ShellError';
  }
export class ShellError extends Error {}
```

**Comment by SamVerschueren** [comment]
This is odd, I cannot reproduce this in the test cases. We already had a test https://github.com/sindresorhus/eslint-plugin-unicorn/blob/master/test/custom-error-definition.js#L69-L84.

Is it possible that somewhere before your expression, something else was fixed as well? Pushing the definition down which causes an offset. Have you tried fixing the error definition in a file with only the error definition, nothing else?

**Comment by j-f1** [comment]
I haven’t seen this happen again, so I’m closing it out as “probably a hiccup.”
