### ISSUE TITLE
[Regression] no-null: error for Object.create(null) with parserOptions.ecmaVersion 2019

### ISSUE THREAD

**Issue by kevinoid** [sindresorhus/eslint-plugin-unicorn#1146]
With `.eslintrc.json`

```json
{
  "extends": "plugin:unicorn/recommended",
  "parserOptions": {
    "ecmaVersion": 2019
  }
}
```
the code
```js
module.exports = Object.create(null);
```
is accepted without error when using `eslint-plugin-unicorn@28.0.2`.  When using `eslint-plugin-unicorn@29.0.0` it produces the following error:

    /path/to/file.js:1:32: Use `undefined` instead of `null`. [Error/unicorn/no-null]

I bisected the regression to 2397d94 (presumably the changes in `rules/utils/method-selector.js` although I didn't investigate further).

Thanks,
Kevin

**Comment by fisker** [comment]
@kevinoid What parser are you using?

**Comment by fisker** [comment]
My guess is , you parser don't have `optional` property for `MemberExpression`, maybe we can change `[...=false]` to `[...!=true]`.

The methodSelector function has bug before 2397d94, you can see, [here](https://github.com/sindresorhus/eslint-plugin-unicorn/commit/2397d940572c74a48e00be11c307e821f9f1664b#diff-4dc7a79c5b1abc94f8b81e79d2203d1fca6d935584941ea8fd4bee8566ad601fL27) it mean to check optional, but it checked `computed` instead.

**Comment by kevinoid** [comment]
> @kevinoid What parser are you using?

I'm not sure what you mean.  How would I check this?  For reference, a script to reproduce the issue from scratch:

```sh
cd "$(mktemp -dt)"
npm init -y
npm install --save-dev eslint eslint-plugin-unicorn
cat >.eslintrc.json <<'ESLINTRC'
{
  "extends": "plugin:unicorn/recommended",
  "parserOptions": {
    "ecmaVersion": 2019
  }
}
ESLINTRC
echo 'module.exports = Object.create(null);' >index.js
./node_modules/.bin/eslint index.js
```

`npm ls`:

    tmp.odU4hveyCQ@1.0.0 /tmp/tmp.odU4hveyCQ
    ├── eslint-plugin-unicorn@29.0.0
    └── eslint@7.22.0

**Comment by fisker** [comment]
Thanks, I'll take a look later.
