### ISSUE TITLE
insertBefore 2nd param should be allowed to be null

### ISSUE THREAD

**Issue by kkmuffme** [sindresorhus/eslint-plugin-unicorn#1156]
https://developer.mozilla.org/en-US/docs/Web/API/Node/insertBefore allows the 2nd arg to be null
That will however give an error to use undefined instead.

However when we use undefined, then it auto-fixes it and removes the "undefined" arg (unless checkArguments of https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/no-useless-undefined.md#checkarguments is set) 

no-null
no-useless-undefined

```js
hello.insertBefore( button, null );

// this workaround does not work either, as Chrome will report an error:
// parameter 2 is not of type" 'node'
const myNull = Object.create( null );
hello.insertBefore( button, myNull );
```

**Comment by sindresorhus** [comment]
I guess we could not report it if the method name is `insertBefore` and the second argument is `null`.

**Comment by kachkaev** [comment]
I think I found an edge case which is not fixed yet. I might submit an issue later when there is time, but here is a quick example:

```ts
a.insertBefore(ghostNode, a.childNodes[0] ?? null);
```

Null is in a sub-AST-node of the second arg, which makes the rule triggered:

```txt
Use `undefined` instead of `null`. unicorn/no-null
```
