### ISSUE TITLE
Prefer `addEventListener` over `onclick`

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/eslint-plugin-unicorn#117]
`addEventListener` is better for many reasons: https://stackoverflow.com/a/35093997/64949

Same with all the other `onfoo` events.

I got the idea in https://github.com/wulkano/kap/pull/255#discussion_r147623982.

---

## Fail

```js
foo.onclick = () => {

};
```

## Pass

```js
foo.addEventListener('click', () => {

});
```

---

This should be auto-fixable.

**Comment by sindresorhus** [comment]
@kevva @SamVerschueren Thoughts?

**Comment by SamVerschueren** [comment]
Yes totally agree. Let's do this one!

**Comment by kevva** [comment]
💯!

**Comment by johnwu93** [comment]
Can I work on this?

**Comment by sindresorhus** [comment]
@johnwu93 Yes :)

**Comment by johnwu93** [comment]
Do you guys just want this to be applicable whenever an object calls `onclick`, regardless of its type? Or, do you guys want this to be applicable if the object is of type `DOM element`? The later would be nice, but much more difficult to implement.

**Comment by sindresorhus** [comment]
@johnwu93 ESLint doesn't have type inference, so that is impossible. We'll just assume `onclick` means it's a DOM element.
