### ISSUE TITLE
Merge `unicorn/prefer-regexp-test` to `eslint-plugin-regexp`

### ISSUE THREAD

**Issue by fisker** [sindresorhus/eslint-plugin-unicorn#1175]
I found [`eslint-plugin-regexp`](https://github.com/ota-meshi/eslint-plugin-regexp) has lots of useful rules about `regexp`.

And I checked [`regexp/prefer-regexp-test`](https://github.com/ota-meshi/eslint-plugin-regexp/blob/master/lib/rules/prefer-regexp-test.ts) rule, it's almost the same with ours. ~It even have the same bugs I fixed recently #1152 and #1173.~ Update: maybe not, not sure.

Maybe we can migrate our rule to this plugin?

This plugin seems young though.

**Comment by sindresorhus** [comment]
Hmm, not sure. I don't see much benefit in doing that. That plugin has a sole maintainer. What happens if that person burns out. I have experienced this in the past. I invested a lot in `eslint-plugin-import` and in the end it ended up close to being unmaintained.

**Comment by fisker** [comment]
Just a idea. Your call.

**Comment by sindresorhus** [comment]
Let's reconsider in half a year or something if the plugin is still maintained then.
