### ISSUE TITLE
Prefer-spread rule is displayed when using a string .concat().

### ISSUE THREAD

**Issue by damonpam** [sindresorhus/eslint-plugin-unicorn#1186]
the `prefer-spread` rule is displayed with strings when it seems to be define for Arrays.
https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/no-array-for-each.md

`prefer-spread`: prefer the spread operator over `Array#concat(…)`.

```js
const base = 'this is the string base';
const suffix = 'with a suffix';

const sentence = code.concat(suffix);
```

**Comment by fisker** [comment]
Duplicated of #1147
