### ISSUE TITLE
Publish a new version

### ISSUE THREAD

**Issue by noamokman** [sindresorhus/eslint-plugin-unicorn#119]
Hi,

Can you publish a new version to npm?

Thanks!

**Comment by sindresorhus** [comment]
Publishing a new release is blocked by https://github.com/sindresorhus/eslint-plugin-unicorn/issues/107. Help welcome.

**Comment by sindresorhus** [comment]
I did a new release: https://github.com/sindresorhus/eslint-plugin-unicorn/releases/tag/v3.0.0 We can fix #107 later.

**Comment by noamokman** [comment]
Thanks!
