### ISSUE TITLE
Conflict no-useless-undefined with consistent-return

### ISSUE THREAD

**Issue by crystalfp** [sindresorhus/eslint-plugin-unicorn#1199]
Thanks for all the eslint-plugin-unicorn checks! Very useful.

When I enable the `eslint-plugin-unicorn/no-useless-undefined` rule, and have `consistent-return` rule enabled too the following code gives one violation in the first rule. But if I change `return undefined` to `return` the later rule signals a violation.
Maybe the `no-useless-undefined` rule is missing an option to skip this kind of code.

eslint-plugin-unicorn/no-useless-undefined

This simplified example removed the needed await calls present in the real code.
Changing undefined to null trigger another violation.
Well, I could disable the rule for this line, but there are many similar ones.

```js
async compute(arg: number): Promise<number|undefined> {

    if(arg === 42) return undefined;
    return arg;
}
```

Thanks for looking
mario

**Comment by fisker** [comment]
Your code seems not parse able, is it TypeScript? I think https://github.com/sindresorhus/eslint-plugin-unicorn/pull/1165 already fixed it, are you sure your version is v30?

**Comment by crystalfp** [comment]
Yes, it is Typescript.
Yes, I have v30 installed.
Thanks!
mario

**Comment by fisker** [comment]
> Yes, it is Typescript.

But it can't be parsed, is it a class/object method? Maybe you can post full code.

**Comment by fisker** [comment]
Have you considered try this option https://eslint.org/docs/rules/consistent-return#options?

**Comment by crystalfp** [comment]
Thanks @fisker ! Yes, the code is a class method. Thanks also for the suggestion about consistent return. I'll try it as soon as I arrive at the office.

**Comment by crystalfp** [comment]
Unfortunately it does not work.
With `consistent-return: [error, {treatUndefinedAsUnspecified: true}]` the following code gives the error "Async method 'viewByKeywords' expected a return value" at line 1:
```
class Database {
	private async viewByKeywords(): Promise<QueryResultsBlock[]|undefined> {

		if(!this.databaseHandler) {
			return; // <- line 1
		}
                return [];
        }
}
```
Same error with treatUndefinedAsUnspecified set to true.
Changing line 1 to `return undefined` gives no error for treatUndefinedAsUnspecified set to false.
If I set it to true it generates the error: "Async method 'viewByKeywords' expected a return value."

Summarizing: I cannot use the no-useless-undefined rule and have to set treatUndefinedAsUnspecified to false. This way at least eslint does not offer useless suggestions.

Anyway, thanks for your time @fisker !

**Comment by fungiboletus** [comment]
I have the same issue. How did you fix it @crystalfp ?

**Comment by crystalfp** [comment]
As I wrote, disabling the rule. Eslint should help developing clean code, but too many false positive, or unfixable issues do not help in this.

**Comment by KramerLewis** [comment]
I am seeing this issue in arrow functions.

style A
```
function foo(): (string | undefined)[] {
  return ['bar', 'baz'].map((str) => {
    if(str === 'baz') return undefined;
    return str;
  });
}
```
results in
```
  3:31  error  Do not use useless `undefined`                                                                   unicorn/no-useless-undefined
```

style B
```
function foo(): (string | undefined)[] {
  return ['bar', 'baz'].map((str) => {
    if(str === 'baz') return;
    return str;
  });
}
```
results in 
```
  4:5   error  Arrow function expected no return value                                                          consistent-return
```


Setting `treatUndefinedAsUnspecified` to true or false does not solve it for me.
