### ISSUE TITLE
Deprecate rules which is exists in default eslint

### ISSUE THREAD

**Issue by danny007in** [sindresorhus/eslint-plugin-unicorn#1213]
Example 
`no-lonely-if`

**Comment by yakov116** [comment]
From the first line there. https://github.com/sindresorhus/eslint-plugin-unicorn/blob/c88882e9e4c22dc96b9ccfe61a7e93c9923cdd46/docs/rules/no-lonely-if.md

> This rule adds onto the built-in [`no-lonely-if`](https://eslint.org/docs/rules/no-lonely-if) rule, which only forbids `if` statements in `else`, not in `if`.

**Comment by danny007in** [comment]
rename to `no-lonely-if-inside-else`

**Comment by danny007in** [comment]
rename it 👍🏼

**Comment by sindresorhus** [comment]
I don't see why we should rename it, and no one has provided any argument for why we should.
