### ISSUE TITLE
`prefer-switch` rule causes unreachable break statement when return statement present

### ISSUE THREAD

**Issue by bmish** [sindresorhus/eslint-plugin-unicorn#1232]
The autofixer of the [unicorn/prefer-switch](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prefer-switch.md) rule adds a `break` statement to the end of each case. This `break` statement could be considered redundant or an error/violation when coming after a `return` statement. Likely the `break` should be omitted after a `return`?

Before autofix:

```js
function getSomething() {
  if (p.type === 'PathExpression') {
    return 1;
  } else if (p.type === 'StringLiteral') {
    return 2;
  } else if (p.type === 'SubExpression') {
    return 3;
  } else {
    return 4;
  }
}
```

After autofix:

```js
function getSomething() {
  switch (p.type) {
    case 'PathExpression': {
      return 1;

      break;
    }
    case 'StringLiteral': {
      return 2;

      break;
    }
    case 'SubExpression': {
      return 3;

      break;
    }
    default: {
      return 4;
    }
  }
}
```

Causes two errors on the `break` lines:

```
Unreachable code detected. ts(7027)
```

```
Unreachable code. eslint no-unreachable
```

https://eslint.org/docs/rules/no-unreachable (recommended rule)

**Comment by fisker** [comment]
I'll fix this.
