### ISSUE TITLE
`prefer-string-starts-ends-with`: incorrect autofix when string does not exist

### ISSUE THREAD

**Issue by bmish** [sindresorhus/eslint-plugin-unicorn#1267]
### Problem

If the string variable is null or undefined, the autofix will cause an exception.

Before autofix:

```js
/^en/.test(lang)
// Returns `false` if `lang` is `undefined` / `null`
```

After autofix:

```js
lang.startsWith('en')
// Uncaught TypeError: Cannot read property 'startsWith' of undefined
```

### Fix

A year from now when we drop support for Node 12, we can use optional chaining to autofix this safely:

```js
lang?.startsWith('en')
```

Until then, we have a few options:
1. Do nothing since the autofixer has been around or a year (#711) and no one else has complained
2. Temporarily turn the autofixer into an automated suggestion until we can use the optional chaining autofix
3. Warn about this situation in the [rule doc](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prefer-string-starts-ends-with.md)

**Comment by fisker** [comment]
I  assume you mean `lang.startsWith?.('en')`

**Comment by bmish** [comment]
@fisker no actually. The situation here is that `lang` does not exist, not that the function does not exist.

**Comment by fisker** [comment]
Oh right. but if function didn't exists `lang?.startsWith()` still error (undefined is not a function).

**Comment by fisker** [comment]
Correct fix for this should be 

```js
String(lang).startsWith('en')
```

**Comment by bmish** [comment]
@fisker that fix should work, although it's not the most elegant fix, since most of the time the string casting will be unnecessary and potentially cause the reader confusion (it's not clear that it's there to solve the problem of undefined/null). So we could use that but we should definitely follow-up to use optional chaining in a year.

**Comment by bmish** [comment]
Using `(lang || '').startsWith('en')` would actually make the fixes intent more clear. I think I may prefer this one.

**Comment by fisker** [comment]
No, you are wrong 

```text
/^un/.test(undefined)
true

String(undefined).startsWith('un')
true

(undefined || '').startsWith('un')
false

undefined?.startsWith('en')
undefined
```

**Comment by bmish** [comment]
Oh wow. I am surprised by the behavior with `/^un/.test(undefined)`. Not intuitive, and probably not the intention of the original code, but technically your fix is correct.

**Comment by fisker** [comment]
Yap, if it's not string, it convert to string first, we can remove auto fix for it or use suggestions.

**Comment by bmish** [comment]
I am happy with your suggested autofix, given that it's correct, and an autofix is much more useful than a suggestion.

**Comment by fisker** [comment]
What if it's unknown value?  `/^x/.test(foo)`, people may don't want wrap it with `String()`, I think we can still assume it's string?

**Comment by bmish** [comment]
I'm kind of torn on this. Ideally, an autofix should be both correct and match the intent of the original code.

1. `lang.startsWith('en')` (today's autofix) -- matches intent, crashes on undefined, not fully correct
2. `lang?.startsWith('en')` -- matches intent, doesn't crash on undefined, not fully correct
3. `(lang || '').startsWith('en')` -- matches intent, doesn't crash on undefined, not fully correct
4. `String(lang).startsWith('en')` -- doesn't match intent, redundant most of the time, but fully correct

There's no perfect choice. I could see arguments for each.

One argument for keeping today's autofix is that it's the nicest fix and it will also fail-fast if someone uses undefined with it, so any issue should be detected quickly.

**Comment by fisker** [comment]
I prefer keep the current fix, but suggest  `String(foo).startsWith()` for known non-string cases.

**Comment by fisker** [comment]
Like 

- fix to `String(...).startsWith(...)`
- fix to `...?.startsWith(...)`
- fix to `(... || '').startsWith(...)`

**Comment by bmish** [comment]
Yeah I think we're agreed on keeping the current autofix and then providing all of these as suggestions.

**Comment by fisker** [comment]
Want work on it?

**Comment by bmish** [comment]
Sure I'll work on it.
