### ISSUE TITLE
Add `suggestion` property to rule meta

### ISSUE THREAD

**Issue by fisker** [sindresorhus/eslint-plugin-unicorn#1292]
1. Add `suggestion: true` to meta, this may change in ESLint V8 https://github.com/eslint/eslint/issues/14312
2. Add suggestion info to rule table https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/scripts/generate-rules-table.mjs
3. Enable eslint rule https://github.com/not-an-aardvark/eslint-plugin-eslint-plugin/pull/105

**Comment by bmish** [comment]
Yeah, enabling us to easily mention which rules provide suggestions in the readme is exactly the problem I want to solve with the upcoming ESLint changes to the property.
