### ISSUE TITLE
`prefer-starts-ends-with` rule

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/eslint-plugin-unicorn#13]
[`.startsWith`](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/String/startsWith) instead of:
- `foo.indexOf('bar') === 0`
- `foo[0] === 'b'`
- `foo.charAt(0) === 'b'` (and `foo.charAt()`)
- `foo.slice(0, 2) === 'bar'` (and .substring & .substr)
- `/^bar/.test(foo)` (and `.match()`)

[`.endsWith`](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/String/endsWith) instead of:
- `.lastIndexOf`
- `foo[foo.length - 1] === 'r'`
- `foo.charAt(foo.length - 1) === 'b'`
- `foo.slice(0, -3) === 'bar'` (and .substring & .substr)
- `/bar$/.test(foo)` (and `.match()`)

The regex case is especially useful as I've seen a lot of regexes used in this scenario.
## 

New to making ESLint rules? Check out this quick guide on [how to get started](https://gist.github.com/sindresorhus/1656c46f23545deff8cc713649dcff26).

**Comment by jfmengels** [comment]
You'd have to infer that `foo` is a string, which is hard :/

**Comment by sindresorhus** [comment]
Indeed. Wish ESLint had some kind of type inference analysis...

At least with the regex case you can safely assume a string. So maybe just that for now?

**Comment by jfmengels** [comment]
Yeah, but much less interesting ^^'
(and it only applies when Regex is case sensitive too...)

**Comment by anglee** [comment]
Hi! I am new here. Can I try to take care of this one?

**Comment by sindresorhus** [comment]
@anglee Yes. Go ahead!

Check out this quick guide on [how to get started](https://gist.github.com/sindresorhus/1656c46f23545deff8cc713649dcff26). Let us know if you have any questions. Have fun :)
