### ISSUE TITLE
Consider publishing some utility functions

### ISSUE THREAD

**Issue by bmish** [sindresorhus/eslint-plugin-unicorn#1300]
The utils in this plugin are excellent (node selectors, rename-variable, avoid-capture, parentheses, etc). I'm curious if you have ever considered publishing some of them in [eslint-utils](https://eslint-utils.mysticatea.dev/#%F0%9F%8F%81-goal) or maybe even a new package, so that other eslint plugins could make use of them (I definitely would have benefited from them in my other plugins). It's also possible to export utils directly from eslint-plugin-unicorn, but that's clunky for others to use and would make it harder for us to refactor the utils internally as needed.

**Comment by fisker** [comment]
Personally, I don't have interest to maintain public api/package. But feel free to use/copy/publish functions wrote by me (not sure about others).  Many functions not really work for edge cases, I refactor them all  the time.

**Comment by sindresorhus** [comment]
It's not something I want to publicly maintain either, and having them in a different package would also make it harder to refactor and slow down development.

**Comment by bmish** [comment]
Makes sense. Maybe I'll try contributing some of the highest-impact ones to eslint-utils myself sometime. CC: @mysticatea

**Comment by fisker** [comment]
FYI: I'm adding fix utils to fix common cases, and will refactor `shouldAddParentheses...` function. but I'll only cover needs for this repo.
