### ISSUE TITLE
Proposal changes to `no-null` and `no-useless-undefined`

### ISSUE THREAD

**Issue by fisker** [sindresorhus/eslint-plugin-unicorn#1309]
Exclude:

- ~`map.set(foo, null)`~
- `map.set(foo, undefined)`, if we use `map.set(foo)`, "set... to what"?
- ~`set.add(null)`~
- `set.add(undefined)`
- `Object.is(foo, null)` (`no-useless-undefined` already did, should share a list)
- ~`Array.push(null, undefined)` and `Array.unshift(null, undefined)`, remove `undefined` effect array length, and should allow push `null` to array~
- `Array.push(undefined)` and `Array.unshift(undefined)`, remove `undefined` effect array length

**Comment by sindresorhus** [comment]
> map.set(foo, null)

Why would we exclude it? The point of `no-null` is to prevent `null` usage. We obviously shouldn't auto-fix it, but I also don't see why we shouldn't report on it.

> and should allow push null to array

Why should it be allowed?

**Comment by fisker** [comment]
> The point of no-null is to prevent null usage. 

Make sense, I guess it supposed to use with `eslint-disable`.

>should allow push null to array
>Why should it be allowed?

Same above.

**Comment by fisker** [comment]
Updated.

**Comment by sindresorhus** [comment]
> Object.is(foo, null)

I don't see why we should allow this when `foo === null` is not allowed. I also don't think any real-world code would do this.

**Comment by fisker** [comment]
[`foo === null` is allowed](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/no-null.md#checkstrictequality), actually I mean `anything.is(foo, null)` (maybe test lib use)

**Comment by sindresorhus** [comment]
Ok. Then I agree that `Object.is(foo, null)` should be treated the same as `foo === null` and only be checked when that option is true.
