### ISSUE TITLE
Revisit no-array-instanceof

### ISSUE THREAD

**Issue by novemberborn** [sindresorhus/eslint-plugin-unicorn#136]
This Twitter thread is interesting: https://twitter.com/awbjs/status/939603968698626048

```js
const obj = Object.setPrototypeOf([], null)
Array.isArray(obj) // true
```

There are no comparable methods for other built-in types. I'm not sure this rule needs to exist.

**Comment by sindresorhus** [comment]
Seems very much theoretical. I can't imagine anyone would do that. JS has thousands of edge-cases. `Array.isArray()` works fine in 99.999% cases. That's all I care about. I can live with this super edge-case. And I don't see how `instanceof` would be any better. You can override methods in an Array subclass too to make it fail.

**Comment by jamestalmage** [comment]
There's a very real reason for this rule, and it's clearly stated in the docs. `instanceof` presents real problems when transferring arrays across contexts.

**Comment by novemberborn** [comment]
Cool, just thought I'd bring it up.
