### ISSUE TITLE
[unicorn/filename-case] Ignore base on file path

### ISSUE THREAD

**Issue by anton-johansson** [sindresorhus/eslint-plugin-unicorn#1406]
It seems like the `ignore` field for the `filename-case` plugin is only based on the file name excluding the path. I would like to exclude all files under a certain directory.

The use case for me is that I use Next.JS and the `pages` directory contains files where path parameters are included in the file name. I want kebab-case on all my files, except these ones. An example would be `pages/posts/[postId].tsx`. The plugin currently wants me to rename it `[post-id].tsx`, but I need the path parameter name to be as it is.

An easy fix would be to allow ignoring files based on their path. Thoughts?

**Comment by sindresorhus** [comment]
This sounds like a good use for overrides: https://eslint.org/docs/user-guide/configuring/configuration-files#how-do-overrides-work

I don't think we'll support file paths for the ignore option.

**Comment by anton-johansson** [comment]
You're completely right! Totally forgot about that. Thanks!
