### ISSUE TITLE
getPhysicalFilename() error when linting

### ISSUE THREAD

**Issue by AmandaCacholi** [sindresorhus/eslint-plugin-unicorn#1443]
When updating eslint-plugin-unicorn from 33.0.1 to 34.0.1 it happens de following error:
![image](https://user-images.githubusercontent.com/71740023/126822320-6992b4ce-efab-44a6-ba8b-46517876b36a.png)

The problem appears to be in: getPhysicalFilename()
https://github.com/sindresorhus/eslint-plugin-unicorn/pull/1344

When I test lint mannually it passes:
![image](https://user-images.githubusercontent.com/71740023/126818317-6c905f69-2987-430a-b7d3-e3d954bd177e.png)

**Comment by sindresorhus** [comment]
Sounds like you're not using the required ESLint version:

https://github.com/sindresorhus/eslint-plugin-unicorn/blob/179b7dfd07d24968b01f58d599bb4a685bb4136b/package.json#L77-L79

**Comment by AmandaCacholi** [comment]
This is the version I'm using:
![image](https://user-images.githubusercontent.com/71740023/126881005-2244e016-ba00-40c3-8879-679404a104e5.png)

**Comment by fisker** [comment]
Are you running a global installed eslint?

**Comment by AmandaCacholi** [comment]
I'm not running eslint explicitly, I'm just running the CRA server with 'yarn start'. and when it starts, the error happens:
![image](https://user-images.githubusercontent.com/71740023/127039591-fd8fc4e6-b784-499e-bffe-6f4120a58542.png)

but, when run eslint explicitly, with the global version and the project version, it works perfectly.

global eslint: ^7.30.0
![image](https://user-images.githubusercontent.com/71740023/127040262-aa4f9de0-08c4-4274-93ba-afa7d863ebf0.png)

project eslint: ^7.31.0
![image](https://user-images.githubusercontent.com/71740023/127040314-c86fa1ea-e961-4b37-be21-1268673ad9aa.png)

**Comment by sindresorhus** [comment]
Closing as this is not an issue with this project.

**Comment by Cayan** [comment]
I just bumped into the same issue, it happened on an empty project.

ESLint version is correct.
