### ISSUE TITLE
Rule proposal: `no-nested-await`

### ISSUE THREAD

**Issue by remcohaszing** [sindresorhus/eslint-plugin-unicorn#1458]
Nesting await inside a statement often gets messy. It’s better to split the line using an intermediate variable.

This is potentially autofixable. The only issue is that this would need to generate a name for an intermediate variable.

## Fail

```js
const filtered = (await Promise.all(promises)).filter(Boolean);
```

## Pass

```js
const unfiltered = await Promise.all(promises);
const filtered = unfiltered.filter(Boolean);
```

**Comment by sindresorhus** [comment]
> The only issue is that this would need to generate a name for an intermediate variable.

We can just generate a name like `promise`. It doesn't matter what the name is as the user will probably want to manually change it afterwards.

**Comment by papb** [comment]
> We can just generate a name like `promise`. It doesn't matter what the name is as the user will probably want to manually change it afterwards.

But it won't be a promise since it has been awaited already.

**Comment by papb** [comment]
Also, for what it's worth, I would vote for this to not be enabled by default. I think sometimes `(await foo()).bar` is more readable than splitting that in two lines. I wouldn't use this rule.

**Comment by fisker** [comment]
I was planning to propose a similar rule, this case

```js
const foo = (await import('./foo.js')).default;
```

I always use

```js
const {default: foo}= await import('./foo.js');
```

because I don't want access `.default` from await expression.

This rule will work for my case.

**Comment by remcohaszing** [comment]
I think we need to determine which cases should be reported. Typically I think the ones wrapped inside parentheses should be reported.

```ts
// Function
console.log(await promise);
(await import('foo')).default;
```

The following may be acceptable due to the lack of a better alternative:

```ts
const foo = (await promise) as string;
```

The following look ok to me:

```ts
const { default: foo } = await import('foo');

console.log({
  foo: await fs.readFile('foo'),
  bar: await fs.readFile('bar'),
});
```

**Comment by fisker** [comment]
We can start with property access and call expression, maybe add more cases in future.

**Comment by fisker** [comment]
How about `no-restricted-await-expression`, special version of [`no-restricted-syntax`](https://eslint.org/docs/rules/no-restricted-syntax) only checks `AwaitExpression`, also accept [options](https://eslint.org/docs/rules/no-restricted-syntax#options) like `no-restricted-syntax` but with preset selectors.

**Comment by fregante** [comment]
```js
const data = (await (await fetch()).json());
```

Me, circa 2017

**Comment by sindresorhus** [comment]
> How about no-restricted-await-expression, special version of no-restricted-syntax only checks AwaitExpression, also accept options like no-restricted-syntax but with preset selectors.

I feel like this rule is useful enough to be a focused rule instead of forcing each user to write AST queries. Someone could propose `no-restricted-await-expression` in addition if there are other use-cases.

**Comment by sindresorhus** [comment]
This is now accepted.

**Comment by fisker** [comment]
According to this table https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Operator_Precedence#table, seems only member access is should be considered. Other cases like `new` or `function` call only valid in theory, but rarely seen.

So let's name it `no-await-expression-member`?
