### ISSUE TITLE
`require-number-to-fixed-digits-argument` proposed breaking code changes when using libraries that replicate `toFixed()`

### ISSUE THREAD

**Issue by MitchellCash** [sindresorhus/eslint-plugin-unicorn#1463]
## Description

When using math/number libraries such as [big.js](https://www.npmjs.com/package/big.js), [bignumber.js](https://www.npmjs.com/package/bignumber.js) or [decimal.js](https://www.npmjs.com/package/decimal.js) that replicate the `Number.prototype.toFixed()` method with their own implementation, the `require-number-to-fixed-digits-argument` rule proposes certain breaking changes.

With these libraries passing `null` or `undefined` as the digits parameter for `toFixed()` is acceptable and means the return value will be unrounded and in normal notation. This is unlike `Number.prototype.toFixed()`, which returns the value to zero decimal places.

So when this rule proposes (or automatically fixes with `eslint --fix`) to change from `new BigNumber().toFixed()` to `new BigNumber().toFixed(0)` this breaks code that is expecting the number to come back unrounded and in normal notation.

I like to use this rule on `Number.prototype.toFixed()`, but of course not anywhere else. I have currently disabled `require-number-to-fixed-digits-argument` on lines I don't want it to run with `/* eslint-disable unicorn/require-number-to-fixed-digits-argument */ `, but was wondering if there was a solution that could be implemented in `eslint-plugin-unicorn` itself?

## Example code

```js
const BigNumber = require('bignumber.js');

const myVar = new BigNumber(1.123).toFixed();

console.log(myVar);    // '1.123'
```

**After implementing the proposed changes from `require-number-to-fixed-digits-argument`:**

```js
const BigNumber = require('bignumber.js');

const myVar = new BigNumber(1.123).toFixed(0);

console.log(myVar);    // '1'    <-- Breaking
```

**Comment by fisker** [comment]
We can't statically analyze the `BigNumber` type, so ignore `new BigNumer().toFixed()` is the best we can do.

Note:

```js
const bigNumber = new BigNumber(1.123)
const myVar = bigNumber.toFixed();
```

Still report as error.
