### ISSUE TITLE
String#charAt appears to be misspelled as charAt in documentation for the prefer-at rule

### ISSUE THREAD

**Issue by haykam821** [sindresorhus/eslint-plugin-unicorn#1466]
In [the documentation for the `prefer-at` rule](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/68786b805ec4c888dc07c05d3ea7c860cc3d9945/docs/rules/prefer-at.md#checkallindexaccess), `charAt` appears to be misspelled as `chatAt`. If this is intentional, it is unclear as to why it fails as it is listed under the `checkAllIndexAccess` option.

https://github.com/sindresorhus/eslint-plugin-unicorn/blob/68786b805ec4c888dc07c05d3ea7c860cc3d9945/docs/rules/prefer-at.md#L88

**Comment by fisker** [comment]
Nice catch, want help to fix it?

**Comment by fisker** [comment]
There is also a variable named incorrectly, [isClosingBraceToken](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/68786b805ec4c888dc07c05d3ea7c860cc3d9945/rules/prefer-at.js#L178) should named `closingBracketToken`
