### ISSUE TITLE
Rule proposal: `prefer-code-point`

### ISSUE THREAD

**Issue by fisker** [sindresorhus/eslint-plugin-unicorn#1490]
Prefer `String#codePointAt()` over `String#charCodeAt()`
Prefer `String.fromCodePoint()` over `String.fromCharCode()`

## Fail

```js
const unicorn = '🦄'.charCodeAt(0).toString(16)
// -> 'd83e'
```

```js
const unicorn = String.fromCharCode(0x1f984)
// -> '濾'
```

## Pass

```js
const unicorn = '🦄'.codePointAt(0).toString(16)
// -> '1f984'
```

```js
const unicorn = String.fromCodePoint(0x1f984)
// -> '🦄'
```

This rule should use suggestions instead of auto-fix.

**Comment by fregante** [comment]
> This rule should use suggestions instead of auto-fix.

Why? Only due to support?

**Comment by fisker** [comment]
Because it result differently.

**Comment by sindresorhus** [comment]
This is now accepted.
