### ISSUE TITLE
`require-post-message-target-origin` should ignore some cases

### ISSUE THREAD

**Issue by 2000yeshu** [sindresorhus/eslint-plugin-unicorn#1494]
This rule throws an error when using the postMessage method window.Worker but it shouldn't. For example,

```
this.worker = new Worker('/speedtest_worker.js');
this.worker.postMessage('some message');
```

It should ignore this case because there is no target origin parameter in the postmessage method of worker.

**Comment by 2000yeshu** [comment]
I would love to fix this issue. You can assign this issue to me.

**Comment by sindresorhus** [comment]
Please include a code full example of the cases it should ignore.

**Comment by fisker** [comment]
Duplicate of #1396
