### ISSUE TITLE
unicorn/prevent-abbreviations cannot be turned off

### ISSUE THREAD

**Issue by Slapbox** [sindresorhus/eslint-plugin-unicorn#1497]
**Issue:**

I was surprised to find that some rules seemingly cannot be turned off in conjunction with the recommended settings - but I've never seen this issue with any other plugin. Other rules disable fine, but not `unicorn/prevent-abbreviations`.

- unicorn/prevent-abbreviations

I tried turning it off, and also ignoring all files, but it autofixes all cases anyway - for example, replacing `err` with `error`.

**.eslintrc.js:**

```js

  extends: [
    'eslint:recommended',
    'plugin:react/recommended',
    'plugin:react-redux/recommended',
    'plugin:react-hooks/recommended',
    'plugin:regexp/recommended',
    'plugin:unicorn/recommended',
    'airbnb',
    'prettier',
  ],
  plugins: [
    'prettier',
    'flowtype',
    'import',
    'compat',
    'react',
    'react-redux',
    'react-hooks',
    '@emotion/eslint-plugin',
    'regexp',
    'xss',
    'unicorn',
  ],
  rules: {
    'unicorn/prevent-abbreviations': [
      'off', // 'off' is ignored
      {
        extendDefaultReplacements: false, // If I'm understanding, this should achieve the desired end, but also doesn't work
        ignore: [
          /./, // 'ignore' is ignored
        ],
      },
    ],
  }
```

**Comment by Slapbox** [comment]
Also tried `'unicorn/prevent-abbreviations': 0,` in desperation. Same result.

**Comment by Slapbox** [comment]
Same result using `overrides`:

```js
overrides: [
    {
      files: ['*.js'],
      rules: {
        'unicorn/prevent-abbreviations': 'off',
      },
    },
  ],
 ```

**Comment by yakov116** [comment]
@Slapbox no need to make a new comment just edit the first one.

**Comment by Slapbox** [comment]
Apologies, I forget that just because I'm the only subscriber at this point, doesn't necessarily mean I'm the only one getting notifications.

**Comment by Slapbox** [comment]
It's because I was checking whether this was enabled by seeing if `err` was replaced with `error`, but using that particular replacement as a test case was flawed because that's also handled by `catch-error-name` which I hadn't realized provided functionally identical results in that case.
