### ISSUE TITLE
Add 'consistent-destructuring' exceptions

### ISSUE THREAD

**Issue by Slapbox** [sindresorhus/eslint-plugin-unicorn#1501]
I've found that destructuring React's `state` and `props` off of `this` can be a bit unwieldy due to the depth of destructuring. It would be great to be able to exclude select patterns - in our particular case, `this.state` and `this.props`.

```js
    const { someMethod } = this;
    const { someBool } = this.state; // <<< unicorn/consistent-destructuring flags 'this.state'
```

This is pretty trivial as we can just move the state/props destructures above like this, but it would still be great if this was supported.

```js
    const { someBool } = this.state;
    const { someMethod } = this;
```

Maybe it's just me, but I find destructuring directly from `this.state` to be easier to reason about than first destructuring `state` off of `this`.

-------

It's also a bit of a pain when refactoring if you're getting rid of `someMethod` and you have the following:

```js
const { someMethod, state } = this
const { someBool } = state;
```

because now you're left with this:

```js
const { state } = this;
const { someBool } = state;
```

That destructuring assignment seems needless at that point, but to remove it requires updating two lines of code, which can be tedious during refactors. Even if each individual case only adds a couple seconds, it adds up in terms of time and reducing focus on the task at hand.

**Comment by futpib** [comment]
If `someMethod` is indeed a method isn't it better to call it like `this.someMethod()`?

**Comment by Slapbox** [comment]
That's safer, and my general preference, but sometimes it makes sense (in my opinion) to destructure it off if you're passing it down to a child component under the same name.

**Comment by RettentoRectangle** [comment]
Exceptions would be welcome!

In customElements there are many times we had to disable this rule because of e.g.: classList.

Example:
`
const { foo, bar, baz } = this
// ... later in that function
this.classList.toggle(styles.empty) // <--- Use destructured variables over properties.eslintunicorn/consistent-destructuring)
`

**Comment by fregante** [comment]
The rule was recently removed from the "recommended" config and this issue hasn't seen activity in a while. Closing for now

- https://github.com/sindresorhus/eslint-plugin-unicorn/pull/2260
