### ISSUE TITLE
Re-enable problematic rules

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/eslint-plugin-unicorn#151]
I had to disable (1091fdaaff82de2b9eac0f674a0dafc719a7bff7) some problematic rules in the default config until we manage to fix some issues with them:

`custom-error-definition`
- [x] #150 
- [x] #90
- [ ] checking other problems(fisker)

`no-fn-reference-in-iterator`
- [x] #121 
- [x] enable in #666

`no-unsafe-regex`
- [ ] #153

**Comment by sindresorhus** [comment]
// @johnwu93 In case you have some time to look into any of these :)

**Comment by johnwu93** [comment]
@sindresorhus Sure, I will be happy to look at them :)

**Comment by johnwu93** [comment]
I will write a pull request for them

**Comment by fisker** [comment]
I'm going to rewrite `no-fn-reference-in-iterator` when I have time.

**Comment by sindresorhus** [comment]
Closing in favor of https://github.com/sindresorhus/eslint-plugin-unicorn/pull/680.
