### ISSUE TITLE
Export an `all` config

### ISSUE THREAD

**Issue by Yash-Singh1** [sindresorhus/eslint-plugin-unicorn#1510]
Export an `all` config that contains the default options for all of the rules (except for deprecated ones).

**Comment by sindresorhus** [comment]
Seems like other plugins do this too, so I guess we could.

https://github.com/typescript-eslint/typescript-eslint/blob/8218055d6dfd94c9e6c8645848f981d9d51ce08c/packages/eslint-plugin/src/configs/all.ts

The list should be automatically generated.
