### ISSUE TITLE
Make `prefer-spread` allow `Array.from({length: N})`

### ISSUE THREAD

**Issue by jfmengels** [sindresorhus/eslint-plugin-unicorn#159]
I sometimes use `Array.from({length: N})` in order to create an array with a certain number of elements in it, so that I can later map over it.

Example:
```js
Array.from({length: 10}).map((v, index) => index);
// [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
```

I usually use Lodash's [times function](https://lodash.com/docs/4.17.5#times) for that, but I prefer not to use when I write packages.

If we want to add an exception for this, I think we should allow it when the first argument is an object literal with a `length` property, though we could also allow it when the argument is an object literal and check no further than that. Let me know what you think.

(cc @bdougherty who worked on this)

**Comment by sindresorhus** [comment]
I think that's an ugly hack that takes advantage of a quirk in the language.

Why not just do `[...Array(10).keys()]`?

**Comment by jfmengels** [comment]
Ah, I didn't know about that possibility. I agree that mine is a hack.
I've asked around and someone proposed `Array.from(10).fill(null)` (and then map over it), which is probably going to be my new way of doing it (maybe along with yours).

Feel free to close this then :)

**Comment by meatwallace** [comment]
@jfmengels - worth mentioning that you can use `Array#from` with a map fn ex. `Array.from(new Array(100), (v, index) => index` which has the benefit of only creating a single intermediary array
