### ISSUE TITLE
Support `expect().toMatchInlineSnapshot()` by default in `template-indent`

### ISSUE THREAD

**Issue by remcohaszing** [sindresorhus/eslint-plugin-unicorn#1594]
Jest has a matcher [toMatchInlineSnapshot(\`\`)](https://jestjs.io/docs/expect#tomatchinlinesnapshotpropertymatchers-inlinesnapshot). This accepts a template literal and optional property matchers.

This is roughly equal to `toBe('')`, except:

1. Custom serializers are used to generate the string.
2. Jest can update the template string automatically.
3. The value is dedented before comparison.

Prettier already deals with indentation for jest snapshots, but it’s not entirely consistent. It accepts 3 indentation levels:

1. Fully dedented.
   ```js
   it('test', () => {
     expect({ foo: 'bar' }).toMatchInlineSnapshot(`
   Object {
     "foo": "bar",
   }
   `);
   });
   ```
2. Indented to match the intendation of the function call.
   ```js
   it('test', () => {
     expect({ foo: 'bar' }).toMatchInlineSnapshot(`
     Object {
       "foo": "bar",
     }
     `);
   });
   ```
3. Indented to match the intendation of the function call +1 indentation.
   ```js
   it('test', () => {
     expect({ foo: 'bar' }).toMatchInlineSnapshot(`
       Object {
         "foo": "bar",
       }
     `);
   });
   ```

This rule can already support this rule, but considering Jest’s popularity I think it makes sense to support this by default in the `template-indent` rule. This helps write more consistent code and aligns with prettier indentation level 3.

This can already be configured using the following selector:

```js
CallExpression[callee.type="MemberExpression"][callee.object.type="CallExpression"][callee.object.callee.name="expect"][callee.property.name="toMatchInlineSnapshot"] > TemplateLiteral
```

**Comment by fisker** [comment]
If there is a snapshot serializer, will white space matter?

**Comment by remcohaszing** [comment]
Any whitespace used for padding the snapshot indentation doesn’t matter. Other whitespace does matter., such as whitespace used for indentation of the content after dedenting.

There’s always a snapshot serializer. Did you mean a custom snapshot serializer? For those it doesn’t matter.

You can use the [jest-axios-snapshot tests](https://github.com/remcohaszing/jest-axios-snapshot/blob/main/jest-axios-snapshot.test.ts) to fiddle around if you want to make sure.

**Comment by fisker** [comment]
> Did you mean a custom snapshot serializer?

Yes.

**Comment by fisker** [comment]
@SimenB Sorry for bothering you. 

Can you confirm that, code inside `toMatchInlineSnapshot` is safe to increase indentation level even if a custom snapshot serializer is used?

**Comment by SimenB** [comment]
Jest accepts any indentation yes, but blows it away when updating the snapshot (if applicable). I don't think custom serializers affect that at all

**Comment by fisker** [comment]
Thank you! @SimenB

**Comment by JounQin** [comment]
<img width="699" alt="image" src="https://user-images.githubusercontent.com/8336744/181258843-417e8f60-ecc3-49ef-ac00-72d86b1bdcc8.png">

@fisker 

I'm still having this issue with `vitest`.

**Comment by fisker** [comment]
I don't understand the question, please open a new issue with your code instead of paste a image.

**Comment by JounQin** [comment]
@fisker 

https://github.com/un-ts/domiso/blob/main/.eslintrc#L5

Try to remove this line and run `yarn lint:es`
