### ISSUE TITLE
Rule proposal: `no-thenable`

### ISSUE THREAD

**Issue by fisker** [sindresorhus/eslint-plugin-unicorn#1596]
### Description

If object is defined as thenable, once it's accidentally used in an await expression, your program may hangs. [Airbnb has similar rule for module exports.](https://github.com/airbnb/javascript/blob/366bfa66380c08304101c6add46355696e90b348/packages/eslint-config-airbnb-base/rules/es6.js#L68)

I want forbid more cases.

Maybe we don't even need care it's a function or not. Objects except Promise shouldn't have a `then` property.

### Fail

```js
const foo = {then() {}}
```

```js
const foo = {get then() {}}
```

```js
export const then = () => {};
```

```js
export {then}
```

```js
class Foo {
	then;
}
```

```js
class Foo {
	static then;
}
```

```js
class Foo {
	then() {}
}
```

```js
class Foo {
	static then() {}
}
```

```js
class Foo {
	get then() {}
}
```

```js
class Foo {
	static get then() {}
}
```

```js
foo.then = () => {};
```

```js
Foo.prototype.then = () => {};
```

```js
Object.defineProperty(foo, 'then', {value(){}})
```

```js
Reflect.defineProperty(foo, 'then', {value(){}})
```

```js
Object.fromEntries(['then', () => {}])
```

### Pass

```js
const foo = {notThen() {}}
```

**Comment by sindresorhus** [comment]
This is now accepted.
