### ISSUE TITLE
Remove/Move/Fold `Usage` section in readme?

### ISSUE THREAD

**Issue by fisker** [sindresorhus/eslint-plugin-unicorn#1602]
[This section](https://github.com/sindresorhus/eslint-plugin-unicorn#usage) is getting longer and longer, 

1. Remove it, `extends: "plugin:unicorn/recommended"` is recommended. Only if user want config rules one by one need it, I believe they know how to do it without this section.
2. Move to under `Rules` section?
3. Fold it with `<details>`?

**Comment by sindresorhus** [comment]
1. We can just remove it and link to https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/configs/recommended.js
