### ISSUE TITLE
`no-array-for-each`: is not handling optional chaining when auto-fixing

### ISSUE THREAD

**Issue by Primajin** [sindresorhus/eslint-plugin-unicorn#1632]
We have many places in the code where we run `forEach` behind an optional chain.

```js
myIds?.forEach(id => {
  // do something with that id
});
```

This is correctly flagged as `ESLint: Use for…of instead of Array#forEach(…).(unicorn/no-array-for-each)` 👍🏻 
However the autofix is not picking it up.

once I change it to:
```js
if (myIds) {
  myIds.forEach(id => {
    // do something with that id
  });
}
```
it automagically fixes it to:
```js
if (myIds) {
  for (const id of myIds) {
    // do something with that id
  });
}
```

can we maybe add a rule to the autofixer that if there is an optional chain just wrap the block in an `if`? 🤔

**Comment by fisker** [comment]
It make sense. When I implement this rule, I didn't expect the optional version use too much in a codebase, so I skipped that. However, the auto fix part in this rule is already really complated.

PR wellcome.

**Comment by fisker** [comment]
Or maybe fix to this version

```js
if (Array.isArray(myIds)) {
  for (const id of myIds) {
    // do something with that id
  });
}
```

?

**Comment by Primajin** [comment]
OK great, I have never implemented a lint fixer - so let's see if I can come up with a PR 🤞🏻 😅

**Comment by Primajin** [comment]
Great thanks!
