### ISSUE TITLE
Error during run of eslint plugin unicorn after upgrade to eslint@8

### ISSUE THREAD

**Issue by rajzik** [sindresorhus/eslint-plugin-unicorn#1634]
After running eslint I got error: 

`Failed to load plugin 'unicorn' declared in 'BaseConfig » eslint-config-oriflame/future': Cannot find module 'eslint/use-at-your-own-risk' from 'node_modules/eslint-plugin-unicorn/rules/utils/get-builtin-rule.js'`

Not sure

Currently upgrading our build system to latest version of packages and when I run tests it will fail, and when I enable unicorn in eslint it will fail on every file.

Code can be found here: 
https://github.com/Oriflame/lumos/tree/migrate-to-beemo-v2

I know this isn't enough info about the issue and if you provide some way how to debug it and provide more information, please write me.

**Comment by fisker** [comment]
It's possible to be a node.js version problem.
If the error is during test, it can also be Jest issue, moduleWrapper can be used as workaround.

**Comment by fisker** [comment]
I'm on my cellphone, I didn't checkout your repo.

**Comment by rajzik** [comment]
Currently have node 16. I think this shouldn't be an issue.
But it seems like jest is the problem. Is there any possible workaround on how to fix it?

**Comment by fisker** [comment]
https://github.com/eslint/eslint/issues/14936#issuecomment-906768517

Point it to the correct js file.

**Comment by rajzik** [comment]
@fisker module mapper helped.

```js
module.exports = {
  preset: 'jest-preset-oriflame',
  'moduleNameMapper': {
    'eslint/use-at-your-own-risk': 'eslint/lib/unsupported-api.js'
  }
};
```

Thanks for the help. I am not sure if we can fix it or just close this issue.

**Comment by rajzik** [comment]
This is issue of the jest 
[#9771](https://github.com/facebook/jest/issues/9771)
so we can close this.

**Comment by Slapbox** [comment]
@fisker this seems to be a legitimate unresolved issue in `eslint-plugin-unicorn`.

Removing every trace of Jest from our config doesn't resolve this but removing every trace of Unicorn does.
