### ISSUE TITLE
Don't auto-fix `Array.from({ length: 12 })`

### ISSUE THREAD

**Issue by sergeysova** [sindresorhus/eslint-plugin-unicorn#164]
Before:

```js
Array.from({ length: 123 })
```

After autofix:

```js
[...{ length: 123 }]
```

But result is wrong:

![image](https://user-images.githubusercontent.com/5620073/37364556-eb0fc604-270b-11e8-9502-626fb5fb8a1f.png)

**Comment by sindresorhus** [comment]
Yeah, we shouldn't auto-fix that. Although you really shouldn't do that. There are better ways to achieve what you want: https://github.com/sindresorhus/eslint-plugin-unicorn/issues/159

**Comment by sergeysova** [comment]
Maybe add option/rule to that case?

**Comment by sergeysova** [comment]
Thanx

**Comment by sergeysova** [comment]
@sindresorhus maybe release new version with this and #161 ?

**Comment by sindresorhus** [comment]
Done

**Comment by sergeysova** [comment]
Thank you
