### ISSUE TITLE
Rule proposal: `prefer-structured-clone`

### ISSUE THREAD

**Issue by fisker** [sindresorhus/eslint-plugin-unicorn#1640]
### Description

Prefer [`structuredClone`](https://developer.mozilla.org/en-US/docs/Web/API/structuredClone) when deep-copying.

### Fail

```js
const clone = JSON.parse(JSON.stringify(foo));
```

```js
const clone = _.deepClone(foo);
```

### Pass

```js
const clone = self.structuredClone(foo)
```

**Comment by sindresorhus** [comment]
Drop `dom` from the rule name as Node.js 17 supports it too. There's nothing DOM specific about it (other than it throwing a DOMException, but that's just the reality of it being in a HTML specification).

**Comment by sindresorhus** [comment]
The Lodash method is `_.cloneDeep()`, not `_.deepClone()`. Should also match `lodash.cloneDeep()`

**Comment by sindresorhus** [comment]
Maybe it should also match some popular deep clone packages on npm: https://npms.io/search?q=deep+clone

**Comment by sindresorhus** [comment]
Accepted

**Comment by fisker** [comment]
ESLint rejected to add to core rules https://github.com/eslint/eslint/issues/18354
