### ISSUE TITLE
`prefer-object-has-own` is available in ESLint

### ISSUE THREAD

**Issue by haykam821** [sindresorhus/eslint-plugin-unicorn#1644]
In ESLint 8.5.0, the `prefer-object-has-own` rule was added (https://github.com/eslint/eslint/pull/15346). The rule added by this plugin should be deprecated as was done with `prefer-exponentiation-operator`.

**Comment by fisker** [comment]
We'll run it on our tests, if everything works fine, then we can deprecate it.
