### ISSUE TITLE
Remove `env` and `parserOptions` from preset configs

### ISSUE THREAD

**Issue by fisker** [sindresorhus/eslint-plugin-unicorn#1659]
The idea is good, but user may want to have different settings, and we are overriding them from another config.

```js
{
	extends: [
		'another-config',
		'plugin:unicorn/recommanded',
	]
}
```

Can we remove them?

**Comment by sindresorhus** [comment]
We are overriding those because we only intend to support the latest syntax and `module` type. If we instead just document that, many users will miss it and waste our time opening issues about rules not working with non-module type or older syntax versions.
