### ISSUE TITLE
Change default of `catch-error-name` rule

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/eslint-plugin-unicorn#167]
I know the convention in Node.js is to use `err` for error variable names, but is it really worth saving two characters over? I would much prefer to use `error` instead.

```js
try {

} catch (error) {

}
```

This makes for more readable code.

@SamVerschueren @kevva Thoughts?

**Comment by kevva** [comment]
I don't know why, but I've always been in favour of short variable names á la Node.js. Following conventions makes them as easy to read as if you'd write `error` instead of `err`, or `callback` instead of `cb` etc.

I mostly use longer and more descriptive names for functions.

**Comment by sindresorhus** [comment]
I used to be like that before too, but Swift has thought me the value of descriptive variable names.

**Comment by dandonahoe** [comment]
I just change my default to `error` as well. Totally nit-picky, but I'm doing a React project and I rarely see `err` used. I almost always favor descriptive titles with the option to abbreviate only when the description gets out of control.

Anyway, good linter overall. Thanks.
