### ISSUE TITLE
Rule clash when using `no-useless-undefined`, `no-null`, TypeScript and `React.createContext`

### ISSUE THREAD

**Issue by kachkaev** [sindresorhus/eslint-plugin-unicorn#1684]
I added `plugin:unicorn/recommended` to a few side projects and my code got noticeably more coherent. Great plugin folks!

I have noticed one interesting clash between linting rules and wonder if it can be addressed by the plugin. Here’s my original TypeScript code (before Unicorn):

```ts
import * as React from "react";

interface MyContextValue {
  x: number;
  y: string;
};

export const MyContext = React.createContext<MyContextValue | null>(null);

export const useMyContext = (): MyContextValue => {
  const result = React.useContext(MyContext);
  if (result === null) {
    throw new Error("No MyContext value available");
  }
  return result;
}
```

Once I added recommended Unicorn rules, I got saw near error near `export const MyContext`): `` Use `undefined` instead of `null` (unicorn/no-null)``. Me: _OK,_

```diff
 import * as React from "react";

 interface MyContextValue {
   x: number;
   y: string;
 };

-export const MyContext = React.createContext<MyContextValue | null>(null);
+export const MyContext = React.createContext<MyContextValue | undefined>(undefined);

 export const useMyContext = (): MyContextValue => {
   const result = React.useContext(MyContext);
-  if (result === null) {
+  if (result === undefined) {
     throw new Error("No MyContext value available");
   }
   return result;
 }
```

Unicron: `` Do not use useless `undefined` (unicorn/no-useless-undefined) ``. Me: _OK,_

```diff
-export const MyContext = React.createContext<MyContextValue | undefined>(undefined);
+export const MyContext = React.createContext<MyContextValue | undefined>();
```

TypeScript: ``Expected 1 arguments, but got 0.``. Me: _React typings must be incomplete and I should submit a PR that allows omitting `undefined`._ [React typings](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/75f6dff53de980e934bb1117d431f3a8259ae771/types/react/index.d.ts#L383-L387):

```ts
    function createContext<T>(
        // If you thought this should be optional, see
        // https://github.com/DefinitelyTyped/DefinitelyTyped/pull/24509#issuecomment-382213106
        defaultValue: T,
    ): Context<T>;
```

Link: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/24509#issuecomment-382213106. Me: _Hmm, this looks like a dead end_ 😅

Assuming that we can’t easily update React typings, looks like we should either:
- allow `null` in `createContext` / `React.createContext`
  or
- stop marking `undefined` as useless if it’s an argument of `createContext` / `React.createContext`. 

In the meantime, my workaround is:

```diff
+ // eslint-disable-next-line unicorn/no-useless-undefined
 const MyContext = React.createContext<MyContextValue | undefined>(undefined);
```

or:

```diff
 // .eslintrc.cjs
 module.exports = {
   extends: [
     "...",
     "plugin:unicorn/recommended",
   ],
+  rules: {
+    "unicorn/no-useless-undefined": "off", // https://github.com/sindresorhus/eslint-plugin-unicorn/issues/1684
+  },
 };
```

For the record, I am using `eslint-plugin-unicorn@40.0.0` and `@types/react@17.0.38`. WDYT folks?

**Comment by fisker** [comment]
I think 

> stop marking undefined as useless if it’s an argument of createContext / React.createContext.

Make sense.

**Comment by fisker** [comment]
In case you missed, we also have `checkArguments` option in `no-useless-undefined` rule, https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/no-useless-undefined.md#checkarguments

**Comment by kachkaev** [comment]
👋 Thanks for sharing your thoughts @fisker! See https://github.com/sindresorhus/eslint-plugin-unicorn/pull/1688 👀

**Comment by vzakharov** [comment]
> In case you missed, we also have `checkArguments` option in `no-useless-undefined` rule, https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/no-useless-undefined.md#checkarguments

Sorry for reviving an ancient thread, stumbled across it while researching, but I think just adding the option might be an overkill (because sometimes you DO want to check arguments). Obviously, you can eslint-ignore a specific line instead — BUT would it be possible for the linter to actually figure out TypeScript’s type signature and not complain if it does require `| undefined` (not an optional arg)? I’m guessing no but just to be sure.
