### ISSUE TITLE
Rule proposal: `no-useless-switch-case`

### ISSUE THREAD

**Issue by remcohaszing** [sindresorhus/eslint-plugin-unicorn#1698]
### Description

When a switch case without a consequent is directly followed by a default case, it’s redundant. I believe it should be removed. The auto fixer can remove the redundant case.

This has also beem proposed in https://github.com/eslint/eslint/issues/14924, but it was dismissed because it doesn’t meet the criteria for new ESLint core rules.

### Fail

```js
switch (discriminant) {
  case 'redundant':
  default:
    break;
}
```

### Pass

```js
switch (discriminant) {
  case 42:
    break;
  default:
    break;
}
```

**Comment by sindresorhus** [comment]
I would name it `no-useless-switch-case` as case could also mean "enum case" in TypeScript.

**Comment by remcohaszing** [comment]
> Already available in sonarjs https://github.com/SonarSource/eslint-plugin-sonarjs/blob/master/docs/rules/no-small-switch.md

That rule also applies to a switch, but it’s not the same.

**Comment by sindresorhus** [comment]
Accepted
