### ISSUE TITLE
String.substring is incorrectly considered legacy

### ISSUE THREAD

**Issue by clshortfuse** [sindresorhus/eslint-plugin-unicorn#1711]
Put simply, `String.subtr` can be replaced with `String.splice`. That's fine. `substr` is deprecated and legacy.

But `String.substring` is not legacy and has legitimate uses to avoid needless math. For example:

````js
const sample = '<html dir="ltr" language="en"> text </html>';
const openTag = sample.indexOf('<');
const closeTag = sample.indexOf('>');
const inner = sample.substring(openTag + 1, closeTag);
// OR:
// const inner = sample.substring(openTag + 1, sample.indexOf('>'));
````

Without it, you'd have to calculate and apply math needlessly, possibly requiring storing extra variables. `substring` is `from, to`, where as `slice` is `from, length`. 

It seems the idea idea to include `substring` stems from a user's Stackover answer, and another user's comment incorrectly attributing legacy to both:

https://stackoverflow.com/questions/2243824/what-is-the-difference-between-string-slice-and-string-substring

In reality MDN says:

>Furthermore, substr() is considered a legacy feature in ECMAScript and could be removed from future versions, so it is best to avoid using it if possible.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substring#the_difference_between_substring_and_substr

**Comment by sindresorhus** [comment]
I still think it's better to be consistent and use `slice` always, but I guess we could add an option to allow `substring`.

**Comment by clshortfuse** [comment]
I realized I had mistaken `substr` with `slice`. It seems there's no easy replacement for `substr`. 

I said: >substring is from, to, where as slice is from, length.

This is false. They're the same (with the exception of the negative index) Just more reason why to just always use `slice`, seems like.
