### ISSUE TITLE
`unicorn/prefer-export-from` breaks type exports in typescript projects using the `isolatedModules` flag.

### ISSUE THREAD

**Issue by nrgnrg** [sindresorhus/eslint-plugin-unicorn#1727]
When autofixing exports in ts projects `unicorn/prefer-export-from` will change this:

```ts
import UIAvatar, {
  UIAvatarProps,
} from "./UIAvatar";

export type { UIAvatarProps };
export default UIAvatar;
```

into 

```ts
export { default, UIAvatarProps } from "./UIAvatar";
```

Which results in a typescript error `Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.ts(1205)`

The correct fix should be:

```ts
export { default, type UIAvatarProps } from "./UIAvatar";
```

Type only exports should be prefixed with `type`.

I've also seen this problem happen the other way around before where a non type export gets bundled into an `export type { ... } from ""` and has broken internal library code as the autofix is applied using commit hooks.

**Comment by fisker** [comment]
PR welcome.
