### ISSUE TITLE
 [no-useless-undefined] incorrect fix for fn.bind(undefined, undefined)

### ISSUE THREAD

**Issue by rontav** [sindresorhus/eslint-plugin-unicorn#1738]
`no-useless-undefined` applies wrong fixes to bind function.
It's solved by using `checkArguments` option, but this means that the recommended config can break code when applying autofix to an entire codebase.

Example:
```js
function fn(arg1, arg2) {
    console.log('arg1', arg1, 'arg2', arg2);
}

(fn.bind(undefined, undefined))(3); // arg1 undefined arg2 3
// apply autofix
(fn.bind())(3);                     // arg1 3 arg2 undefined
// also, ts error: Expected at least 1 arguments, but got 0.
```

**Comment by fisker** [comment]
We can ignore the parameters in `.bind()`. Except the first one.

**Comment by rontav** [comment]
Not really. As you can see in the example, the behaviour of the functions changes if the second parameter is not present (`arg1` gets the value `3`, instead of `arg2` being `3`)

**Comment by fisker** [comment]
I mean we should ignore these `undefined` in our rule.
