### ISSUE TITLE
Include reason to use rule in documentation

### ISSUE THREAD

**Issue by fregante** [sindresorhus/eslint-plugin-unicorn#1752]
Very often I find rules that have no explicit reason to exist and one is supposed to just _get it_. This is not Unicorn’s fault as ESLint’s docs are equally lacking (and including text like: "When not to use this rule: Don't use it when you don't need it")

Especially when collaborating with others using the same set of rules in a project, I think this is a crucial piece of information together with:

- https://github.com/sindresorhus/eslint-plugin-unicorn/issues/1751

The lack of it can frustrate developers and lead to the deactivation of the rule.

**Comment by sindresorhus** [comment]
Do you have any specific Unicorn rules we should prioritize for this?

**Comment by fregante** [comment]
Not sure, it appears that actually many/most rules actually do have such paragraph, like, random picks:

- https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prefer-add-event-listener.md
- https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prefer-module.md

Maybe this one is an _exception_ (…) more than the _rule_ (😏):

- https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prefer-number-properties.md

I think `no-array-reduce` could also have further details since it's controversial:

- https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/no-array-reduce.md

**Comment by fregante** [comment]
No reason included:

- https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/explicit-length-check.md
- Reason kinda found here: https://github.com/sindresorhus/eslint-plugin-unicorn/issues/12
