### ISSUE TITLE
Definition for rule 'unicorn/import-index' was not found eslint

### ISSUE THREAD

**Issue by s7sundar** [sindresorhus/eslint-plugin-unicorn#177]
The mentioned `Definition for rule 'unicorn/import-index' was not found eslint` error is displaying on this line.  If anyone knows how to resolve this please let me know

> import React, { Component } from 'react';

**Comment by sindresorhus** [comment]
I'm going to assume this was a temporary issue with ESLint or something else since no one else has experienced it. Please open a new issue if this is still a problem.
