### ISSUE TITLE
regex-shorthand fixer does not escape RegExp constructor strings properly

### ISSUE THREAD

**Issue by MrHen** [sindresorhus/eslint-plugin-unicorn#178]
Rule:

```
"unicorn/regex-shorthand": "error",
```

Original code:

```
const numberRegex = new RegExp('(?=.*[0-9])');
```

Fixed code:

```
const numberRegex = new RegExp('(?=.*\d)');
```

Should be:

```
const numberRegex = new RegExp('(?=.*\\d)');
```

Example of altered behavior:

```

const original = new RegExp('(?=.*[0-9])');
const actual = new RegExp('(?=.*\d)');
const expected = new RegExp('(?=.*\\d)');

console.log({
  original: original.test('aaa111'), // true
  actual: actual.test('aaa111'),     // false
  expected: expected.test('aaa111'), // true
});
```

**Comment by SamVerschueren** [comment]
This seems to be only an issue when we are using a `new RegExp()` with a string argument. I looked into it but it's harder then I initial thought.

**Comment by MrHen** [comment]
Honestly, I wouldn't mind if it just ignored strings. Doing bad things is bad -- doing nothing is an improvement. The only reason I caught it was another lint rule calling out a bogus escape sequence in the string.
