### ISSUE TITLE
GitHub proposal: enable discussion

### ISSUE THREAD

**Issue by jimmywarting** [sindresorhus/eslint-plugin-unicorn#1791]
### Description

In node-fetch it got a bit overwhelming with random issues popping up about proposals, questions and other things that wasn't issues or bug that could be worked on. 

I got tiered of it and it was overwhelming to look at all the issues of what is an actual issue/task/bug that i could sitt down and try to solve & work on and some really old issues got buried. So I enabled discussions for things such as proposals, question and Q&A and started to move them over there as well as linking them to the discussion page instead. 

I suggest that you do the same thing for "rule proposal".
When a proposal becomes "accepted" then it can be turned into an issue such as:

> ## Add new proposal: prefer x over y
> ...description
>
> ref: discussion/32132

**Comment by sindresorhus** [comment]
I prefer using issues for this.

**Comment by sindresorhus** [comment]
I agree discussions makes sense for Q&A, but this project does not really need a place to ask questions. In most cases, either it's a bug or feature request.
