### ISSUE TITLE
`prefer-string-slice` is not autofixable

### ISSUE THREAD

**Issue by DecathectZero** [sindresorhus/eslint-plugin-unicorn#1794]
Mentioned here, https://github.com/sindresorhus/eslint-plugin-unicorn/blob/v40.0.0/docs/rules/prefer-string-slice.md
eslint will attempt to autofix `prefer-string-slice` rule. However, this can be quite disastrous as the assumed autofix produces non-equivalent behavor.

Here's a quick demo in the console:
![image](https://user-images.githubusercontent.com/5643574/163315852-280836c0-7519-47dd-84ec-69383ed63169.png)

The autofix attempts to directly replace `substring` or `substr` with `slice`. Instead it is up the developer to carefully evaluate and change the logic so that `slice` works. 

`substring` allows reading the string backwards. `substr` is completely different than `slice`.

**Comment by fisker** [comment]
Have actually try this rule? We don't simply replace the method name.
