### ISSUE TITLE
Node module specific rules

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/eslint-plugin-unicorn#18]
Would be cool to enforce some best practices and prevention of common pitfalls on the most popular Node.js modules.

For example, with [`meow`](https://github.com/sindresorhus/meow) I want to enforce using a template literal instead of a normal string as the first argument.

I'm thinking we can activate the rule if we detect an import of the specific module.

Any requests? Common pitfalls you've seen? Best practices?

**Comment by jamestalmage** [comment]
It all comes back to type analysis. The easier it is to infer that a given variable is of a given type, the easier it is to write this type of rule.

**Comment by sindresorhus** [comment]
@jamestalmage Sure, but in this case, the template literal or string is always put inline in the function call. If not, we could always use path analysis as 99% certainly in the same file.

**Comment by jamestalmage** [comment]
Oh - I meant ensuring `meow` was `meow`. But yes, it also applies to the template variable as well. Not against it - just saying adding a lot of type dependent rules without a good typing system is burdensome (echoing what we have already said)

**Comment by sindresorhus** [comment]
@jamestalmage Yeah, totally, but don't limit your brainstorming to type dependent rules. Lots of other things that could be useful. I should have found a better example in the issue description than a type dependent one.

**Comment by jamestalmage** [comment]
My point was that type analysis is required for any "uses XXX appropriately" rule. You have to narrow down that a given variable is of type XXX. It's easy for `meow` since you basically always use the import directly.

**Comment by fregante** [comment]
Closing discussion as inactive for 4 years. Now there's a node-specific plugin: https://github.com/mysticatea/eslint-plugin-node
