### ISSUE TITLE
Add plugins: ['unicorn'] to recommended config

### ISSUE THREAD

**Issue by pksunkara** [sindresorhus/eslint-plugin-unicorn#180]
For example, `eslint-plugin-vue` does it like [this](https://github.com/vuejs/eslint-plugin-vue/blob/master/lib/configs/base.js#L19).

If you do this, could you please release v4 too for the people who are still using eslint v4.

**Comment by sindresorhus** [comment]
Sure, go for it.

**Comment by sindresorhus** [comment]
> If you do this, could you please release v4 too for the people who are still using eslint v4.

No, sorry, older versions are effectively unmaintained.

**Comment by pksunkara** [comment]
#182
