### ISSUE TITLE
Cannot find module 'eslint/use-at-your-own-risk' with ESLint v8.14.0

### ISSUE THREAD

**Issue by relima** [sindresorhus/eslint-plugin-unicorn#1800]
fresh install. packages:

{
  "browserslist": [
    "defaults"
  ],
  "devDependencies": {
    "@html-eslint/eslint-plugin": "^0.13.1",
    "@html-eslint/parser": "^0.13.1",
    "eslint": "^8.14.0",
    "eslint-config-airbnb-base": "^15.0.0",
    "eslint-plugin-compat": "^4.0.2",
    "eslint-plugin-import": "^2.26.0",
    "eslint-plugin-json": "^3.1.0",
    "eslint-plugin-no-unsanitized": "^4.0.1",
    "eslint-plugin-node": "^11.1.0",
    "eslint-plugin-promise": "^6.0.0",
    "eslint-plugin-sonarjs": "^0.13.0",
    "eslint-plugin-unicorn": "^42.0.0"
  },
  "dependencies": {
    "yarn": "^1.22.18"
  }
}

Failed to load plugin 'unicorn' declared in '.eslintrc.json': Cannot find module 'eslint/use-at-your-own-risk'

eslint does not run

```js
const code = 'that should be ok';
```

**Comment by fisker** [comment]
Can't help without more information,

**Comment by relima** [comment]
I have managed to get it to work by reinstalling node.
