### ISSUE TITLE
Rule proposal: Keep relative and non-relative imports separate

### ISSUE THREAD

**Issue by jorgegonzalez** [sindresorhus/eslint-plugin-unicorn#181]
Basically a rule enforcing the following separation:

![image](https://user-images.githubusercontent.com/12901172/43691169-5ee96444-98e6-11e8-8dd0-da9984a5a9f9.png)

Keeping these two types of imports separated helps to keep files a bit more organized. This should be fixable.

**Comment by zeorin** [comment]
Like https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/order.md?

**Comment by sindresorhus** [comment]
`import/order` is what you want, and if it's not good enough, open issue on the `import` plugin for possible enhancements.

**Comment by jorgegonzalez** [comment]
Didn’t know about that! Thanks!
