### ISSUE TITLE
Auto-fixing 'unicorn/no-array-for-each' breaks the code in certain cases

### ISSUE THREAD

**Issue by TimShilov** [sindresorhus/eslint-plugin-unicorn#1812]
Autofixing code with 'unicorn/no-array-for-each' rule creates a SyntaxError in cases where `.forEach()` callback has a default argument value.

Let's say I have this piece of code:
```js
items.forEach((item = 0) => {
    console.log(item)
});
```

This code works perfectly fine.

However, if I run `eslint --fix` command then 'unicorn/no-array-for-each' rule autofixes it to this:
```js
for (const item = 0 of items) {
    console.log(item)
}
```
This auto-fixed code has a syntax error in it: `SyntaxError: 'for-of' loop variable declaration may not have an initializer.`.

**Comment by fisker** [comment]
Nice catch!

**Comment by fisker** [comment]
Add an extra check here https://github.com/sindresorhus/eslint-plugin-unicorn/blob/166524a5613d9f0e27cb5bc505fe83d86ff9e7b2/rules/no-array-for-each.js#L362 should work.
