### ISSUE TITLE
wrong documentations

### ISSUE THREAD

**Issue by eng-dibo** [sindresorhus/eslint-plugin-unicorn#1838]
[documentations here](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/v42.0.0/docs/rules/number-literal-case.md) states that `const foo = 0xFF;` is wrong and correct at the same time

![image](https://user-images.githubusercontent.com/57308531/171303837-861e9642-ee89-449c-8735-12101d5d545f.png)

![image](https://user-images.githubusercontent.com/57308531/171303864-ab9ecee3-8c2e-45c6-b4cc-380c8be4e7ac.png)

**Comment by eng-dibo** [comment]
it will fail when using lowercase `0xff` and pass when using uppercase `0xFF`

**Comment by fisker** [comment]
We care about "x" too.
