### ISSUE TITLE
Remove `prefer-event-target` from recommended preset until Node.js v14 is EOL

### ISSUE THREAD

**Issue by FloEdelmann** [sindresorhus/eslint-plugin-unicorn#1854]
[`prefer-event-target`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prefer-event-target.md) (introduced in https://togithub.com/sindresorhus/eslint-plugin-unicorn/pull/1792 / https://github.com/sindresorhus/eslint-plugin-unicorn/releases/tag/v43.0.0) suggests using `EventTarget` instead of `EventEmitter`, since `EventTarget` is cross-platform.

However, in Node.js v14 (which is still in Maintenance LTS), `EventTarget` is not available for end user code: https://nodejs.org/docs/latest-v14.x/api/events.html#events_eventtarget_and_event_api

In Node.js v16 (current LTS), there is no such restriction anymore: https://nodejs.org/docs/latest-v16.x/api/events.html#eventtarget-and-event-api

Thus, I'd suggest to remove `prefer-event-target` from the recommended preset until [Node.js v14 is EOL](https://nodejs.org/en/about/releases/) (2023-04-30).

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/eslint-plugin-unicorn/releases/tag/v43.0.1

**Comment by fregante** [comment]
What do you think about offering per-version presets? Advantages:

- you can have nodenext *pioneers* test out new rules in production
- once nodenext becomes current you just import it in the recommended config

**Comment by sindresorhus** [comment]
@fregante Not sure it's worth the effort. It would only apply to 3 rules. And what does event "nodenext" entail? Who would want a preset that can potentially require any future Node.js version? It would have to be Node.js-version specific presets and I just don't think there are enough rules to make it worth it. You can already just manually enable the extra rules you like. Maybe we could document "future recommended rules" or something?

**Comment by sindresorhus** [comment]
^ (And use a new issue next time. A lot of people will miss out on the discussion when it's just in a PR thread)

**Comment by bmish** [comment]
I agree that additional presets generally aren't worth the effort / maintenance burden. But I do like to make it clear why a particular rule isn't recommended yet and whether it is intended to become recommended or not by adding one of these notes to the rule documentation:

```
TODO: Add this rule to the `recommended` preset` once we drop support for Node 14.
```

```
TODO: Add this rule to the `recommended` preset` in the next major release.
```

```
Note: This rule is not suitable to become a `recommended` rule due to X reason.
```
