### ISSUE TITLE
`prefer-spread` should exclude `Array.from`

### ISSUE THREAD

**Issue by kidonng** [sindresorhus/eslint-plugin-unicorn#1876]
Benchmarks ([without `mapFn`](https://jsben.ch/LyuiN) / [with `mapFn`](https://jsben.ch/zQy7i)) show `[...spread]` is generally 30-40% slower than `Array.from`, when operating on a large `Set`.

In particular, `[...arrayLike].map(fn)` generates a intermediate array, while `Array.from(arrayLike, mapFn)` does not.

I agree spread is easier to write, but `Array.from` is just as readable and serves as a faster alternative.

A side note: "spread operator" is not an appropriate term (even if widely used), because [spread is not an operator](https://stackoverflow.com/a/37152508). The referenced MDN page in the docs is titled "Spread Syntax" for this reason.

**Comment by sindresorhus** [comment]
The performance difference is probably negligible in production code. Micro-benchmarks do not reflect real situations.

**Comment by kidonng** [comment]
I'm getting different benchmark results in another device, so my claim does not stand.

I guess JavaScript engines will be doing optimizations for these common patterns, so the final result does not differ a lot.
