### ISSUE TITLE
Replace `safe-regex` with modern alternative

### ISSUE THREAD

**Issue by mcmxcdev** [sindresorhus/eslint-plugin-unicorn#1882]
There is the https://github.com/sindresorhus/eslint-plugin-unicorn/blob/v43.0.2/docs/rules/no-unsafe-regex.md rule which uses [safe-regex](https://github.com/substack/safe-regex) under the hood.

I had a short look at  `safe-regex` and there haven't been any new releases since years. It would be great to replace this with a maintained dependency instead.

**Comment by mcmxcdev** [comment]
It seems there has been some discussion already in: https://github.com/sindresorhus/eslint-plugin-unicorn/issues/153

**Comment by fregante** [comment]
I think this is tracked in #153 as you mentioned
