### ISSUE TITLE
Docs with new eslint config spec

### ISSUE THREAD

**Issue by jjangga0214** [sindresorhus/eslint-plugin-unicorn#1884]
Eslint announced a new config spec.
https://eslint.org/docs/latest/user-guide/configuring/configuration-files-new
It'd be better to be guided in README, along with the legacy config example.

Thanks.

**Comment by fregante** [comment]
Basically a duplicate of your own issue https://github.com/sindresorhus/eslint-plugin-unicorn/issues/1885

If the config is changed, the readme is included in the same PR
