### ISSUE TITLE
Export new eslint config

### ISSUE THREAD

**Issue by jjangga0214** [sindresorhus/eslint-plugin-unicorn#1885]
Currently, configs/all.js and configs/recommended.js do not follow the esilnt's new config system. I think new modules should be created and exported along with the legacy.
Thanks :)

**Comment by varwasabi** [comment]
Given how experimental the new config is, I think this would be a ways away going into anything that is releasable.

**Comment by jjangga0214** [comment]
@varwasabi 

- The spec is fixed. 
- Though eslint's API for handling the new config is experimental.

Those two are irrelevant to each other.
This PR is only related to the former, the spec.
