### ISSUE TITLE
`unicorn/prefer-includes` applies to iterators, while it shouldn't

### ISSUE THREAD

**Issue by mlbiche** [sindresorhus/eslint-plugin-unicorn#1916]
As iterators do not have `includes` method, a [condensed syntax to check whether an iterator includes a vale](https://stackoverflow.com/questions/64093419/javascript-check-whether-iterator-includes-value) uses the `some` method. 

The ESLint plugin raises the `unicorn/prefer-includes` and if auto-fix is enabled, turns the `some` method into an `include` method leading to a JavaScript error.

```js
const myMap = new Map([['foo', 'bar']])
myMap.keys().some(key => key === 'foo')
```

This piece of code could be shortened into `myMap.has('foo')`, but it illustrates the issue.

**Comment by fisker** [comment]
There is no `.some()` either, isn't it?

**Comment by mlbiche** [comment]
@fisker Oops, I have partially read the StackOverflow answer. You're right, sorry for this ! 😅
