### ISSUE TITLE
prefer-native-coercion-functions: detect `!!` for `Boolean`

### ISSUE THREAD

**Issue by silverwind** [sindresorhus/eslint-plugin-unicorn#1918]
[prefer-native-coercion-functions](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prefer-native-coercion-functions.md) detects `Boolean(el)` but not `!!el` which is a convention for boolean conversion:

```js
arr.filter(el => !!el) // prefer arr.filter(Boolean)
```

There are more similar conventions, but their intention may not be as clear as for the boolean case:

```js
arr.filter(el => `${el}`) // prefer arr.filter(String)
arr.filter(el => +el) // prefer arr.filter(Number)
```

Edit: I see these cases are mentioned in the [notes](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prefer-native-coercion-functions.md#note), but I wonder what the reason for their exclusion is.

**Comment by fisker** [comment]
Mentioned in original rule proposal https://github.com/sindresorhus/eslint-plugin-unicorn/issues/1643#issue-1082994404

> Some cases already coverd by builtin rule no-implicit-coercion, so maybe we can assume some type-casting is already in shape of v => Boolean(v)

**Comment by fisker** [comment]
> I wonder what the reason for their exclusion is.

Only reason, LAZY -- I don't want re-implement logic already exist in  `no-implicit-coercion`

**Comment by silverwind** [comment]
I do have `no-implicit-coercion` disabled. I guess it's time to enable it.
