### ISSUE TITLE
Allow descriptive error name in catch-error-name

### ISSUE THREAD

**Issue by pvdlg** [sindresorhus/eslint-plugin-unicorn#192]
Currently the `catch-error-name` forces to name the `catch` argument `error`, `error2`, `error3` etc... Adding a number at the end of a variable is not really descriptive.

I guess it's ok for the rule to accept `error${index}` as a valid name but the rule should allow and recommend to use a descriptive error name such as `fsError`, `httpError` etc...

**Comment by sindresorhus** [comment]
I agree.

**Comment by futpib** [comment]
I would not call errors names like `fsError` as it may be misleading (looks like it implies the type of error, when there is no real guarantee). May still be useful for names like `innerError`.

**Comment by lo1tuma** [comment]
Should this be the default behavior or should we just add another option to provide a regex pattern that the catch binding must match?
Another disadvantage for descriptive error names would be that we don’t get auto-fixing.

I would be willing to implement this feature once we have figured out the details of how it should work.

**Comment by pvdlg** [comment]
I imagine you can still auto-fix the case `e` => `error` which is the most common.

**Comment by sindresorhus** [comment]
How about we change the `name` option to accept a regex instead?

**Comment by lo1tuma** [comment]
@sindresorhus That would be sufficient for my needs. But in this case we would also lose the ability to auto-fix detected problems. Or we provide a second option that specifies which name should be used for auto-fixing ,e.g. `{ pattern: '^error$|^.+Error$', nameForAutoFixing: 'error' }`.

**Comment by sindresorhus** [comment]
@lo1tuma Are we talking about the same thing? As the `pattern` would be **allowed error names**, so there's no auto-fixing needed.

**Comment by sindresorhus** [comment]
I've been thinking about this some more, and I think we should just continue auto-fixing to `error${index}`, but also change the `caughtErrorsIgnorePattern` option default to `^_$|^error|error$`. This way we have a sane default auto-fix, but users can still rename the fixed error names to something more descriptive.

**Comment by lo1tuma** [comment]
Great idea. So basically we already have everything to support this use-case. I’m going to open a PR.
