### ISSUE TITLE
MongoDB `find` method treated as `Array#find` method

### ISSUE THREAD

**Issue by moshest** [sindresorhus/eslint-plugin-unicorn#1947]
Linting rules treat `collection.find` method in MongoDB as if it's `Array.find` function.

### Related rules:
- [no-array-callback-reference](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/v43.0.2/docs/rules/no-array-callback-reference.md)
- [no-array-method-this-argument](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/v43.0.2/docs/rules/no-array-method-this-argument.md)

### Consider the following example:

```ts
const filter = { foo: 1 };

const ids = await collection
  .find(filter, {
    limit: options.limit,
    projection: { _id: 1 },
  })
  .toArray();
```

This code mistreated as `Array#find` function and produce the following errors:

1. Expect inline find function instead of the find `filter` argument:

<img width="828" alt="image" src="https://user-images.githubusercontent.com/534911/200181531-59017c3e-97f9-4603-a0b1-3c59bbca7d77.png">

2. Expect no `this` argument on the second `options` argument:

<img width="828" alt="image" src="https://user-images.githubusercontent.com/534911/200181549-4d93affc-cce4-4de3-96fb-3799631acc77.png">

**Comment by fisker** [comment]
There's no way for the rule to know it's not an array from just static checking. You'll have to disable the rule.

**Comment by fisker** [comment]
Seems doable in your case, but I'm not sure if it worth the effort.
