### ISSUE TITLE
The `safe-regex` link in `no-unsafe-regex.md` is dead

### ISSUE THREAD

**Issue by munierujp** [sindresorhus/eslint-plugin-unicorn#1958]
The `safe-regex` link in `no-unsafe-regex.md` is dead.

https://github.com/sindresorhus/eslint-plugin-unicorn/blob/505a2039627350fe7ae0b990d48cd035d8184949/docs/rules/no-unsafe-regex.md?plain=1#L8

**Comment by fregante** [comment]
PR welcome
