### ISSUE TITLE
Can we set a default `"max-lines": [ "error", 1000 ]`?

### ISSUE THREAD

**Issue by niftylettuce** [sindresorhus/eslint-plugin-unicorn#196]
<https://eslint.org/docs/rules/max-lines>

**Comment by sindresorhus** [comment]
Why is this opened here? I assume you meant to open this on the XO repo. In any case, I don’t  think it’s something I want. Setting a naive limit is not going to make sense in all cases and it’s just going to be annoying. I used to have this rule enabled, but turned it off at some point out of annoyance.
