### ISSUE TITLE
`unicorn/no-useless-spread` erroneously fixes `String#slice`

### ISSUE THREAD

**Issue by iamnapo** [sindresorhus/eslint-plugin-unicorn#1988]
```js
const string = "abcdef";

[...string.slice(1, 3)]; // Error: Unnecessarily cloning an array
```
and auto-fixes it to
```js
string.slice(1, 3);
```

**Comment by fisker** [comment]
Workaround for now

```js
const string = "abcdef";
const fooString = string.slice(1, 3);
[...fooString];
```

**Comment by fisker** [comment]
Since we can't know if it's a string or an array, I'm going to remove the auto-fix. You still need use `eslint-disable` for this case.

**Comment by mondeja** [comment]
The auto fix is still there. Additionally, note that there are cases in which can be known if a variable is a string due to JSDoc comments, for example:

```js
/**
 * @param {String} color My color
 */
const normalizeColor = (color) => {
  color = [...color.slice(0, 3)].map((x) => x.repeat(2)).join('');
  ...
}
```

With `@type` too, probably in others contexts.
