### ISSUE TITLE
[unicorn/prefer-spread] `ArrayLike` can't be spread but be reported

### ISSUE THREAD

**Issue by SettingDust** [sindresorhus/eslint-plugin-unicorn#1990]
```ts
const foo = (bar: ArrayLike<number>) => {
  for (const element of Array.from(bar)) {
    console.log(element)
  }
}

Prefer the spread operator over `Array.from(…)`.(unicorn/prefer-spread)
```
With spread will error `Type 'ArrayLike ' must have a '[Symbol.iterator]()' method that returns an iterator.`

**Comment by fregante** [comment]
Duplicate of https://github.com/sindresorhus/eslint-plugin-unicorn/issues/1876

**Comment by fregante** [comment]
But I suppose the type here could be used to exclude this piece of code

**Comment by SettingDust** [comment]
Not duplicate. This is caused by `ArrayLike` instead of `Array.from`.

**Comment by fregante** [comment]
See https://github.com/sindresorhus/eslint-plugin-unicorn/issues/120#issuecomment-386823609

It was an intentional decision

**Comment by fregante** [comment]
I can reopen it as a bug in case the maintainers decide to detect and ignore the `ArrayLike` type, but I wouldn't hold my breath.

Related:

- https://github.com/sindresorhus/eslint-plugin-unicorn/issues/2018#issuecomment-1407314620

**Comment by fregante** [comment]
Duplicate of https://github.com/sindresorhus/eslint-plugin-unicorn/issues/1064
