### ISSUE TITLE
`prevent-abbreviations` breaks code in Vue templates?

### ISSUE THREAD

**Issue by KnifeFed** [sindresorhus/eslint-plugin-unicorn#2005]
It seems `prevent-abbreviations` can break code in Vue templates.

`prevent-abbreviations`

```vue
<template>
    <button @click="goToPrev"/>
</template>

<script setup>
const goToPrev = () => {
    // do something
}
</script>
```

Auto-fixing renames `goToPrev` to `goToPrevious` but doesn't change the reference in the Vue directive, breaking the execution.

Also, is there a way to only disable auto-fixing for this rule?

**Comment by KnifeFed** [comment]
Alright, I guess I need to just disable this rule.

**Comment by fisker** [comment]
Looks like there is no info for variables in template, so I'm going to remove the auto-fix for this case.
