### ISSUE TITLE
`no-useless-spread` with empty n-elements array

### ISSUE THREAD

**Issue by nickofthyme** [sindresorhus/eslint-plugin-unicorn#2006]
When the `unicorn/no-useless-spread` rule is enabled, it will error on spread operators used to create an array of `n` elements.

A common use case is to create an array of `n` elements then `map` over the element to _fill_ the array with desired values.

```ts
const itemCount = 2;
const myItems = [...new Array(itemCount)].map((_, i) => `Item ${i}`);
```

The above code errors as shown below...

<img width="621" alt="image" src="https://user-images.githubusercontent.com/19007109/205734200-b7122d92-9758-4150-99a7-b560289fd67f.png">

To fix the issue would change the logic as shown below, making this case a _**useful**_ case not _useless_ spread 😉 

```ts
new Array(2).map(() => 't')
// [empty × 2]

[...new Array(2)].map(() => 't')
// ['t', 't']
```

**Comment by yakov116** [comment]
What version are you on? This seems like a duplicate of #1994

**Comment by nickofthyme** [comment]
Yup true, sorry didn't see that issue.
