### ISSUE TITLE
Failed to load plugin 'unicorn' declared in '.eslintrc.js » @nuxtjs/eslint-config'

### ISSUE THREAD

**Issue by MRloll** [sindresorhus/eslint-plugin-unicorn#2019]
I am tryin to create nuxt app. I choosed eslint as my liner ofc, andat the end the installation I get this error.
Please guys help me its been so tiring trying to fix this and cant find any fixation

**Comment by sindresorhus** [comment]
This is about Nuxt usage, so it would be better to ask on the Nuxt issue tracker.
