### ISSUE TITLE
`safe-regex` is gone, needs replacement

### ISSUE THREAD

**Issue by fregante** [sindresorhus/eslint-plugin-unicorn#2025]
User "substack" is off GitHub entirely:

https://github.com/substack/safe-regex

The package itself has been last updated 3 years ago:

https://www.npmjs.com/package/safe-regex

We have a link to it in the docs and we're using the dependency in package.json:

- https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/no-unsafe-regex.md
- https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/package.json

More context:

https://stackoverflow.com/questions/73833369/minimist-github-page-doesnt-exit

Related:

- https://github.com/sindresorhus/eslint-plugin-unicorn/issues/153

**Comment by silverwind** [comment]
The npm package points to this repo, which is still alive:

https://github.com/davisjam/safe-regex

Also, the fastify people have made a fork:

https://github.com/fastify/safe-regex2

**Comment by silverwind** [comment]
Keep this open until the dependency is actually removed?

**Comment by fisker** [comment]
oops forgot that.

**Comment by silverwind** [comment]
No need I guess if it's already on the "train" to removal.

**Comment by fisker** [comment]
#2140

**Comment by gkiely** [comment]
Hey guys if it's possible to switch to safe-regex2 instead of blanket removing this it would be appreciated. I rely on this rule for codebases that have extensive regular expressions.

**Comment by silverwind** [comment]
@gkiely check out [eslint-plugin-regexp](https://github.com/ota-meshi/eslint-plugin-regexp), it has lots of regex-related rules and I recall it also has one that detects "unsafe" regexes.
