### ISSUE TITLE
`unicorn/prefer-dom-node-append` and `unicorn/prefer-dom-node-remove` doesn't work with optional chaining

### ISSUE THREAD

**Issue by B2o5T** [sindresorhus/eslint-plugin-unicorn#2056]
only when I remove optional chaining I get an error

```js
toolbar?.appendChild(executeOpButton);
```

**Comment by fregante** [comment]
Confirmed, seen in [refined-github/refined-github@`f56255e` (#6445)](https://github.com/refined-github/refined-github/pull/6445/commits/f56255ee38271140d21f041da29e0dc60fd013e4#diff-0642eba0bad39e38af379d2a11a31201a27f853f9ec54cb2cfd3a61820c6cf80R11)
