### ISSUE TITLE
prefer-logical-operator-over-ternary is dangerous and shouldn't be recommended

### ISSUE THREAD

**Issue by ndeuma** [sindresorhus/eslint-plugin-unicorn#2059]
"??" is not equivalent to "?:" for NaN, "" and several other values. This lead to a bug in our application. This rule should at least not be recommended .

```js
// NaN
const x = NaN; x ?? "default value" 

// "default value"
const y = NaN; x ? x : "default value" 

// ""
const a = ""; a ?? "default value" 

// "default value"
const b = ""; b ? b : "default value" 
```

**Comment by B2o5T** [comment]
This rule is not dangerous, it has suggestions instead autofix

It is up to you to choose the right operator for your individual case
