### ISSUE TITLE
Enforce file naming to be in camelCase

### ISSUE THREAD

**Issue by jatin-vl** [sindresorhus/eslint-plugin-unicorn#2172]
I used "eslint-plugin-unicorn" for enforcing file naming to be in camelCase in node application.

It works fine and throw error for the following naming convention.

- checklist-forecast.ts
- ChecklistForecast.ts
- checklist-forecast.ts

But it does not throw error for the "multiplewordstucktogetherwithoutcamelcasing". As it consider it as a single word.
- checklistforecast.ts

**Comment by sindresorhus** [comment]
> But it does not throw error for the "multiplewordstucktogetherwithoutcamelcasing". As it consider it as a single word.

It is techincally a single word.

There is simply no way of knowing that it's multiple words. Even if we would support all English words, there are words that can both be combined and not. It's simply not feasible.
