### ISSUE TITLE
consider removing clean-regexp as dependency

### ISSUE THREAD

**Issue by WAKayser** [sindresorhus/eslint-plugin-unicorn#2185]
This is a very small depenency that has not been updated for 6 years. It also requires an old version of escape-string-regexp.

Thanks for the great eslint rules.

**Comment by sindresorhus** [comment]
Does it cause any problems? If no, then I don't see any reason to remove it. Small packages can simply be done. For this to be actionable, there also needs to be a solution for what to use instead.
