### ISSUE TITLE
Error while loading rule 'unicorn/consistent-function-scoping': Cannot destructure property 'scopeManager' of 'sourceCode' as it is undefined.

### ISSUE THREAD

**Issue by strau0106** [sindresorhus/eslint-plugin-unicorn#2207]
I get the following error when using the unicorn/consistent-function-scoping rule in a nextjs project: ` Error while loading rule 'unicorn/consistent-function-scoping': Cannot destructure property 'scopeManager' of 'sourceCode' as it is undefined.
`

'unicorn/consistent-function-scopin'

Not entirely sure what exactly is causing this issue. The issue does not appear to be bound to a specific file.

Running v48.0.1 of unicorn, TS: 5.2.2

Any help appreciated. Happy to try things out and do some work

**Comment by fisker** [comment]
Please use latest ESLint.

**Comment by strau0106** [comment]
yeah sorry, my bad
