### ISSUE TITLE
Docs request: explain why explicit-length-check is useful

### ISSUE THREAD

**Issue by mmkal** [sindresorhus/eslint-plugin-unicorn#2215]
### Description

https://github.com/sindresorhus/eslint-plugin-unicorn/blob/v39.0.0/docs/rules/explicit-length-check.md says what the `explicit-length-check` does, but not why you would want it/ why it's recommended.

So, what's the reason for the rule? I'm filing this as a docs request for future readers, but I am also curious what content would be written in that md file.

I find the rule a tiny bit annoying, so I read the docs in hopes of seeing some justification for it to see whether it applied to my team's codebase. The docs really just explained when it passes and fails - which I knew already from the lint errors I got.

### Fail

n/a

### Pass

n/a

### Additional Info

<sub>should I make a `.github/ISSUE_TEMPLATE/docs_request.md` file so this kind of issue doesn't require so many `n/a` fields and incorrect labels?</sub>

**Comment by mmkal** [comment]
Ok, looking at the history of the doc I found the original issue: 

So the reason is, quote @sindresorhus:

> I generally favor explicitness

That's totally understandable - but honestly I do think that should be put there. I came to the docs thinking "is there an edge case I can't think of, some javascript-null-weirdness issue with `if (foo.length) console.log(foo)`". If I had seen that it's just a stylistic thing for a different person/team, that genuinely helps inform my decision on whether to use it.

So, if no objections, I can open a PR paraphrasing that so people understand that it's totally safe to disable?

Also related: https://github.com/sindresorhus/eslint-plugin-unicorn/issues/1752

**Comment by sindresorhus** [comment]
The main benefit of the rule is to enforce consistency. The secondary benefit is stricter more readable code.

**Comment by mmkal** [comment]
Wait, I'm so confused. @fregante added exactly what I'm looking for in #2070 - how come https://github.com/sindresorhus/eslint-plugin-unicorn/blob/v39.0.0/docs/rules/explicit-length-check.md doesn't have it?

**Comment by mmkal** [comment]
Oh I am stupid. I'm on an old version of the library. Closing this.
