### ISSUE TITLE
Add support for flat config (`eslint.config.js`)

### ISSUE THREAD

**Issue by rakleed** [sindresorhus/eslint-plugin-unicorn#2220]
From the next version 9, [ESLint will deprecate](https://eslint.org/blog/2023/10/flat-config-rollout-plans/) the current eslintrc format, and by default will use the [new flat config format](https://eslint.org/docs/latest/use/configure/configuration-files-new) (eslint.config.js). Already from [version 8.21.0](https://github.com/eslint/eslint/releases/tag/v8.21.0) you can use the flat config format. But your [README](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/readme.md) doesn't say anything about how to configure in flat config, so I'm guessing you don't support it.

Guide to migrating a plugin to a flat config: https://eslint.org/docs/latest/extend/plugin-migration-flat-config

**Comment by hanc2006** [comment]
It would be nice to have a reference example.
