### ISSUE TITLE
no-array-for-each autofix is unsafe for sparse arrays

### ISSUE THREAD

**Issue by Pyrolistical** [sindresorhus/eslint-plugin-unicorn#2227]
```js
// BEFORE
const x = [];
x[1] = true;
x.forEach((item, i) => console.log(item, i));
// only prints: true 1

// AFTER
const x = [];
x[1] = true;
for (const [i, item] of x.entries()) {
  console.log(item, i);
}
// prints: undefined 0\ntrue 1
```

**Comment by sindresorhus** [comment]
Sparse arrays are an anti-pattern, so we're not going to change the auto-fix, but we should document the issue with sparse arrays.

**Comment by Pyrolistical** [comment]
I agree, but they are used in the wild. Example in [`qs` where `source` is a sparse array](https://github.com/ljharb/qs/blob/edc19a206587d20c78c596e1553657fe207035a6/lib/utils.js#L77)
