### ISSUE TITLE
In v50.0.0 , lodash dependency is missing

### ISSUE THREAD

**Issue by webextensions** [sindresorhus/eslint-plugin-unicorn#2240]
`const {camelCase} = require('lodash');` is used in https://github.com/sindresorhus/eslint-plugin-unicorn/blob/v50.0.0/rules/no-unnecessary-polyfills.js

But, `"lodash"` isn't available in https://github.com/sindresorhus/eslint-plugin-unicorn/blob/v50.0.0/package.json

So, when we consume this package (in another ESLint config), it is causing an issue when we try to load the latest version:
`Failed to load plugin 'eslint-plugin-unicorn' declared in '.eslintrc.js ...`

**Comment by fisker** [comment]
Would you like to fix it? Should import from `./utils/lodash.js`.

https://github.com/sindresorhus/eslint-plugin-unicorn/blob/7f66a2408651ab6c67d514924ea3ec3bd9420349/rules/filename-case.js#L3

**Comment by fisker** [comment]
Should fixed in [v50.0.1](https://github.com/sindresorhus/eslint-plugin-unicorn/releases/tag/v50.0.1)
