### ISSUE TITLE
Export types for use in flat configs

### ISSUE THREAD

**Issue by Logicer16** [sindresorhus/eslint-plugin-unicorn#2246]
The flat eslint config format imports plugins as modules. This now allows typing to be enforced in these config files.

To help users avoid having issues like ts(7016), type definitions should be included in this plugin or distributed through DefinitelyTyped. Examples can be found in [@eslint/js](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/eslint__js/index.d.ts), eslint-plugin-prettier ([1](https://github.com/prettier/eslint-plugin-prettier/blob/master/eslint-plugin-prettier.d.ts)) ([2](https://github.com/prettier/eslint-plugin-prettier/blob/master/recommended.d.ts)), and [eslint-plugin-n](https://github.com/eslint-community/eslint-plugin-n/issues/142).

**Comment by yukulele** [comment]
fixed by #2382
