### ISSUE TITLE
Add option to ignore some files in `filename-case` rule

### ISSUE THREAD

**Issue by iwata** [sindresorhus/eslint-plugin-unicorn#229]
I'm using [node-config-ts](https://www.npmjs.com/package/node-config-ts).
It creates `Config.d.ts` file automatically.
I wanna use `kebabCase` and ignore this file.

**Comment by sindresorhus** [comment]
In both XO and ESLint, you can create rule override for certain files.

- https://github.com/xojs/xo#config-overrides
- https://eslint.org/docs/user-guide/configuring#disabling-rules-only-for-a-group-of-files

**Comment by iwata** [comment]
It makes sense, thanks.
