### ISSUE TITLE
Missing rules in plugin

### ISSUE THREAD

**Issue by RebeccaStevens** [sindresorhus/eslint-plugin-unicorn#2302]
Some rules are missing from the exported rules.
I discovered this while trying to covert my config to work with the eslint 9 rc.

The rules `no-anonymous-default-export`, `no-await-in-promise-methods` and `no-single-promise-in-promise-methods` are not in the plugin's rules.

```js
import pluginUnicorn from "eslint-plugin-unicorn";

const allRules = Object.keys(pluginUnicorn.rules);
console.log(allRules.includes("no-anonymous-default-export")); // false
console.log(allRules.includes("no-await-in-promise-methods")); // false
console.log(allRules.includes("no-single-promise-in-promise-methods")); // false
```

**Comment by sindresorhus** [comment]
Like most repos on GitHub, the `main` branch tracks the latest development, not the latest release. These rules were not yet released, but they are now: https://github.com/sindresorhus/eslint-plugin-unicorn/releases/tag/v52.0.0
