### ISSUE TITLE
prefer-node-protocol for ambiguous dependencies

### ISSUE THREAD

**Issue by georg-schwarz** [sindresorhus/eslint-plugin-unicorn#2326]
I'd expect the `prefer-node-protocol` to allow defining some exceptions where the rule should not apply, or the rule should not apply in the first place if there is a similarly named dependency.

Maybe there is already a solution that I'm not aware of. Then please treat this issue as documentation if someone struggles with it as well ;-)

### Example

We stumbled upon this behavior as we were trying to use a package called [assert](https://www.npmjs.com/package/assert). Unfortunately, it is ambiguous whether a programmer wants to import from `node:assert` or `assert`.

```js
import { strict as assert } from 'assert'; // the library
import { strict as assert } from 'node:assert'; // from node
```

In the meantime, we will go with `// eslint-disable-next-line unicorn/prefer-node-protocol` whenever we import the library. But, obviously, a general solution would be much nicer.

**Comment by sindresorhus** [comment]
The best solution in this case is to use an "eslint-disable" comment. I don't see the need to add an option to this rule for such an edge-case.

**Comment by sindresorhus** [comment]
And it's generally an anti-pattern to use packages named the same a built-in packages as it makes it unclear to people reading the code that it's not actually a built-in module being used.

**Comment by silverwind** [comment]
> And it's generally an anti-pattern to use packages named the same a built-in packages as it makes it unclear to people reading the code that it's not actually a built-in module being used.

Agree, I would go as far as blacklist affected packages in another rule that supports it. `punycode` is another offending name that exists as both npm and core module.

**Comment by georg-schwarz** [comment]
Thanks for the quick answers! I get your point and followed your advice by disallowing one of the ambiguous libraries and giving a hint on what to do. In our specific case, we will rely on the library instead of the core module.

```json
   // ...
    "no-restricted-imports": [
          "error",
          {
            "paths": [
              {
                "name": "node:assert",
                "message": "Please use the library `assert` instead to keep browser compatibility. You might need to disable the rule `unicorn/prefer-node-protocol` for the importing code line to do so."
              }
            ]
          }
        ]
   // ...
```

**Comment by fisker** [comment]
`punycode` suggest use `const punycode = require('punycode/');` https://www.npmjs.com/package/punycode

Maybe `import { strict as assert } from 'assert/';` works too?

**Comment by georg-schwarz** [comment]
> Maybe `import { strict as assert } from 'assert/';` works too?

Amazing, it works! :+1: Thank you so much! :smile: 
I'll open an issue in the repo of the `assert` library to document this.

**Comment by fisker** [comment]
`import { strict as assert } from 'assert/build/assert.js';`?

**Comment by georg-schwarz** [comment]
> `import { strict as assert } from 'assert/build/assert.js';`?

Yeah, that should work, thanks! 
But I'd rather prefer disabling the linter rule than using these file imports. Remembering or documenting that we have to import it everywhere like this seems to be more bothersome to me :wink:

**Comment by silverwind** [comment]
I would ask the authors of `assert` to publish to a unambiguous package name. `punycode` is also available as unambigous `punycode.js` module.

**Comment by sarimarton-ofsz** [comment]
I disagree with the sentiment that generic names in the npmjs namespace is an antipattern. Two separate namespaces naturally collide.
