### ISSUE TITLE
`rule-name`: `prefer-reflect-apply` is not type safe

### ISSUE THREAD

**Issue by zanminkian** [sindresorhus/eslint-plugin-unicorn#2365]
### Description

```ts
function foo(name: string) {
  console.log(name)
}

foo.apply(null, [42]); // typescript will report type error
Function.prototype.apply.call(foo, null, [42]);
Reflect.apply(foo, null, [42]);
```
As code above, using `foo.apply` is type safe, but `Reflect.apply` isn't.

So, should we deprecate the rule `prefer-reflect-apply`?

### Fail

No

### Pass

No

**Comment by sindresorhus** [comment]
This is a problem with TypeScript. You need to open an issue on TypeScript instead. We would not deprecate the rule just because of a TypeScript bug.
