### ISSUE TITLE
Rule proposal: `prefer-math-min-max`

### ISSUE THREAD

**Issue by seanblonien** [sindresorhus/eslint-plugin-unicorn#2373]
Could there be a rule for fixing the use of ternaries instead of using `Math.min` and `Math.max` where appropriate?

Example of **_incorrect_** usage
```ts
const height = 30;
const value = height > 50 ? 50 : height;
```

Example of **_correct_** usage, using the Math API
```ts
const height = 30;
const value = Math.min(height, 50);
```

same example for `Math.max` with flipped operator sign

**Comment by fregante** [comment]
I think this would be a new rule since it has little to do with modern APIs

**Comment by sindresorhus** [comment]
Maybe: `prefer-math-min-max`
