### ISSUE TITLE
Problem with autofix for `no-single-promise-in-promise-methods`

### ISSUE THREAD

**Issue by ItamarKieslerFabric** [sindresorhus/eslint-plugin-unicorn#2385]
Hi,
Thank you for creating and maintaining this plugin.

When autofixing `no-single-promise-in-promise-methods` code might break:

Original code:
```ts
const results = await Promise.all([somePromise]);
doSomething(results[0]);
```

Autofixed code:
```ts
const results = await somePromise;
doSomething(results[0]); // Problem, results is no longer an array
```

I don't know if it's possible to automatically identify the usages of the resolved array and fix them, if not maybe not autofix?

Thanks

**Comment by fisker** [comment]
//cc @Clement398
