### ISSUE TITLE
Enforce "must use new" check inside constructor functions.

### ISSUE THREAD

**Issue by jamestalmage** [sindresorhus/eslint-plugin-unicorn#24]
ES2015 Classes throw an error if you don't use `new` to instantiate them.

We have begun performing the same check manually in non-es2015 constructors, using a simple `if(!(this instance of ...))` check. It would be good to enforce that check if the function name was capitalized.
## 

New to making ESLint rules? Check out this quick guide on [how to get started](https://gist.github.com/sindresorhus/1656c46f23545deff8cc713649dcff26).

**Comment by brandonweis** [comment]
@sindresorhus at your service!

**Comment by sindresorhus** [comment]
@brandonweis Awesome! Read [this](https://gist.github.com/sindresorhus/1656c46f23545deff8cc713649dcff26) on how to get started. Let me know if you have any questions :)

**Comment by sindresorhus** [comment]
I'm no all ES2015, so this rule is pretty moot for me. Even AVA is using native classes now.
