### ISSUE TITLE
d.ts file missing from published package

### ISSUE THREAD

**Issue by meszaros-lajos-gyorgy** [sindresorhus/eslint-plugin-unicorn#2407]
The `index.d.ts` file is not present in the published package when installing it via `npm install eslint-plugin-unicorn`.
![image](https://github.com/user-attachments/assets/afb48ed5-cd16-4dda-a67d-7e48f30680da)

As a result the code markes the import with `any`...
![image](https://github.com/user-attachments/assets/333a6f6c-2ae0-4154-b160-6a84dcf74ca9)
... and the [@typescript-eslint/no-unsafe-assignment](https://typescript-eslint.io/rules/no-unsafe-assignment) rule immediately starts yelling at me.
![image](https://github.com/user-attachments/assets/c0aa6e44-560f-46c3-8424-ce8293baddea)

**Comment by meszaros-lajos-gyorgy** [comment]
This seems like a duplicate of https://github.com/sindresorhus/eslint-plugin-unicorn/issues/2324, though I don't know why that ticket is closed, I don't see the fix released.

**Comment by sindresorhus** [comment]
It was not released yet, but I released it just now: https://github.com/sindresorhus/eslint-plugin-unicorn/releases/tag/v55.0.0

**Comment by meszaros-lajos-gyorgy** [comment]
Thank you!
