### ISSUE TITLE
Remove `better-regex` rule from recommended list

### ISSUE THREAD

**Issue by fregante** [sindresorhus/eslint-plugin-unicorn#2409]
The rule uses a package "Published 7 years ago" https://www.npmjs.com/package/clean-regexp and it's the source of [a lot of issues](https://github.com/sindresorhus/eslint-plugin-unicorn/issues?q=+%22better-regex%22+is%3Aissue). Currently open:

- https://github.com/sindresorhus/eslint-plugin-unicorn/issues/2314
- https://github.com/sindresorhus/eslint-plugin-unicorn/issues/1754
- https://github.com/sindresorhus/eslint-plugin-unicorn/issues/1626
- https://github.com/sindresorhus/eslint-plugin-unicorn/issues/895

Then check out [`regexp-tree` issues](https://github.com/DmitrySoshnikov/regexp-tree/issues?q=sort%3Aupdated-desc+is%3Aissue+is%3Aopen)

I disable it rather often, I suggest removing it from the `recommended` list or dropping/extracting the rule altogether.

**Comment by voxpelli** [comment]
Is the plan to keep `better-regex` around as a rule as is, to maintain it or to deprecate and remove it?

#9623 mentions [`eslint-plugin-regex`](https://github.com/gmullerb/eslint-plugin-regex) as a better alternative, but its unclear to me what a replacement for `better-regex` would look like with that module.

**Comment by voxpelli** [comment]
Found https://github.com/typescript-eslint/typescript-eslint/pull/9948 which seems to suggest that https://github.com/gmullerb/eslint-plugin-regex is not the correct module, its the https://github.com/ota-meshi/eslint-plugin-regexp that's a better replacement?
