### ISSUE TITLE
`explicit-length-check`: Possible deprecation or new rule with reversed behaviour

### ISSUE THREAD

**Issue by ferferga** [sindresorhus/eslint-plugin-unicorn#2455]
### Description

I did some benchmarks in different algorithms for checking if a collection has contents: https://jsperf.app/kopiro

Although we're probably taking the side of microoptimization here, as you can see, not doing the comparison with 0 gives +1M (Chromium) or +500K ops (Firefox), so I think it makes sense to at least provide the reversed rule for people desiring to enforce that (and shouldn't require much more logic?).

### Fail

```js
if (short.length > 0) {
	
}
```

### Pass

```js
if (short.length) {
	
}
```

**Comment by sindresorhus** [comment]
This is just a micro optimization and could easily change in a new JS.

https://sindresorhus.com/blog/micro-benchmark-fallacy

**Comment by sindresorhus** [comment]
I'm going to pass on this.
