### ISSUE TITLE
`prefer-dom-node-remove` is confusing as it only applies to Elements, not Nodes

### ISSUE THREAD

**Issue by viveleroi** [sindresorhus/eslint-plugin-unicorn#2456]
The rule `prefer-dom-node-remove` is poorly named and possibly confusing to users. Node#remove is not a valid function. The documentation page links to Element#remove. While Element extends Node, not every DOM node is an Element.

So in situations where I have a Text node, I have to setup an ignore for this rule because I can't use node.remove. I realize there's nothing you can do to prevent false-positives like this, but maybe the rule or the documentation should specifically explain the differences. I'm sure most users are working with Elements, so the false-positive doesn't affect many people.

Also, the docs could probably explain why Element#remove is preferred. I assume it's because it's simpler to write.

This also applies to `unicorn/prefer-dom-node-append`

**Comment by fregante** [comment]
Text nodes do have the `.remove()` method, try running `new Text().remove()` in the console and you'll see it pass.

Specifically `.remove()` is defined as a mixin `ChildNode#remove()`, which applies to Node as well as Element:

https://dom.spec.whatwg.org/#childnode
