### ISSUE TITLE
`no-useless-undefined` conflicts with `useRef` hook in React 19

### ISSUE THREAD

**Issue by rakleed** [sindresorhus/eslint-plugin-unicorn#2460]
Starting with React 19, [`useRef` will require an argument ](https://react.dev/blog/2024/04/25/react-19-upgrade-guide#useref-requires-argument)on initialization. But the `no-useless-undefined` rule requires not to specify `undefined`. It might be worth adding it as an exception to https://github.com/sindresorhus/eslint-plugin-unicorn/blob/1558cbea81bf4476ee27d80724155d991433ce49/rules/no-useless-undefined.js#L32-L68 ​​as in https://github.com/sindresorhus/eslint-plugin-unicorn/pull/2223.

**Comment by fregante** [comment]
This would be a quick fix. See the last PR to ignore some React functions:

- https://github.com/sindresorhus/eslint-plugin-unicorn/pull/2223
