### ISSUE TITLE
`prevent-abbreviation` rule currently not working with `@typescript-eslint/parser`

### ISSUE THREAD

**Issue by SpainTrain** [sindresorhus/eslint-plugin-unicorn#265]
This is more for awareness/tracking since I believe it is a bug in `@typescript-eslint/parser@1.5.0` (see https://github.com/typescript-eslint/typescript-eslint/issues/381) and not in this plugin itself.

When run against a ts file with an `enum`, this function https://github.com/sindresorhus/eslint-plugin-unicorn/blob/79a8cd69669b94baec9f4864f08f6be0cac43805/rules/prevent-abbreviations.js#L436 throws an `undefined` Error because the enum identifier node does not have `.parent`.

**Comment by dashmug** [comment]
I've just run into this as well.

**Comment by sindresorhus** [comment]
This will be fixed there very soon: https://github.com/typescript-eslint/typescript-eslint/pull/383
