### ISSUE TITLE
'use strict' is unnecessary inside of modules

### ISSUE THREAD

**Issue by aladdin-add** [sindresorhus/eslint-plugin-unicorn#274]
I was trying to use the plugin in a Node.js lib (not using esm), but got something like:

`6:1  error  'use strict' is unnecessary inside of modules `

**Comment by futpib** [comment]
Can you post the code so that we can reproduce this?

**Comment by aladdin-add** [comment]
oops, I would have posted the code! it was:
```js
'use strict';

// xxx
```

**Comment by aladdin-add** [comment]
seems it was caused by:
https://github.com/sindresorhus/eslint-plugin-unicorn/blob/0765c1f862265024b4d69df0f8160538eb114339/index.js#L14
