### ISSUE TITLE
Object.assign convert in spread with wrong order

### ISSUE THREAD

**Issue by copycut** [sindresorhus/eslint-plugin-unicorn#275]
* ESLint Version: 5.16
* Node Version: 10.15.3
* npm Version: 6.9.0
* Babel-eslint: 10.0.1

When --fix is used on project, the result of converting Object.assign don't return the expected value.

## Previously

```js
const user = {name: 'user', id: 0};
return Object.assign({name: 'test'}, user); // {name: 'test', id:0}
```

## After convertion (--fix applied)

```js
const user = {name: 'user', id: 0};
return {name: 'test', ...user}; // {name: 'user', id: 0}
```

## Expected result

```js
const user = {name: 'user', id: 0};
return {...user, name: 'test'}; // {name: 'test', id: 0}
```

**Comment by futpib** [comment]
Which rule reports `Object.assing` for you? I don't think we have a rule that does that.

**Comment by copycut** [comment]
My bad it's in Eslint rules ^__^'
https://github.com/eslint/eslint/blob/master/lib/rules/prefer-object-spread.js
