### ISSUE TITLE
Use lodash instead of method of lodash

### ISSUE THREAD

**Issue by Hongarc** [sindresorhus/eslint-plugin-unicorn#283]
I see you use `lodash.camelcase` to `lodash.upperfirst`.

My recommendation is just use `lodash` in `package.json` and call: `require('lodash/camelcase')` to call `camelcase` and others method.

It will keep that method doesn't out update (just need update `lodash`).

**Comment by sindresorhus** [comment]
We can do it after the next major Lodash version, but right now the Lodash package is too large. https://packagephobia.now.sh/result?p=lodash
