### ISSUE TITLE
Respect `browserslist` settings?

### ISSUE THREAD

**Issue by amankkg** [sindresorhus/eslint-plugin-unicorn#285]
Hi!
How to handle situations if some feature is not supported (e.g. `Array|String's include` method in case of `prefer-includes` rule)?
What would you suggest?
Who's responsibility should it be? This plugin or users?
Probably, it worths mentioning in README.
Thanks!

**Comment by sindresorhus** [comment]
I'm not interested in baking in support for `browserlist` here. However, you can easily add it in your own [shareable ESLint config](https://eslint.org/docs/developer-guide/shareable-configs). It's just a JS file after all.
