### ISSUE TITLE
Require "secure" cookies

### ISSUE THREAD

**Issue by kkmuffme** [sindresorhus/eslint-plugin-unicorn#299]
**Please describe what the rule should do:**

When setting cookies with js, we should require the "secure" parameter. In 2019, with free SSL with letsencrypt, there really is no reason anymore to not be on SSL/https and eslint should require the secure parameter to improve security.

This is (I believe) also easily auto-fixable by eslint.

**What category of rule is this? (place an "X" next to just one item)**

[ ] Warns about a potential error (problem)
[ ] Suggests an alternate way of doing something (suggestion)
[ ] Enforces code style (layout)
[x] Other (please specify:) **Improves security**

**Provide 2-3 code examples that this rule will warn about:**

```js
document.cookie = "username=John Doe";
document.cookie = "username=John Doe; expires=Thu, 18 Dec 2013 12:00:00 UTC";
document.cookie = "username=John Doe; expires=Thu, 18 Dec 2013 12:00:00 UTC; path=/";

Should be:
document.cookie = "username=John Doe; secure";
document.cookie = "username=John Doe; expires=Thu, 18 Dec 2013 12:00:00 UTC; secure";
document.cookie = "username=John Doe; expires=Thu, 18 Dec 2013 12:00:00 UTC; path=/; secure";
```

**Are you willing to submit a pull request to implement this rule?**
I have no idea how, but I am happy to test, write documentation or whatever else is needed.

**Comment by futpib** [comment]
I'd rather ban `document.cookie` and recommend [cookie](https://www.npmjs.com/package/cookie) or something like that instead. Formatting or parsing this string on your own is error prone (easy to forget escaping).

**Comment by sindresorhus** [comment]
@futpib That's a very good point.

Also relevant: https://github.com/WICG/cookie-store

**Comment by kkmuffme** [comment]
@futpib we would just add "secure" to it, not sure how you would get an injection like that?

Anyway, my use case is to use it on a wide variety of browser js, not necessarily in node.js

**Comment by sindresorhus** [comment]
> @futpib we would just add "secure" to it, not sure how you would get an injection like that?

His point is that `document.cookie` is inherently insecure itself. It's not adding `secure` that risks the injection, but rather anything else you would do with `document.cookie`.

> Anyway, my use case is to use it on a wide variety of browser js, not necessarily in node.js

There's nothing Node.js-specific about the `cookie` package. It works in the browser too. There are also many other cookie packages on npm.

**Comment by kkmuffme** [comment]
Except that it requires npm/node :-) I am mostly developing/fixing WordPress (legacy) code, so in most cases cannot use cookie npm or change the use of document.cookie, as my code runs on 1000s of sites with completely different configurations and often is years old :-( 

I know "secure" won't improve it much, but better than nothing.

**Comment by sindresorhus** [comment]
> Except that it requires npm/node :-)

You can still bundle them manually. It's just JavaScript. Nothing Node.js specific.

> I know "secure" won't improve it much, but better than nothing.

I don't disagree with that, but for making rules, we prefer to go with the absolute best solution.

**Comment by sindresorhus** [comment]
Closing in favor of https://github.com/sindresorhus/eslint-plugin-unicorn/issues/402.
