### ISSUE TITLE
Multiple allowed error names in catch-error-name

### ISSUE THREAD

**Issue by kkmuffme** [sindresorhus/eslint-plugin-unicorn#300]
Is it possible (how?) to allow multiple names for errors?

e.g. I would like to allow "error" and "err"?

https://github.com/sindresorhus/eslint-plugin-unicorn/blob/master/docs/rules/catch-error-name.md

**Comment by sindresorhus** [comment]
No, and it's not something I want to support. I don't want to encourage inconsistent code like that. I would recommend just disabling this rule.
