### ISSUE TITLE
filename-case cannot set multiple cases

### ISSUE THREAD

**Issue by unlight** [sindresorhus/eslint-plugin-unicorn#301]
Documentation 
[sindresorhus/eslint-plugin-unicorn/blob/master/docs/rules/filename-case.md
](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/master/docs/rules/filename-case.md)
```
"unicorn/filename-case": [
	"error",
	{
		"cases": {
			"camelCase": true,
			"pascalCase": true
		}
	}
]
```
Does not work.
```
eslint-plugin-unicorn@8.0.2
```

**Comment by sindresorhus** [comment]
It's not released yet. Look here for the readme of the current version; https://github.com/sindresorhus/eslint-plugin-unicorn/tree/v8.0.2
