### ISSUE TITLE
Bug: prefer-exponentiation-operator disregards order of operations

### ISSUE THREAD

**Issue by thomaLV** [sindresorhus/eslint-plugin-unicorn#304]
Currently Math.pow(x, y - z) is converted to x ** y - z which is obviously not equal.

**Comment by MrHen** [comment]
Eep. I _might_ be able to fix that tonight. If not, I can try to get to it this weekend.

**Comment by thomaLV** [comment]
After running `npm update` and `npm -g update`, I'm seeing no change in behavior. Has the fix been made public? Running eslint-plugin-unicorn version is 9.1.0

**Comment by MrHen** [comment]
Fix should have come with https://github.com/sindresorhus/eslint-plugin-unicorn/releases/tag/v9.0.0

Is the scenario the same that you posted before? `Math.pow(x, y - z)` is being converted to `x ** y - z`? A [similar scenario](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/master/test/prefer-exponentiation-operator.js#L53) was added to the tests but maybe there is something special about the variables.

I can try to take another look tonight.

**Comment by thomaLV** [comment]
Fixing ` Math.pow(1000 + 2, 1 - 3)` results in `1000 + 2 ** 1 - 3` for me. Could there be a problem with my setup?

**Comment by MrHen** [comment]
@thomaLV Can you do an `npm ls eslint-plugin-unicorn` and post the results? You should see something similar to:

```
npm ls eslint-plugin-unicorn
my-project@0.1.0 /Users/adam.babcock/Source/my-project
└── eslint-plugin-unicorn@9.0.0 
```

**Comment by thomaLV** [comment]
Did as you asked and unicorn showed up empty. I moved my node_modules folder and some other stuff, and now everything works as expected. Thank you!
