### ISSUE TITLE
no-process-exit in worker_threads

### ISSUE THREAD

**Issue by lagden** [sindresorhus/eslint-plugin-unicorn#328]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%2430%20Funded-%2300A156.svg" />](https://issuehunt.io/r/sindresorhus/eslint-plugin-unicorn/issues/328)

Is there a solution for these cases?

![image](https://user-images.githubusercontent.com/130963/59971265-f90edf80-954e-11e9-8df6-7eab832ab4c7.png)

```js
'use strict'

const {workerData, parentPort} = require('worker_threads')
const debug = require('./debug')
const sleep = require('./sleep')

const {data, seq} = workerData
sleep(3)
  .then(() => {
    // some data processing...
    const res = `modified ${data}`
    parentPort.postMessage(`Data processed - ${seq}: ${res}`)
  })
  .catch(error => {
    debug.error(error)
    process.exit(1)
  })
```

My worker is waiting for an exit event.

```js
'use strict'

const {Worker} = require('worker_threads')

function runService(service, workerData) {
  return new Promise((resolve, reject) => {
    const worker = new Worker(service, {workerData})
    worker.on('message', resolve)
    worker.on('error', reject)
    worker.on('exit', code => {
      if (code !== 0) {
        reject(new Error(`Worker stopped with exit code ${code}`))
      }
    })
  })
}

module.exports = runService
```

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $30.00)

- [<img src='https://avatars3.githubusercontent.com/u/44827199?v=4' alt='issuehunt' width=24 height=24> issuehunt](https://issuehunt.io/u/issuehunt) ($30.00)
### Submitted pull Requests
- [#388 Closes #328: Enable process.exit on thread files](https://issuehunt.io/r/sindresorhus/eslint-plugin-unicorn/pull/388)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/sindresorhus/eslint-plugin-unicorn/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

**Comment by sindresorhus** [comment]
> It also allows process.exit() to be called in process.on('<event>', func) event handlers. - https://github.com/sindresorhus/eslint-plugin-unicorn/blob/master/docs/rules/no-process-exit.md

I guess we just need to support the `worker` name there in addition to `process`.

**Comment by lubien** [comment]
Can I work on this on this weekend?

**Comment by sindresorhus** [comment]
Yup :)

**Comment by lubien** [comment]
> I guess we just need to support the `worker` name there in addition to `process`.

I'm affraid this is not the solution for this case. The `process.exit` happens in the fork, not in the master's `worker.on`.

**Comment by sindresorhus** [comment]
Either we just disable the rule if `worker_threads` is imported, or maybe more specific also check for `parentPort` or `workerData`?

**Comment by lubien** [comment]
> Either we just disable the rule if `worker_threads` is imported

This is something I feel that is the best tho I confess I haven't done work with threads in node so I don't know if it would be the best solution but I can implement it if you're okay with it.

**Comment by sindresorhus** [comment]
@lubien Let's go with my solution for now.

**Comment by lagden** [comment]
👏 👏 👏
