### ISSUE TITLE
`prevent-abbreviations` should not try to fix variable names when they're being destructured

### ISSUE THREAD

**Issue by mattfwood** [sindresorhus/eslint-plugin-unicorn#330]
First off, I think this is a great library with a lot of excellent rules and really appreciate all the work on it.

I was working on implementing some of the rules for my team and I ran an autofix and saw this change in my git diff:

![image](https://user-images.githubusercontent.com/22530815/60280641-f272c600-98c8-11e9-90ef-0c344f5f41bc.png)

In this case, it would definitely introduce a bug since there 's no 'development' variable being passed.

While I think this autofix is generally pretty safe, i think it might be good to check if the current scope includes destructuring and avoid autofixing.

I can look into working on a PR for this myself (i've been interested in learning how to work on eslint rules), just wanted to point this out and see if i can help out.

**Comment by MrHen** [comment]
The fix should probably be:

```
webpack: (config, { dev: development, buildId }) => {
```

**Comment by futpib** [comment]
Strange, we have a test case which is expected to cover a case like this:
https://github.com/sindresorhus/eslint-plugin-unicorn/blob/c2b8e76fb20f6ec087d3338225a626836d5e3810/test/prevent-abbreviations.js#L577-L578

**Comment by mattfwood** [comment]
@futpib I can take a look at that test case and see why my situation might be some weird exception.

@sindresorhus i'll go ahead and start looking into this, if you'd be able to assign this to me that would be great. thank you!
