### ISSUE TITLE
Is there a difference between `no-buffer-constructor` and `unicorn/no-new-buffer`?

### ISSUE THREAD

**Issue by MrHen** [sindresorhus/eslint-plugin-unicorn#338]
Looks like these two rules share the same purpose:

* [no-buffer-constructor](https://eslint.org/docs/rules/no-buffer-constructor)
* [unicorn/no-new-buffer](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/master/docs/rules/no-new-buffer.md)

Is there any significant difference between them?

**Comment by sindresorhus** [comment]
`unicorn/no-new-buffer` existed first and ESLint later on added their own rule for it. I don't think it's worth deprecating ours yet as we enforce have it in the recommended config, so it reaches more people. We can rather just deprecate it when `new Buffer()` is removed from Node.js, as it's moot then.
