### ISSUE TITLE
context.options not getting the values

### ISSUE THREAD

**Issue by gurrrung** [sindresorhus/eslint-plugin-unicorn#339]
While developing the rule, in `index.js` when I do

```
'unicorn/myrule': ['error', {name: 'hello'}]
```

and in `rules/myrule.js` I just did a simple `console.log(context.options[0])` and it is coming `undefined` all the time when I wrote a simple test and ran it using
`npx ava test/myrule.js`.

Am I doing something wrong to pass options?

PS: `console.log('hello')` works fine.

**Comment by futpib** [comment]
Try this:

```diff
-'unicorn/myrule': 'error', [ {name: 'hello'}]
+'unicorn/myrule': ['error', {name: 'hello'}]
```

**Comment by gurrrung** [comment]
@futpib my fault, it was already that way. :( doesn't work.

**Comment by gurrrung** [comment]
I will edit it my version.

**Comment by futpib** [comment]
`index.js` is a definition of a [ESLint plugin](https://eslint.org/docs/developer-guide/working-with-plugins). When you run tests, your rule does not get passed the options from `index.js`. Instead it is passed options from the test definition (or none, if none specified in the test definition).

Here is an example of a test with custom options:
https://github.com/sindresorhus/eslint-plugin-unicorn/blob/4c3d61c04318f75480bb6ab30bf948fa1643d550/test/catch-error-name.js#L304-L318

**Comment by gurrrung** [comment]
That's exactly what I was missing, thanks.:)
