### ISSUE TITLE
[filename-case] Feature request for case style configuration per file mask

### ISSUE THREAD

**Issue by ulrichb** [sindresorhus/eslint-plugin-unicorn#341]
I'm using your `filename-case` rule as replacement for [TSLint's `file-name-casing`](https://palantir.github.io/tslint/rules/file-name-casing/).

What I'm missing is this file pattern/mask-specific option. Examples:

![image](https://user-images.githubusercontent.com/388796/61984103-41646600-b003-11e9-855b-4ab1c384ba66.png)

Any chance to get this supported here too?

**Comment by futpib** [comment]
You can try [XO's overrides configuration](https://github.com/xojs/xo#config-overrides). In my opinion, this feature is best implemented in the linter itself rather then in each rule separately.
