### ISSUE TITLE
Description of `prefer-query-selector` is misleading WRT “consistency”

### ISSUE THREAD

**Issue by Alhadis** [sindresorhus/eslint-plugin-unicorn#342]
The description of the [`prefer-query-selector`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/fb5a50ce95f85d958db83bdad3a642ed2cbb732b/docs/rules/prefer-query-selector.md) rule states:

> **Prefer `.querySelectorAll()` over `.getElementsByClassName()` and `.getElementsByTagName()`**
> It's better to be consistent.

"Consistency" has nothing to do here. These methods aren't synonymous with each other: `.getElementsByTagName()` and `.getElementsByClassName()` return an [`HTMLCollection`](https://mdn.io/HTMLCollection) object, which updates dynamically as elements are added or removed from the DOM:

~~~js
const pages = document.getElementsByClassName("page");
console.log(pages.length); // 1

const newPage = Object.assign(document.createElement("div"), {className: "page"});
document.body.appendChild(newPage);
console.log(pages.length) // 2
~~~

Conversely, [`.querySelectorAll()`](https://mdn.io/querySelectorAll) returns a static [`NodeList`](https://mdn.io/NodeList) which does **not** reflect changes to the DOM:

~~~js
const live = document.getElementsByTagName("div");
const dead = document.querySelectorAll("div");
live.length === 3;
dead.length === 3;

document.body.appendChild(document.createElement("div"));
live.length === 4;
dead.length === 3;
~~~

The rule — or at least its description — should be amended to acknowledge this.

**Comment by sindresorhus** [comment]
> "Consistency" has nothing to do here.

"Consistency" as in always using the same method that behaves the same.

> These methods aren't synonymous with each other: 

I'm well aware of how they work.

---

But sure, we can make the difference clearer.

**Comment by HERBOD7** [comment]
@sindresorhus I can do it.

**Comment by neonanal** [comment]
This rule basically breaks code that relies on a "live" [HTMLCollection](https://mdn.io/HTMLCollection) returned by .getElementsByTagName() and .getElementsByClassName(). I was under impression that linters are NOT supposed to change code functionality, and `prefer-query-selector` goes against this idea, maybe I have wrong expectations for linters, dunno. 
 I can disable it for sure, but why on Earth would someone replace one method with a non-equivalent one??
