### ISSUE TITLE
Rule proposal:  `prefer-modern-dom-apis`

### ISSUE THREAD

**Issue by fregante** [sindresorhus/eslint-plugin-unicorn#344]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%2480%20Funded-%2300A156.svg" />](https://issuehunt.io/r/sindresorhus/eslint-plugin-unicorn/issues/344)

There more methods like `appendChild` and `removeChild`, for which we already have rules. 
They've all been replaced with better versions:

- [insertBefore](https://developer.mozilla.org/en-US/docs/Web/API/Node/insertBefore) -> [before](https://developer.mozilla.org/en-US/docs/Web/API/ChildNode/before)
- [replaceChild](https://developer.mozilla.org/en-US/docs/Web/API/Node/replaceChild) -> [replaceWith](https://developer.mozilla.org/en-US/docs/Web/API/ChildNode/replaceWith)
- [insertAdjacentText](https://developer.mozilla.org/en-US/docs/Web/API/Element/insertAdjacentText) -> [before](https://developer.mozilla.org/en-US/docs/Web/API/ChildNode/before), [after](https://developer.mozilla.org/en-US/docs/Web/API/ChildNode/after), [append](https://developer.mozilla.org/en-US/docs/Web/API/ChildNode/append), [prepend](https://developer.mozilla.org/en-US/docs/Web/API/ChildNode/prepend)
- [insertAdjacentElement](https://developer.mozilla.org/en-US/docs/Web/API/Element/insertAdjacentElement) -> [before](https://developer.mozilla.org/en-US/docs/Web/API/ChildNode/before), [after](https://developer.mozilla.org/en-US/docs/Web/API/ChildNode/after), [append](https://developer.mozilla.org/en-US/docs/Web/API/ChildNode/append), [prepend](https://developer.mozilla.org/en-US/docs/Web/API/ChildNode/prepend)

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $80.00)

- [<img src='https://avatars3.githubusercontent.com/u/44827199?v=4' alt='issuehunt' width=24 height=24> issuehunt](https://issuehunt.io/u/issuehunt) ($80.00)
### Submitted pull Requests
- [#362 Add `prefer-modern-dom-apis` rule](https://issuehunt.io/r/sindresorhus/eslint-plugin-unicorn/pull/362)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/sindresorhus/eslint-plugin-unicorn/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

**Comment by sindresorhus** [comment]
Alternative name: `prefer-modern-dom-apis`?

**Comment by mhatvan** [comment]
I would like to work on this.

**Comment by sindresorhus** [comment]
@mhatvan Go ahead :)

**Comment by fregante** [comment]
Was this not added to config-xo? This was not marked as error:

https://github.com/sindresorhus/refined-github/blob/86af70b3b9a816081af9e87e12036c3b54042df4/source/features/deep-blame.tsx#L63

**Comment by fisker** [comment]
@fregante I'm not sure 
if  it's added, but even  added, this rule won't report on this 
 case , see  https://github.com/sindresorhus/eslint-plugin-unicorn/issues/549
