### ISSUE TITLE
prevent-abbreviations: another meaning for the "dir" abbreviation

### ISSUE THREAD

**Issue by EvgenyOrekhov** [sindresorhus/eslint-plugin-unicorn#348]
prevent-abbreviations automatically replaces `dir` with `directory`, but `dir` might mean `direction`. Example: `sortDir` - "sort direction".

**Comment by sindresorhus** [comment]
We should probably add `direction` here: https://github.com/sindresorhus/eslint-plugin-unicorn/blob/6b6cee586442997188904648cdb0b66022ad589d/rules/prevent-abbreviations.js#L119
