### ISSUE TITLE
Use github actions?

### ISSUE THREAD

**Issue by fisker** [sindresorhus/eslint-plugin-unicorn#361]
Maybe this is not the good place to ask this, but just curious, are you interested in switching your ci to github actions? 

I've tried to run this project, here is the result

https://github.com/fisker/eslint-plugin-unicorn/runs/197837953

**Comment by fisker** [comment]
BTW: When I register azure pipelines, my id `fisker` is taken(ms gave it to me a few days later), so I checked your id `sindresorhus` and some other names, and I have this organization name now. you can have  it back anytime, just in case you  want  use azure

@sindresorhus

**Comment by sindresorhus** [comment]
Not really, unless it solve some huge problems. GitHub Actions is still very early and I don't want to deal with issues with it. The config is also very verbose compared to Travis.

**Comment by fisker** [comment]
Good to know
