### ISSUE TITLE
Definition for [several rules] was not found

### ISSUE THREAD

**Issue by limeandcoconut** [sindresorhus/eslint-plugin-unicorn#371]
I'm seeing:

```Definition for rule 'unicorn/consistent-function-scoping' was not found.eslint(unicorn/consistent-function-scoping)
Definition for rule 'unicorn/expiring-todo-comments' was not found.eslint(unicorn/expiring-todo-comments)
Definition for rule 'unicorn/expiring-todo-comments' was not found.eslint(unicorn/expiring-todo-comments)
```
With an otherwise working eslint config. At least one of unicorn's other rules is working. I've `rm -f`ed and `npm i`ed node modules, no change.

Deps:
```"eslint": "^6.4.0",
    "eslint-config-limeandcoconut": "^1.0.1",
    "eslint-plugin-html": "^6.0.0",
    "eslint-plugin-unicorn": "^10.0.0",
    "eslint-plugin-vue": "^5.2.3",
```
and limeandcoconut's deps:
```
    "eslint": "^6.4.0",
    "eslint-plugin-unicorn": "^10.0.0",
    "eslint-plugin-html": "6.0.0",
    "eslint-plugin-vue": "5.2.3"
```
`eslint-plugin-vue`  isn't being used right now. It's disabled until it gets upgraded to eslint ^6

**Comment by MrHen** [comment]
Can you run `npm ls eslint-plugin-unicorn` from your project directory and post the output?

**Comment by limeandcoconut** [comment]
```
electron-demo@1.0.0 /Users/jasmith/Sites/perpar/game-electron
├─┬ eslint-config-limeandcoconut@1.0.1
│ └── eslint-plugin-unicorn@10.0.0  deduped
└── eslint-plugin-unicorn@10.0.0 
```

**Comment by swernerx** [comment]
Same issue here. But only when running inside Jest - yes, we test our linting infrastructure :)

**Comment by swernerx** [comment]
Might be related to `import-modules` which is being used internally?

**Comment by swernerx** [comment]
Ah, I already did fix this for some previous customer of mine: https://github.com/sindresorhus/import-modules/issues/2 @sindresorhus can you please check this?
