### ISSUE TITLE
`consistent-function-scoping`: Ignore within `useEffect` in React Hooks

### ISSUE THREAD

**Issue by garyking** [sindresorhus/eslint-plugin-unicorn#392]
In React Hooks, I got:

```js
useEffect(() => {
  async function getItems() {}
  
  getItems()
}, [])
```

And it's definitely better to keep the function in the `useEffect`, to group it together. But this rule recommends moving out the function, of course.

Perhaps perform a check if the function is in `useEffect`, to ignore it?

**Comment by MrHen** [comment]
Hm, this is an interesting exception to the rule. Things like hooks or listeners might not have any references to the parent scope.

**Comment by futpib** [comment]
> And it's definitely better to keep the function in the `useEffect`, to group it together.

Is it definitely better? I imagine `getItems` having some fetching or other global side-effect code, it that case it would be better not only to move it out of the component, but maybe even into a separate file or module.

**Comment by garyking** [comment]
It's [recommended per the React docs](https://reactjs.org/docs/hooks-effect.html#example-using-hooks-1), at least.

**Comment by futpib** [comment]
Now that's a different case, they have `ChatAPI.subscribeToFriendStatus` (which I would consider analogous to `getItems` from your example) define somewhere outside the component and `useEffect` call, that's what I'd do (define it in a separate file). In this example `handleStatusChange` would not be reported as it captures `setIsOnline` from the component scope.

```js
import React, { useState, useEffect } from 'react';

function FriendStatus(props) {
  const [isOnline, setIsOnline] = useState(null);

  useEffect(() => {
    function handleStatusChange(status) {
      setIsOnline(status.isOnline);
    }

    ChatAPI.subscribeToFriendStatus(props.friend.id, handleStatusChange);
    // Specify how to clean up after this effect:
    return function cleanup() {
      ChatAPI.unsubscribeFromFriendStatus(props.friend.id, handleStatusChange);
    };
  });

  if (isOnline === null) {
    return 'Loading...';
  }
  return isOnline ? 'Online' : 'Offline';
}
```

**Comment by fisker** [comment]
```js
useEffect(() => {
  async function getItems() {
    function foo() {} 
  }
  
  getItems()
}, [])
```

What do we do with function `foo`? 

1. ignore
1. move to top of `useEffect`
1. move to top of `file`

**Comment by hatched-tom** [comment]
@fisker I believe 2 makes the most sense here, unless I'm missing something

**Comment by charliematters** [comment]
This doesn't seem to work when using the default import of react:
`React.useEffect(() => { ... })`
