### ISSUE TITLE
allow using `lower` suffix for `pascalCase` in `filename-case` rule

### ISSUE THREAD

**Issue by evilebottnawi** [sindresorhus/eslint-plugin-unicorn#395]
For example:
```
FooBar.test.js
```
Why?
1. Some tools use/recommend `lower` notation for part after `.`, for example `jest` use lower `test` (`FooBar.test.js`) in examples for class testing.
2. Sometimes you have vendor libraries (not in node_modules) and they use notation `Timer.min.js` (rare use case) 
3. Code for multiple platform, for example: `MyClass.web.js`, `MyClass.android.js` (react/react-native/other same tools)

Or maybe option to configure this

**Comment by fisker** [comment]
how about a whitelist？

**Comment by evilebottnawi** [comment]
Sounds good, maybe will be great allow whitelist using regexp

**Comment by evilebottnawi** [comment]
WIP on the `whitelist` option. 

Other case - i use `eslint-plugin-markdown` for linting code in Markdown files (using `kebabCase` and `pascalCase` values) so the `filename-case` rule report on some files, for example `.github/ISSUE_TEMPLATE` can be written in `kebabCase` or `pascalCase`. 

Also many developers use `README.md` and `CHANGELOG.md` as standard practice.

**Comment by evilebottnawi** [comment]
Maybe we should use `ignore` name because eslint uses `ignore` as options in some rules, anyway it will be easy to rename

**Comment by fisker** [comment]
`ignore` sounds better

**Comment by sindresorhus** [comment]
Let’s go with `ignore`.
