### ISSUE TITLE
`allowWarningComments` for `expiring-todo-comments` rule should be `true` by default

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/eslint-plugin-unicorn#398]
https://github.com/sindresorhus/eslint-plugin-unicorn/blob/master/docs/rules/expiring-todo-comments.md#allowwarningcomments

I missed that we made it false. I think it's better as `true`. As most people will probably make normal TODOs a warning and this rule an error.

// @lubien

**Comment by lubien** [comment]
I'll work on it asap!
