### ISSUE TITLE
Add option to the `throw-new-error` rule for working with custom errors

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/eslint-plugin-unicorn#4]
From: https://github.com/sindresorhus/eslint-plugin-xo/commit/53b7133c910695557d9c4a10079fac791b32c4dc#commitcomment-17077491

> An option that accepts an array of string/regex of error names? Could default to [/Error$/].
## 

New to making ESLint rules? Check out this quick guide on [how to get started](https://gist.github.com/sindresorhus/1656c46f23545deff8cc713649dcff26).

**Comment by jfmengels** [comment]
Would that be the default? Seems like a sensible one to me, as it's unlikely that someone throws something whose name ends with Error and is not an Error.

**Comment by sindresorhus** [comment]
`[/Error$/]` would be the default.

**Comment by sindresorhus** [comment]
How about we just hardcode it to `/^(?:[A-Z][a-z0-9]*)*Error$/` without an option? I can't imagine any custom error that wouldn't match that.

**Comment by jfmengels** [comment]
Yes, sounds good :+1:

**Comment by liubinyi** [comment]
Hi @sindresorhus @jfmengels , I would like to give a shot. please let me know if you have concerns on existing pr. Thanks
