### ISSUE TITLE
"No bad browser APIs" rule ideas

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/eslint-plugin-unicorn#402]
Would be useful to prevent use of some bad browser APIs.

For example, it's not recommended to use `document.cookie` directly as it's easy to get the string wrong. See https://github.com/sindresorhus/eslint-plugin-unicorn/issues/299 and https://developer.mozilla.org/en-US/docs/Web/API/Document/cookie Instead, the user should use a cookie library.

What other browser APIs are not recommended to use directly that this rule could cover?

**Comment by fisker** [comment]
I don't like this idea checking unrelated things together, how about a single rule just for cookie, maybe `no-cookie-access-directly`

Other api should not use directly, I think `IndexedDB` also has a horrible design, hard to use

**Comment by sindresorhus** [comment]
Sure, we can make them separate rules, but it's still valuable to have one issue here where we can discuss potential ideas.

I would call it `no-document-cookie-api`.

**Comment by MrHen** [comment]
The first couple that come to mind are `window.history` and `window.location`. I don't think there is inherently anything _wrong_ with using them but `window.location.href = foo` versus `window.location = foo` versus `window.location.assign(foo)` is pretty confusing.

**Comment by fisker** [comment]
Nerver heard `window.location.assign(foo)` before :(

I always use `window.location.href = foo`, but I've seen my colleague use `window.location = foo` and `document.location`, though `document.location` is the same, i prefer `window.location`

**Comment by fregante** [comment]
Honestly I’d block `location.href =` usage too. Often people use it instead of `location.replace()` for redirects and break the back button.

 `href` still makes sense when it’s inside a click listener but even then sometimes it’s just people not realizing they can use a plain anchor. It could be a `eslint-disable-line` exception

**Comment by sindresorhus** [comment]
I moved the cookie one into a new issue: https://github.com/sindresorhus/eslint-plugin-unicorn/issues/695
