### ISSUE TITLE
prefer-includes fix breaks utility library usage (eg. lodash)

### ISSUE THREAD

**Issue by JoshSchreuder** [sindresorhus/eslint-plugin-unicorn#410]
`prefer-includes` rule autofix incorrectly applies to usages of utility libraries like lodash.

For example:

```js
let arr = [1, 2, 3];

if (_.indexOf(arr, 1) !== -1) {
    console.log("true");
}
```

Becomes
```js
let arr = [1, 2, 3];

if (_.includes(arr)) {
    console.log("true");
}
```

After the fix is applied, which is semantically different and leads to bugs.

**Comment by fisker** [comment]
just realize `fromIndex` also not considered

```js
let arr = [1, 2, 3];

if (arr.indexOf(arr, 2, 1) !== -1) {
    console.log("true");
}
```

**Comment by MrHen** [comment]
> `prefer-includes` rule autofix incorrectly applies to usages of utility libraries like lodash.

The only way we could realistically handle this is to add a `blacklist` configuration option where it will ignore certain identifiers.

Aside from that, I would recommend turning the rule off for your project (and maybe using the [eslint-plugin-lodash variant](https://github.com/wix/eslint-plugin-lodash/blob/master/docs/rules/prefer-includes.md) instead.)

**Comment by JoshSchreuder** [comment]
> Aside from that, I would recommend turning the rule off for your project (and maybe using the eslint-plugin-lodash variant instead.)

Have turned it off for our project, however I think it's a little irresponsible to include a rule in your recommended configuration that could cause bugs on `--fix`. Any fixable rule outputs should be equivalent functionally IMO.
