### ISSUE TITLE
`no-fn-reference-in-iterator` autofix might break code

### ISSUE THREAD

**Issue by yangmingshan** [sindresorhus/eslint-plugin-unicorn#418]
Origin code
```js
const fn = (x, y) => x + y;

[1, 2, 3].map(fn);
```
After autofix
```js
const fn = (x, y) => x + y;

[1, 2, 3].map(x => fn(x));
```

**Comment by fisker** [comment]
I just check the orignal proposal https://github.com/sindresorhus/eslint-plugin-unicorn/issues/91 , isn't this by design?

I don't think this rule is fixable, we should remove the fixer.

**Comment by sindresorhus** [comment]
Yeah, let's remove the fixer for now, and we can bring it back for TypeScript users when we do https://github.com/sindresorhus/eslint-plugin-unicorn/issues/347.

**Comment by sindresorhus** [comment]
Actually, we could convert it into a suggestion => https://github.com/sindresorhus/eslint-plugin-unicorn/issues/441

**Comment by fisker** [comment]
just checked the rule, this NumberOfArguments is not right, more than 1/2 arguments , some of those methods may have up to 4 arguments, if I remember correctly

https://github.com/sindresorhus/eslint-plugin-unicorn/blob/567c9700e1557dce326001b7f2fe2ad1c7b0adc7/rules/no-fn-reference-in-iterator.js#L4-L14
