### ISSUE TITLE
Rule proposal: `prefer-trim-start-end` evaluating

### ISSUE THREAD

**Issue by evilebottnawi** [sindresorhus/eslint-plugin-unicorn#439]
Prefer `trimStart` over `trimLeft` (alias) and `trimEnd` over `trimRight` (alias)

Ref: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/trimstart
Ref: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/trimend

Maybe better name for rule

**Comment by sindresorhus** [comment]
PR welcome :)

**Comment by fisker** [comment]
name: `prefer-trim-start-end`, shorter

<details>
<summary>rules by name length</summary>
<code><pre>
no-unreadable-array-destructuring
prefer-exponentiation-operator
no-fn-reference-in-iterator
consistent-function-scoping
prefer-trim-start-and-end  // No.5
prefer-add-event-listener
no-abusive-eslint-disable
prefer-starts-ends-with
custom-error-definition
expiring-todo-comments
prevent-abbreviations
prefer-query-selector
explicit-length-check
prefer-reflect-apply
no-unused-properties
prefer-text-content
prefer-string-slice
number-literal-case
no-array-instanceof
prefer-node-remove
prefer-node-append
prefer-type-error
no-zero-fractions
no-nested-ternary
no-keyword-prefix
no-console-spaces
prefer-event-key
new-for-builtins
catch-error-name
throw-new-error
regex-shorthand
prefer-includes
prefer-flat-map
no-unsafe-regex
no-process-exit
prefer-dataset
prefer-spread
no-new-buffer
no-hex-escape
filename-case
error-message
import-index
no-for-loop
escape-case
</pre></code>
</details>

**Comment by fisker** [comment]
I'm going to work on this, should be very simple
