### ISSUE TITLE
Disscuss `dir => direction` replacement

### ISSUE THREAD

**Issue by fisker** [sindresorhus/eslint-plugin-unicorn#460]
I was trying to do something about `prevent-abbreviations`, found something interesting about `dir => direction` replacement, 

@futpib suggested this first, https://github.com/sindresorhus/eslint-plugin-unicorn/pull/237#issuecomment-467945046

@sindresorhus decided to drop it https://github.com/sindresorhus/eslint-plugin-unicorn/pull/237#issuecomment-470940285

then added it again https://github.com/sindresorhus/eslint-plugin-unicorn/issues/348#issuecomment-528083040

Keeping this makes `dir => directory` not auto-fixable

**Comment by sindresorhus** [comment]
My comment was before we started supporting combinations like `sortDir`, which does make sense. I don't think we should do anything about this. However, what will help a lot would be to support the [ESLint suggestions API](https://github.com/sindresorhus/eslint-plugin-unicorn/issues/441), which would let users interactively choose a fix in their editor.

**Comment by fisker** [comment]
Let's do suggestions later
