### ISSUE TITLE
Rename `regex-shorthand` rule?

### ISSUE THREAD

**Issue by fisker** [sindresorhus/eslint-plugin-unicorn#469]
`regex-shorthand` do more than just `shorthand` now, should we rename it?
also [`no-unsafe-regex` is buggy](https://github.com/sindresorhus/eslint-plugin-unicorn/issues/153) and already `off` by default, and I looked around, didn't found a better solution, maybe we can remove it, if we found a better way to do it, maybe we can add a option to `regex-shorthand` rule.

**Comment by sindresorhus** [comment]
Some name suggestions:

- `better-regex`
- `improved-regex`
- `optimized-regex`

**Comment by yakov116** [comment]
Optimized-regex

**Comment by fisker** [comment]
for now `optimized-regex` sounds reasonable, if we try combine `no-unsafe-regex` with this one, I perfer `better-regex`

**Comment by sindresorhus** [comment]
Let's go with `better-regex`.

**Comment by fisker** [comment]
Need a better rule description

`Enforce the use of regex shorthands to improve readability` (old)

and error message

`Use regex shorthands to improve readability.` (old)

**Comment by sindresorhus** [comment]
Let's first summarize what the rule does now:

- Enforces shorthands readability
- Sorts character classes for consistency
- What else?

**Comment by fisker** [comment]
https://github.com/DmitrySoshnikov/regexp-tree/tree/master/src/optimizer#transforms

**Comment by sindresorhus** [comment]
We don't need to mention all of those though. We can link to it in the docs.

So in summary:
- Enforces shorthands readability
- Sorts character classes for consistency
- Makes regexes safer

So for description, maybe:

> Improve regexes by making them shorter, consistent, and safer.

As for the error message, that really depends on the transformation being done though.
