### ISSUE TITLE
regex-shorthand autofix changes the meaning of regex

### ISSUE THREAD

**Issue by rsml** [sindresorhus/eslint-plugin-unicorn#472]
Using rule: `"unicorn/regex-shorthand": 2,`

This line:
`'a0'.split(/[ ;-]/g)`
=> `["a0"]`

Gets autofixed to:
`'a0'.split(/[ -;]/g)`
=> `["a", ""]`

To work around, I just added a blackslash before the `-`.

I think the autofix for `unicorn/regex-shorthand` should preserve the position of any hyphens at the beginning or end of a character class.

**Comment by sindresorhus** [comment]
Can you open an issue on https://github.com/DmitrySoshnikov/regexp-tree? Which is what we use to optimize the regex. I think we should also disable that optimization for now until it's fixed in `regex-tree`.

**Comment by rsml** [comment]
It was reported a year ago over there: https://github.com/DmitrySoshnikov/regexp-tree/issues/163. I agree with disabling it for now.
