### ISSUE TITLE
File extension option for filename-case rule

### ISSUE THREAD

**Issue by Stanzilla** [sindresorhus/eslint-plugin-unicorn#475]
Hey there, any way we could get an option to also (or just) check file name extensions with this rule?

**Comment by sindresorhus** [comment]
What's the use-case? Would be good to see an example of how you would use such an option.

**Comment by Stanzilla** [comment]
Mainly because my editors keep checking in .PNG/.JPG etc. Currently using a pre-commit hook to prevent that but alerting before would be nice.

**Comment by fisker** [comment]
I'm going to close this, you should not run eslint on any `.png/.jpg` file.
