### ISSUE TITLE
Error while loading rule unicorn/expiring-todo-comments

### ISSUE THREAD

**Issue by momakes** [sindresorhus/eslint-plugin-unicorn#479]
`ESLint: Error while loading rule 'unicorn/expiring-todo-comments': Invalid Version: null Occurred while linting`

I keep getting it on every ESLint run in VS Code on any file that has a TODO comment with version. Wasn't like this before. Tried updating, no luck.

What else can I provide?

**Comment by sindresorhus** [comment]
// @lubien

**Comment by momakes** [comment]
Update: Here's a GIF to demonstrate (it's annoying!)
![CleanShot 2019-12-17 at 14 44 51](https://user-images.githubusercontent.com/56743114/70991031-f47d4b00-20db-11ea-8ae0-d0744f1e25a7.gif)

**Comment by SimenB** [comment]
FWIW 12.1.0 works, >=13 has the error

**Comment by fisker** [comment]
@momakes Can you test if #494 fixes your problem?

You can add this by `yarn add fisker/eslint-plugin-unicorn#fix-expiring-todo-comments` or `npm i fisker/eslint-plugin-unicorn#fix-expiring-todo-comments`(not sure this command is correct)

**Comment by SimenB** [comment]
@fisker works in my project 👍

**Comment by fisker** [comment]
@SimenB Thanks.
