### ISSUE TITLE
Allow multiple `name` for `catch-error-name`

### ISSUE THREAD

**Issue by evilebottnawi** [sindresorhus/eslint-plugin-unicorn#48]
Sometimes we have the following code:

``` js
const fs = require('fs');
try {
  fs.readFileSync('./foo';)
} catch (err) {
  // Nothing
}
```

And if enable rule `no-unused-vars` we have error. For ignoring this construction we can use http://eslint.org/docs/rules/no-unused-vars#caughterrorsignorepattern. But if i use `ignoreErr` i get error from `catch-error-name` rule.

**Comment by sindresorhus** [comment]
Wonder if we can just read and use the setting from that rule.

**Comment by evilebottnawi** [comment]
@sindresorhus it would be even better :smile:

**Comment by sindresorhus** [comment]
@jfmengels Do you know if that's possible?

**Comment by jfmengels** [comment]
Doesn't look like it no, except if we manually try to find the `.eslintrc` file (harder than it looks), parse it, etc.

The `context` object ESLint provides has a few methods, and I found the `defaults` methods, which returns the default ESLint config (with rule configurations and all). I have no idea how that could be useful, but that is something close to what we'd want to have. We could open an issue requesting to have a new method that returns the whole configuration.
