### ISSUE TITLE
v15 is incompatible with Node 8

### ISSUE THREAD

**Issue by bmish** [sindresorhus/eslint-plugin-unicorn#481]
[v15](https://github.com/sindresorhus/eslint-plugin-unicorn/releases/tag/v15.0.0) was just released and is incompatible with Node 8 due to the dependency on semver being upgraded.

```
error semver@7.1.1: The engine "node" is incompatible with this module. Expected version ">=10". Got "8.17.0"
```
I understand that Node 8 is end-of-life soon, so if this breaking change is intentional, it would help if it was documented in the release notes / CHANGELOG / README.

If the change is not intentional, then semver could be downgraded and a patch released, and the supported Node versions could be documented in the README.

I would personally prefer if Node 8 could be supported for at least a few more months to give other packages using eslint-plugin-unicorn some more time to drop support for it, unless there is an actual need to drop it now.

(also: why didn't the tests catch this breakage? .travis.yml specifies Node 8 as one of the versions to test under.)

**Comment by sindresorhus** [comment]
This was not intentional. I'll make sure it doesn't happen again: https://github.com/sindresorhus/np/issues/480

> (also: why didn't the tests catch this breakage? .travis.yml specifies Node 8 as one of the versions to test under.)

Because npm doesn't enforce the `engine` field. It's really stupid.
https://docs.npmjs.com/misc/config#engine-strict
