### ISSUE TITLE
erroneous unicorn/regex-shorthand

### ISSUE THREAD

**Issue by PopGoesTheWza** [sindresorhus/eslint-plugin-unicorn#499]
Just to add another case of erroneous regex fix:

This regex `/^[a-z][a-z0-9\-]{5,29}$/` is changed to `/^[a-z][\d-a-z]{5,29}$/`...

Replacing `[0-9]` with `[\d]` is fine but changing `\-` into `-`, without moving it to first position breaks the regex.

Either `/^[a-z][-\da-z]{5,29}$/` or `/^[a-z][\d\-a-z]{5,29}$/` would be acceptable solutions.

Here is a [Repl.it link](https://repl.it/@PopGoesTheWza/unicornregex-shorthand) to illustrate this issue.

**Comment by JounQin** [comment]
It maybe a bug of JavaScript itself: https://regexper.com/#%2F%5B%5Cd-a-z%5D%2F

But we have to "fix" it. :(

**Comment by PopGoesTheWza** [comment]
@JounQin It should be fixed with https://github.com/DmitrySoshnikov/regexp-tree/issues/163

**Comment by fisker** [comment]
We need add test on this case, so we can close this issue.

**Comment by JounQin** [comment]
@PopGoesTheWza I checked my `yarn.lock`, the version of `regexp-tree` is `0.1.18`, but it does not work.
