### ISSUE TITLE
`prefer-node-remove`: Remove requirement for `removeChild` to be on `parentElement` or `parentNode`

### ISSUE THREAD

**Issue by brettz9** [sindresorhus/eslint-plugin-unicorn#506]
There is a requirement specific to `prefer-node-remove` which expects the parent to be named "parentNode" or "parentElement".

There is no such requirement in `prefer-modern-dom-apis` with `replaceChild` or `insertBefore`, and I think there need be no such requirement.

**Comment by fisker** [comment]
Can you point me the line ? Can't find

**Comment by brettz9** [comment]
Sure. https://github.com/sindresorhus/eslint-plugin-unicorn/blob/master/rules/prefer-node-remove.js#L63-L64

**Comment by fisker** [comment]
Sorry , I thought talking about `prefer-modern-dom-apis` haha.

Indeed, it seem unnessary, I think the old one mean to fix only  `foo.parentNode.removeChild(foo)` but accidentally also allow `parentNode.removeChild(foo)`. 

Question is ` can bar.removeChild(foo)` fix to `foo.remove()`, I think its safe.

**Comment by brettz9** [comment]
Yes, I think it would be. And sometimes I even use `parentNode` as the variable name, e.g., `const {parentNode} = node;` so end up with `parentNode.removeChild(foo)` or, as in your example, `bar.removeChild(foo)`.

**Comment by fisker** [comment]
Also I think old one  allow `foo.parentNode.removeChild(bar)` since argument and caller is  not compared. so this check is meaningless. Can you confirm this for me? Not on my laptop

**Comment by brettz9** [comment]
`foo.parentNode.removeChild('bar')` is a valid test case (i.e., it is not reported).

I think it should be reported thoug since `foo` could be a sibling of `bar`.

**Comment by fisker** [comment]
No this case is not what I mean , Literal cant pass argument check `bar` without quotes

**Comment by brettz9** [comment]
Oh, oops, yeah, I see... Let me check.

**Comment by brettz9** [comment]
You're right, `foo.parentNode.removeChild(bar)` is reported as invalid and fixed to `bar.remove()`.

**Comment by fisker** [comment]
Ok, accepted. remove that check, PR welcome

**Comment by fisker** [comment]
Other things  to be done, 

1. check arguments length, as we do in other similar cases
2. fix the argument check, should allow other types like `removeChild(foo.bar)` `removeChild(foo[0])` , it should allow any type except some type that cant be a `Node` like literal type

**Comment by brettz9** [comment]
Ok, I've done #1 (including for `prefer-node-append`, where I also changed to include the callee property name inside the selector).

I'm not sure what you mean about the parentheses in #2.

**Comment by brettz9** [comment]
And I've added the callee type within the selector for `prefer-modern-dom-apis`.

**Comment by brettz9** [comment]
I don't know if you want to crowd any more than one condition into the selectors, even though it appears possible per https://eslint.org/docs/developer-guide/selectors#restricting-syntax-with-selectors .

**Comment by fisker** [comment]
for 2, `foo.removeChild(foo.bar)` is not fixed, because arguments[0] is not `Identifier` or `ThisExpression`.

Abount I mean , `foo.removeChild(await bar())` can't fix to `await bar().remove()` should be `(await bar()).remove()` 


And 

```js
const array = []
foo.removeChild(await bar())
```
to
```js
const array = []
(await bar()).removeChild()
```
still not right, this is right. (but we can forget about this, too hard)
```js
const array = []
;(await bar()).removeChild()
```

**Comment by fisker** [comment]
> I don't know if you want to crowd any more than one condition into the selectors, even though it appears possible per [eslint.org/docs/developer-guide/selectors#restricting-syntax-with-selectors](https://eslint.org/docs/developer-guide/selectors#restricting-syntax-with-selectors) .

I think only check `callee.property.name` in selector is good enough, you can add more if you want.

**Comment by fisker** [comment]
@brettz9 I thought about this today again. The fix maybe more complicate, say we have this

```js
someDomLib('div')
	.one()
	.two()
	.three()
	.four()
	.getParent() // do a lot of stuff , and return the parent at last
	.removeChild(bar);
```

I think we just fix it to 

```js
bar.remove();
``

actually, we should do

```
someDomLib('div')
	.one()
	.two()
	.three()
	.four()
	.getParent(); // do a lot of stuff , and return the parent at last
bar.remove();
```
