### ISSUE TITLE
Prefer unicode escapes over hexadecimal escapes

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/eslint-plugin-unicorn#51]
`\x1B` → `\u001B`

For consistency.

[Reading material.](https://mathiasbynens.be/notes/javascript-escapes#unicode)

-

Rule name suggestion?

-

Should be auto-fixable.

**Comment by matijs** [comment]
Going to have a crack at this if that's ok.

**Comment by sindresorhus** [comment]
@matijs Go ahead :) I just wrote a quick guide on how to get started: https://gist.github.com/sindresorhus/1656c46f23545deff8cc713649dcff26
