### ISSUE TITLE
`escape-case` rule

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/eslint-plugin-unicorn#54]
In JS you can write escapes with either uppercase or lowercase value. Would be useful to have a rule to enforce the value to be uppercase. Don't want an option for this as lowercase is a bad practice.

For example `\xa9` and `\xA9` are equivalent, but the latter is clearer. `\ud834\udf06` and `\uD834\uDF06` are too.

The following should be supported (the values are just there as an example):
- `\xA9`
- `\uD834`
- `\u{1D306}`
- `\cA`
## 

Suggestions for a better rule name?

Alternative: `uppercase-escape`
## 

Would be useful if it works in a regex too, though not essential for the first version: https://github.com/sindresorhus/filename-reserved-regex/blob/af9c88cd73ba944ec27c64173aa9017ec80e7d2a/index.js#L4
## 

Should also be possible to auto-fix it, right?

**Comment by florianb** [comment]
I'd be happy to help -- unfortunately I am pretty unused to eslint-rules. So i guess i need some time t find out how to write a rule.

**Comment by sindresorhus** [comment]
@florianb Awesome! I just wrote a quick guide on how to get started: https://gist.github.com/sindresorhus/1656c46f23545deff8cc713649dcff26

**Comment by Bebersohl** [comment]
@florianb I am also working on this. Let me know if you want to collaborate.

**Comment by florianb** [comment]
Thanks for the hint @Bebersohl! 🤔 I'd probably pick another rule up to avoid things are done twice. But i'd really appreciate to collaborate by receiving and giving feedback. Probably you want to ping me if you have questions or if i can help in any way.

If you want i'd ping you too. 😸
