### ISSUE TITLE
`number-literal-case` rule

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/eslint-plugin-unicorn#55]
[JS has different number literals.](http://www.2ality.com/2015/04/numbers-math-es6.html) Casing is of course not enforced, because why would you want consistency or readable numbers?...

This rule should enforce lowercase literal identifier and uppercase value.

No option for this as none of the failing cases makes sense.

Should be auto-fixable.

### Fail

```js
0XFF
0xff
0Xff

0B11

0O10
```

### Pass

```js
0xFF

0b11

0o10
```

**Comment by sindresorhus** [comment]
For anyone wanting to try their hand at this, read: http://eslint.org/docs/developer-guide/working-with-rules

Go ahead and play around with some code in http://astexplorer.net/ (Make sure the parser is `espree`).

All you have to do here is to detect numbers and validate their raw source. For example, try `0b1010` in AST Explorer. You just need to tell ESLint that you want to listen to any `ExpressionStatement`. You then ensure `node.expression.type === 'Literal'`, and you can check its `.raw` property, where you get `0b1010` as a string and can ensure it's in the correct format.

**Comment by SamVerschueren** [comment]
I'm looking into this as I'm totally new to ESLint rules. I tried using `ExpressionStatement` but it doesn't seem to work.

I try to lint `const foo = 0xFF`, but it only works if when I use `Literal` as key. Am I doing something wrong here?

```js
const create = context => {
	return {
		ExpressionStatement: node => {
			console.log('expression statement');
		},
		Literal: node => {
			console.log('literal');
		}
	};
};
```

**Comment by SamVerschueren** [comment]
I created a rule, not sure if I comply with everything regarding conventions etc. So any feedback (implementation, docs, plugin name, ...) is more then welcome as it's my first ESLint rule ever. I didn't publish it yet because I want some feedback first.

:tada: https://github.com/SamVerschueren/eslint-plugin-number-literal-case

// @jfmengels

**Comment by jfmengels** [comment]
@SamVerschueren It all looks pretty good to me! Nice job!

Any reason you don't want to implement it in this plugin? From my experience, people tend to not like adding a lot of plugins (part f the reason why people ike `xo` and `standard`), so single-rule plugins tend to not be used much by the community. Even my relatively popular `eslint-plugin-import-order` got merged into `eslint-plugin-import` for this kind of reason.

**Comment by SamVerschueren** [comment]
Oh, I thought it was meant to be created separately. I will merge it in later today :).
