### ISSUE TITLE
prevent-abbreviations: Inappropriate suggested rename for `pkg`

### ISSUE THREAD

**Issue by coreyfarrell** [sindresorhus/eslint-plugin-unicorn#579]
```
 ✖  15:23  The variable pkg should be named package. A more descriptive name will do too.  unicorn/prevent-abbreviations
```

Following this suggestion produces a parse error in strict / ES module mode as `package` is a reserved name.  I've just renamed the variable to `packageFile` but still wanted to share this finding so you would be aware.  Not sure what an appropriate generic suggestion would be, maybe this rule could ignore `pkg` but still suggest `pkgFile` -> `packageFile`?

**Comment by sindresorhus** [comment]
Weird. In those cases it’s supposed to suggest `package_`.
