### ISSUE TITLE
unicorn/better-regex rule missing (16.1.1)

### ISSUE THREAD

**Issue by stephen-dirtcreative** [sindresorhus/eslint-plugin-unicorn#582]
*Environment*:
eslint v6.8.0
eslint-plugin-unicorn v16.1.1

*eslintrc.js*:
[snip]
rules: {
  ...
  'unicorn/better-regex': 'error',
  ...
}
[/snip]

*Expected*:
Rule exists

*Actual*:
'Definition for rule ... not found'

*Triage*:
Looking in the package files (./node_moduels/eslint-plugin-unicorn/rules/ shows there is no better-regex.js file

**Comment by fisker** [comment]
`unicorn/better-regex` was named `unicorn/regex-shorthand` https://github.com/sindresorhus/eslint-plugin-unicorn/pull/522 ,[this change](https://github.com/sindresorhus/eslint-plugin-unicorn/pull/522) has not been released.

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/eslint-plugin-unicorn/releases/tag/v17.0.0
