### ISSUE TITLE
`better-regex` rule not found

### ISSUE THREAD

**Issue by brettz9** [sindresorhus/eslint-plugin-unicorn#583]
Apologies if this ends up being more of a tooling issue, but as it impacts a new unicorn rule, I thought I'd bring it up in case it is due to some config.

After updating to Unicorn 17.0.0, when I use my IDE (Atom) with the `linter-eslint` package, I am getting an error in my linter, even after IDE restart, that "Definition for rule 'unicorn/better-regex' was not found. (unicorn/better-regex)". Yet when I run my `eslint` script for the same repository, there are no complaints. I see it is indeed version 17 in `node_modules`, and I see the file for `better-regex` and `index.js` pointing to it.

I have global eslint disabled in the IDE setting (and uninstalled my global copy just to be safe), so I really find it puzzling why it says the rule wasn't found.

Even more puzzling--I get the error about the rule when checking a file in one repo and not in another (where both use the rule).

Getting it even when paring down to just:

```js
module.exports = {
  "extends": [
    "plugin:unicorn/recommended"
  ],
  "plugins": [
    "promise"
  ],
  "rules": {
    "unicorn/better-regex": ["error"]
  }
};
```

or

```js
module.exports = {
  "plugins": [
    "unicorn",
    "promise"
  ],
  "rules": {
    "unicorn/better-regex": ["error"]
  }
};
```

Adding "root": true` does not help either.

If I switch to `unicorn/regex-shorthand`, it works.

Any thoughts of what this could be?

**Comment by yakov116** [comment]
https://github.com/sindresorhus/eslint-plugin-unicorn/releases

>Breaking
>Rename regex-shorthand rule to better-regex (#522) a5e5405

**Comment by brettz9** [comment]
Yes, thanks, but I'm trying with that new rule,`better-regex`. I just mentioned the `regex-shorthand` to contrast that it is working while `better-regex` is not. Despite my having updated to the version which should have `better-regex` and appears to.

**Comment by brettz9** [comment]
Still getting this after #584 / v17.0.1 upgrade (and Atom restart)...

**Comment by brettz9** [comment]
Figured it out... My home directory had an older copy of unicorn. The IDE's algorithm (FWIW, in `getRelativePath` of `linter-eslint/src/worker-helpers.js`) to set a base path was to look for an `.eslintignore`, and in this case, as I didn't have one in that project, it looked in the home directory and finding one there, it set that HOME path to be the linting path. Adding an `.eslintignore` to my project worked around the issue for me (and yes, I do want to have linting info at HOME). Sorry for the noise! Thanks!
