### ISSUE TITLE
Enforce `Buffer.from` instead of `new Buffer`

### ISSUE THREAD

**Issue by SamVerschueren** [sindresorhus/eslint-plugin-unicorn#59]
Since `new Buffer()` is being deprecated since Node.js >= 6, it might be nice if we could enforce this some day in the future. Not sure if it makes sense to already create this rule because ESLint can't target specific Node.js versions, right?

**Comment by jfmengels** [comment]
> ESLint can't target specific Node.js versions, right?

You're right, it can't.

> Not sure if it makes sense to already create this rule

Well, it can be useful for people who will only target Node >= 6 versions for their app/libraries, so I'd say yes.

I wonder, are there any other similar constructs where `new XYZ()` is replaced by a method on `XYZ`? I don't know if it would make sense to generalize this.

**Comment by sindresorhus** [comment]
`Buffer.from()` was backported to Node.js 4 (benefits of it being LTS), so we can safely enforce it.

**Comment by kevva** [comment]
> Buffer.from() was backported to Node.js 4 (benefits of it being LTS), so we can safely enforce it.

Oh, didn't know that. Nice!

**Comment by SamVerschueren** [comment]
I want to take this one if that's ok?

**Comment by sindresorhus** [comment]
@SamVerschueren Go ahead 🤘

**Comment by jfmengels** [comment]
> I wonder, are there any other similar constructs where new XYZ() is replaced by a method on XYZ? I don't know if it would make sense to generalize this.

So this will be a rule specific to Buffer then?

**Comment by sindresorhus** [comment]
@jfmengels Yes. We can add a more generic rule in the future if use-cases come up.

**Comment by SamVerschueren** [comment]
> So this will be a rule specific to Buffer then?

Exactly, no need to add a "complex construct" which might never get used. We can always improve later on.

**Comment by jfmengels** [comment]
Okay, sounds good to me.

**Comment by kevva** [comment]
Make sure to take `Buffer.alloc` into account too. See https://github.com/kevva/to-ico/commit/22b447205d26db3cb8245d83e94fb09b90f79bee.

**Comment by SamVerschueren** [comment]
Aha, good catch @kevva. It's not as simple as finding a `NewStatement` with `Buffer` and changing that to `Buffer.from()`.

**Comment by niksy** [comment]
Just wanted to point out that eslint-plugin-node has similar rule for deprecated APIs if you need some hints on how to additionally approach this: https://github.com/mysticatea/eslint-plugin-node/blob/master/docs/rules/no-deprecated-api.md

**Comment by SamVerschueren** [comment]
How should we call this rule?

- `no-new-buffer`
- `new-buffer-deprecated`
- `buffer-deprecated`
- ...

**Comment by sindresorhus** [comment]
@SamVerschueren `no-new-buffer`

**Comment by SamVerschueren** [comment]
Should we also cover the case that someone could write this?

```
const buf = Buffer('foo');
```

**Comment by sindresorhus** [comment]
Nah, I've never seen anyone write that, and as you said, it's already covered by the `new-cap` rule.
