### ISSUE TITLE
Rule proposal: Prefer `Number` methods

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/eslint-plugin-unicorn#594]
### Fail

```js
parseInt(…);
parseFloat(…);
isNaN(…);
isFinite(…);
```

### Pass

```js
Number.parseInt(…);
Number.parseFloat(…);
Number.isNaN(…);
Number.isFinite(…);
```

This rule cannot be auto-fixable as the globals methods have slightly different behavior. However, it **should** use the ESLint suggestions API.

Should we also enforce `Number.NaN` over `NaN`? They equivalent. I'm leaning towards "yes", for consistency, and also less use of floating globals.

**Comment by fisker** [comment]
I  never  see anyone use `Number.NaN`, but  we  can make a option to enable it.

Relate issue on eslint https://github.com/eslint/eslint/issues/8894

**Comment by sindresorhus** [comment]
Maybe we could just try enforcing `Number.NaN` and see if anyone cares enough to complain?

**Comment by fisker** [comment]
One  note, please  use this `isShadowed` check https://github.com/sindresorhus/eslint-plugin-unicorn/blob/cdfedd8451bffa613f3e0bfbadbda71335b5f1c8/rules/new-for-builtins.js#L20 when  implementing.

**Comment by fisker** [comment]
Name suggestion? How about `no-global-number-method`? But `Number.NaN` is not a method

**Comment by fisker** [comment]
`prefer-number-member`?

**Comment by fisker** [comment]
Should we suggest `Number.POSITIVE_INFINITY` and `Number.NEGATIVE_INFINITY` over `Infinity`

**Comment by sindresorhus** [comment]
> prefer-number-properties

👍 

> Should we suggest Number.POSITIVE_INFINITY and Number.NEGATIVE_INFINITY over Infinity?

No, `Infinity` is still better. The difference between positive/negative `Infinity` doesn't matter in 99% of cases.

**Comment by jimmywarting** [comment]
I would like to see a reasoning for why number properties are better, (and not just because of global-phobia)
If you can't argument for a good reason, then don't break something that isn't broken.

I came here for the `Number.NaN` reason... never seen anyone write that
Some functions are the same, `parseInt === Number.parseInt`, `Number.parseFloat === parseFloat`

isNaN i can understand it's not the same as `Number.parseInt` and dose things differently

**Comment by sindresorhus** [comment]
> If you can't argument for a good reason, then don't break something that isn't broken.

No one is forcing you to use this rule. You can opt out of it.

> ...or using Number Number.NEGATIVE_INFINITY That's just too long and unpleasant to write

There's an option to not check `Infinity`. I still personally prefer it for consistency.

> Some functions are the same, parseInt === Number.parseInt, Number.parseFloat === parseFloat

Consistency. When there are some that are better and should be preferred, it's better for readability to consistency use the `Number` methods ones.

**Comment by jimmywarting** [comment]
> No one is forcing you to use this rule. You can opt out of it.

That's what all linter say. 
Think it should be the reverse, You can opt **in** for non-essential rules

**Comment by jimmywarting** [comment]
Reason agains Number.parseInt

Don't work in IE
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/parseInt

But it's pretty much dead now anyway

**Comment by fisker** [comment]
Isn't all these properties not available in IE? If you are targeting IE, you can't check any  of them.

**Comment by fisker** [comment]
I think we can add option for `Number.NaN`, but not othere properties, otherwise this rule won't make sense to enable.

**Comment by jean-moldovan** [comment]
There are cases when you, for example, parse query params and want to be able to convert a string into a number if possible: `0`, `invalid`, `123`.

So you would do:
```
  if (isNaN(score)) { <-- Number.isNaN works differently here
    return null
  }

  return Number(score)
```

**Comment by fisker** [comment]
This is why we didn't auto fix this case https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prefer-number-properties.md

**Comment by jean-moldovan** [comment]
Yes, but the difference is that the linter will still complain causing confusion unless you tell it to ignore that line.

<img width="1021" alt="Screenshot 2021-11-05 at 11 12 43" src="https://user-images.githubusercontent.com/3635352/140495036-a24efca4-b00c-477e-bc28-1f0bcb7c7146.png">

Making it configurable can solve this.

**Comment by fisker** [comment]
That's the point of this rule, you should refactor to use `Number.isNaN()`

**Comment by fregante** [comment]
> you should refactor to use `Number.isNaN()`

What is the suggested refactor though?  This?

```js
- if (isNaN(numberOrIdk)) {
+ if (typeof numberOrIdk !== number || Number.isNaN(numberOrIdk)) {
```

If so, it's quite verbose.

- Related: https://github.com/sindresorhus/eslint-plugin-unicorn/issues/1751

**Comment by fisker** [comment]
I think

```diff
- if (isNaN(numberOrIdk)) {
+ if (Number.isNaN(Number(numberOrIdk))) {
```

is more correct.
