### ISSUE TITLE
Dead code in `no-keyword-prefix`

### ISSUE THREAD

**Issue by fisker** [sindresorhus/eslint-plugin-unicorn#598]
`options.ignoreDestructuring` is used  https://github.com/sindresorhus/eslint-plugin-unicorn/blob/054e04b22a2b08bb5b996206add0b657c1f3b394/rules/no-keyword-prefix.js#L144

There is no such option in both [`schema`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/054e04b22a2b08bb5b996206add0b657c1f3b394/rules/no-keyword-prefix.js#L186-L209), [docs](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/master/docs/rules/no-keyword-prefix.md) and [tests](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/master/test/no-keyword-prefix.js). And this is not mentioned in [the initial commit](https://github.com/sindresorhus/eslint-plugin-unicorn/pull/282). What to do?

**Comment by sindresorhus** [comment]
Remove it.
