### ISSUE TITLE
Rule proposal: No reduce

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/eslint-plugin-unicorn#623]
Using `Array#reduce` is in most cases not the right solution. It just makes code harder to read.

https://twitter.com/jaffathecake/status/1213077702300852224

I think it's better to just use "eslint-disable"  comments when it's actually needed for summing number, which is rare.

**Comment by papb** [comment]
Hmm 🤔 interesting... I also don't like reduce generally, but I've seen people that do. I would probably enable this rule in my projects.

I think it should not be part of `plugin:unicorn/recommended` though. Or maybe it could be, but as a warning. An error by default would probably make many people angry.

**Comment by sindresorhus** [comment]
It should be on by default as an error. I’m not concerned about angry users. We do what’s best for code readability regardless of whether it might be controversial. Users can just disable the rule.

**Comment by sindresorhus** [comment]
This is now accepted. PR welcome if anyone wants this.

**Comment by fisker** [comment]
A video taking about that tweet https://youtu.be/qaGjS7-qWzg

**Comment by ankeetmaini** [comment]
I can take a stab at it. So it should fail at any instance of `Array.reduce`?

**Comment by papb** [comment]
@ankeetmaini Yes.

**Comment by wldcordeiro** [comment]
A tweet as validation for why a rule should be added and enforced by default. 🤦

**Comment by papb** [comment]
@wldcordeiro No, a tweet as inspiration, something that OP (and owner of the repository) agrees to, an issue created, waited over one month for feedback, other people gave thumbs-up, a brief discussion happened, no one objected concretely, and above all that, you can just disable the rule with one line.

**Comment by philihp** [comment]
This is great! Can we also turn off `Array.map` also, for the same reasons?

**Comment by fisker** [comment]
What's wrong with `Array#map`?

**Comment by philihp** [comment]
It just makes code harder to read.

**Comment by papb** [comment]
I disagree, I think `map` is excellent. Can you show some examples of code using `map` to which you propose better readability without `map`?

**Comment by philihp** [comment]
Hold up, now we like `map`, but we don't like `reduce`?

**Comment by papb** [comment]
@philihp Yes. At least I do.

**Comment by wldcordeiro** [comment]
I've liked reduce too. This library is hitting a threshold where it's becoming _too_ opinionated for the recommended. 🙄

**Comment by aquator** [comment]
@philihp is right, also clearly trolling. Map is fine, reduce is not? Why not? That is a pretty basic operation. Let's disable flatMap too, because it is hard to understand! Please remove this one, makes no sense at all.
