### ISSUE TITLE
`prefer-string-slice` rule

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/eslint-plugin-unicorn#65]
I prefer `.slice()` over `.substr()` and `.substring()`. `.slice()` has clearer behavior and has a counterpart with arrays. Also better to be consistent. Anything you do with `.substr()` or `.substring()` can be done with `.slice()`.

Read more: http://stackoverflow.com/questions/2243824/what-is-the-difference-between-string-slice-and-string-substring

I'm aware we can't do type checking, but I think we can just assume a string when we see `.substr()` and `.substring()`. Worth the risk I think.
## 

Thoughts?

**Comment by matijs** [comment]
Had a lot of fun doing #51, so wouldn't mind doing some work on this as well. Should be fixable as well with the fix being a bit more interesting than the one in #51 :)

**Comment by jfmengels** [comment]
@matijs Go ahead and have fun :)

**Comment by matijs** [comment]
So… regarding fixability… 

If one or more of the arguments of `substr` or `substring` is a `Literal` it's easy. Not so much so if we're dealing with `FunctionExpression`s. Or am I missing something?

**Comment by jfmengels** [comment]
@matijs I'm sorry, I don't understand. None of these methods take functions as expressions as far as I've checked. Do you mean when you use complex expressions as the arguments?

**Comment by matijs** [comment]
@jfmengels exactly, or well, anything other than an `Identifier` or a `Literal` really.

**Comment by matijs** [comment]
I don't think this is fixable unless the arguments are `Literal`s, so… maybe half fixable. Is this worth pursuing?

**Comment by jfmengels** [comment]
Hmm, I'm not sure how to fix this either.

> I don't think this is fixable unless the arguments are Literals, so… maybe half fixable. Is this worth pursuing?

Yeah, any fix is still useful.

**Comment by matijs** [comment]
See [this comment](https://github.com/sindresorhus/eslint-plugin-unicorn/pull/67#issuecomment-256304501) in the PR for thoughts on fixing.
