### ISSUE TITLE
Rule proposal: `jsx-unique-key`

### ISSUE THREAD

**Issue by silverwind** [sindresorhus/eslint-plugin-unicorn#658]
Not sure if JSX-specific rules are in scope here, but I'd propose a rule that triggers if it detects duplicate `key` properties on the same nesting level/same array because React renders very weird things in such a scenario and it's certainly never intended. For example:

```jsx
const div = (
  <div>
    <span key="span1"/> /* error: duplicate JSX key 'span1' */
    <span key="span1"/> /* error: duplicate JSX key 'span1' */
  </div>
);

const spans = [
  <span key="span1"/>, /* error: duplicate JSX key 'span1' */
  <span key="span1"/>, /* error: duplicate JSX key 'span1' */
];
```

**Comment by sindresorhus** [comment]
Seems like this would be a better fit for https://github.com/yannickcr/eslint-plugin-react?

**Comment by silverwind** [comment]
Indeed, I will investigate, no need to "pollute" this module with React-specific rules.
