### ISSUE TITLE
Rule proposal: prefer-optional-catch-binding

### ISSUE THREAD

**Issue by fisker** [sindresorhus/eslint-plugin-unicorn#670]
There is  already a  proposal in  eslint  project, but not  accepted there, I'd like to have it here .

Orignal proposal: https://github.com/eslint/eslint/issues/10434

Autofix for no-unused-vars "caughtErrors: all" is  also rejected  https://github.com/eslint/eslint/issues/11640

**Comment by sindresorhus** [comment]
Accepted
