### ISSUE TITLE
`escape-case` only catches first escape sequence in string

### ISSUE THREAD

**Issue by bmish** [sindresorhus/eslint-plugin-unicorn#677]
I'm seeing [escape-case](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/master/docs/rules/escape-case.md) only catch and autofix/uppercase the first escape sequence character.

Before: `const x = '\uff10\uff11'`
After: `const x = '\uFF10\uff11'`

**Comment by fisker** [comment]
This rule only fix one character once, with `--fix` you'll get all fixed.

**Comment by bmish** [comment]
I'm a bit unsure what you mean? I did use `eslint --fix` but only the first escape sequence gets fixed.

**Comment by fisker** [comment]
Right, I broke it in https://github.com/sindresorhus/eslint-plugin-unicorn/pull/534

**Comment by fisker** [comment]
Should be fixed by #678
