### ISSUE TITLE
consistent-function-scoping: option to exclude IIFE

### ISSUE THREAD

**Issue by kevinoid** [sindresorhus/eslint-plugin-unicorn#685]
For code intended to run in a shared global scope (e.g. client-side libraries), it is not uncommon to use an [immediately invoked function expression (IIFE)](https://en.wikipedia.org/wiki/Immediately_invoked_function_expression) to wrap parts of the code to avoid adding functions to the global scope.  This currently runs afoul of the `unicorn/consistent-function-scoping` rule:

```js
(function() {
  function onFocusChange() {
    // ...
  }
  window.addEventListener('blur', onFocusChange);
  window.addEventListener('focus', onFocusChange);
}());
```

Disabling `unicorn/consistent-function-scoping` for each function in the IIFE can be tedious, and disabling it for the entire IIFE would miss potential issues in nested functions.  Is there any chance you might consider an option to not warn about moving functions out of an IIFE?

Thanks,
Kevin

**Comment by sindresorhus** [comment]
I think it would be better to just disable the rule for such files. This is only really a legacy problem as you can use `<script type="module"></script>` these days.

**Comment by kevinoid** [comment]
> I think it would be better to just disable the rule for such files.

Sure.  Of course that also misses out on the benefits of enforcing the rule.

> This is only really a legacy problem as you can use `<script type="module"></script>` these days.

Agreed.  I look forward to the day I don't have to work with legacy code, support legacy engines (browser and non-browser), or run code in environments/scopes I don't control, but I'm afraid that's a ways off for me.

Feel free to prioritize/ignore/close however you think is appropriate, or wait for more thumbs-up to judge interest.

**Comment by fisker** [comment]
I think this a reasonable request.
