### ISSUE TITLE
`prefer-spread` incompatible with DOM APIs (and non-iterables)

### ISSUE THREAD

**Issue by buschtoens** [sindresorhus/eslint-plugin-unicorn#687]
Quoting https://github.com/sindresorhus/eslint-plugin-unicorn/issues/120#issuecomment-615220593:

`unicorn/prefer-spread` is enabled by default as an `error` when extending from  `unicorn:recommended`. I found a quite annoying edge-case, due to:

> `Array.from` works on Array-likes while `...` only works on iterables.

It is true that:

> Array-like is IMHO just a legacy quirk. Iterables is a better way to define things that can be iterated.

However, all DOM APIs (to my knowledge) don't implement the `[Symbol.iterator]` protocol.

```ts
// This works
for (const element of Array.from(document.querySelectorAll('.foo'))) {
  console.log(element);
}

// This doesn't
for (const element of [...document.querySelectorAll('.foo')]) {
  console.log(element);
}
```

I've enabled ESLint auto-fixing in my editor and more often than I'd like to admit I trolled myself with this pretty hard.

I'll probably just demote the rule to be a warning, because I don't want to monkey-patch the `[Symbol.iterator]` protocol into the DOM API, even though that'd be even better, since then you could just do:

```ts
for (const element of document.querySelectorAll('.foo')) {
  console.log(element);
}
```

I would recommend to make this rule a warning in `unicorn:recommended` as well, to avoid this foot-gun.

**Comment by buschtoens** [comment]
FWIW demoting to `warn` doesn't help. At least with [vscode-eslint](https://github.com/microsoft/vscode-eslint) the auto-fix is still active. :(

**Comment by fisker** [comment]
Yes, warnings with `--fix` still applies.

**Comment by fregante** [comment]
> However, all DOM APIs (to my knowledge) don't implement the `[Symbol.iterator]` protocol.

Incorrect. Only in Edge 15- NodeList _isn't_ an iterator. `[...document.querySelectorAll()]` has worked in all browsers for years.

I think that the problem with `prefer-spread` currently is that is assumes that `Array.from` and `...` are equivalent.

**Comment by buschtoens** [comment]
Ooooh, nice! Then it must only be my `tsconfig.json` `lib` that is missing it.

**Comment by buschtoens** [comment]
From my POV this issue can be closed, but I also agree that there is an important difference between `Array.from()` and `...`. Would be great, if this rule's auto-fixing could be disabled, so you can still use it as a warning and mental note.

**Comment by fregante** [comment]
Auto-fixing is still desirable, but I wish it only acted when the item was actually iterable, and not just Object-like, as I pointed out a few years ago https://github.com/sindresorhus/eslint-plugin-unicorn/issues/120#issuecomment-386815139

**Comment by fisker** [comment]
We can keep this open, because people still use something like [`HTMLCollection`](https://wiki.developer.mozilla.org/en-US/docs/Web/API/HTMLCollection) which can't fix

**Comment by JoaoGuedes** [comment]
> > However, all DOM APIs (to my knowledge) don't implement the `[Symbol.iterator]` protocol.
> 
> Incorrect. **Only in Edge 15-** NodeList isn't an iterator. `[...document.querySelectorAll()]` has worked in all browsers for years (Edge 16 [added it late 2017](http://web.archive.org/web/20171204155312/https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/suggestions/15898300-iterable-nodelists))
>

This problem happened to me in Edge 17.17314 and caused the app I work on to crash.

**Comment by fregante** [comment]
@JoaoGuedes I don't think so. I just tested it and it works

### Edge 17 ✅

<img width="513" alt="" src="https://user-images.githubusercontent.com/1402241/80630102-012f8980-8a54-11ea-9b91-c2fe5945ed27.png">

### Edge 16 ✅

<img width="901" alt="" src="https://user-images.githubusercontent.com/1402241/80630285-4489f800-8a54-11ea-9926-7a56f4067446.png">


### Edge 15 ❌ 

<img width="914" alt="" src="https://user-images.githubusercontent.com/1402241/80630523-a64a6200-8a54-11ea-9392-f9fcba00cee9.png">

**Comment by JoaoGuedes** [comment]
it doesn't happen on a `NodeList` but it happens on `HTMLCollection`, which is still part of the DOM API.

**Comment by fregante** [comment]
> it happens on `HTMLCollection`

Indeed, Edge 17

<img width="235" alt="" src="https://user-images.githubusercontent.com/1402241/80636990-92a3f900-8a5e-11ea-8c67-0e01853dbe63.png">

**Comment by sindresorhus** [comment]
`[...document.body.children]` works in all modern browsers now, including the latest version of Edge.

https://stackoverflow.com/a/31574921/64949

---

Closing as this plugin only cares about modern browsers. If you need support for older browser you can simply disable the rule.

**Comment by tjx666** [comment]
In fact, I think the readability of `Array.from` is better than spread operation.
