### ISSUE TITLE
Definition for rule 'unicorn/no-null' was not found. (unicorn/no-null)

### ISSUE THREAD

**Issue by robinloeffel** [sindresorhus/eslint-plugin-unicorn#688]
Adding `unicorn/no-null: "error"` to your ESLint config makes it throw the following error:
> `Definition for rule 'unicorn/no-null' was not found (unicorn/no-null)`

I'm on `eslint@^6.8.0` and `eslint-plugin-unicorn@^18.0.1`. You can check out https://github.com/robinloeffel/eslint-config-sweet/blob/master/config.json#L198.

**Comment by fisker** [comment]
`no-null` rule is not included in `v18.0.1`.

**Comment by robinloeffel** [comment]
Oh. So how can I make use of this rule?

**Comment by fisker** [comment]
Since the rule is already merged, you can use `yarn add sindresorhus/eslint-plugin-unicorn` to install from github, or wait for a new version.

**Comment by sindresorhus** [comment]
Like most projects on GitHub, `master` is the development branch. When using a project, you need to look at the docs for the version you're using: https://github.com/sindresorhus/eslint-plugin-unicorn/tree/6f11ba1f3753d7138ac8489df97fe363af24cec6
