### ISSUE TITLE
definition for rule 'unicorn/consistent-function-scoping' was not found  unicorn/consistent-function-scoping

### ISSUE THREAD

**Issue by zilahir** [sindresorhus/eslint-plugin-unicorn#690]
This issue is present both underű"eslint-plugin-unicorn": "^17.1.0"` an `"eslint-plugin-unicorn": "^18.0.1"`. It seems like it's not a version issue since this rule exists for a while, though I would like to turn it for in a specific case. 

Any idea how to solve this?

Thanks

**Comment by zilahir** [comment]
the rule's file is present at: `./node_modules/eslint-plugin-unicorn/rules ` so that can't be the problem here.

**Comment by fisker** [comment]
Does [this](https://github.com/sindresorhus/eslint-plugin-unicorn/issues/583#issuecomment-596269827) help?

**Comment by zilahir** [comment]
hah, weird, but yes, it did! thanks!

**Comment by zilahir** [comment]
nope, too soon. 

it's still happening. the weird thing, that this is a different project, and the error is for different rules. :D

![image](https://user-images.githubusercontent.com/6687149/80825011-3bca2b00-8be8-11ea-8d27-ca515ff1dd1f.png)

**Comment by fisker** [comment]
You'll have to find the wrong version of `eslint-plugin-unicorn` yourself, we can't really help.

**Comment by zilahir** [comment]
@fisker i just managed to figure it out. The problem was that my own linter configuration was extended by default the unicorn, even though it was not within it's peer dependencies. So it was all my mistake.

I deleted my comment, thought i will be faster than you are, but you were quicker. Anyway, the problem was on my side.

Thank you for your time! :)
