### ISSUE TITLE
`prefer-set-has` is little bit annoying

### ISSUE THREAD

**Issue by fisker** [sindresorhus/eslint-plugin-unicorn#696]
When the `.includes()` check not in a `for` , `while` or used by another function seems not really necessary to use a `Set`.

**Comment by sindresorhus** [comment]
Do you have any examples of where it's annoying?

**Comment by fisker** [comment]
I tried to upgrade  `eslint-plugin-unicorn` to v19 for `prettier`, 4 cases in that codebase is reported, but 3 of them are similar

https://github.com/prettier/prettier/blob/99b0fae7e1c0a8ead2b56c3ea037489a7b82915a/src/language-css/utils.js#L31-L44

This one `.includes()` call is in a `while` loop.


---

https://github.com/prettier/prettier/blob/99b0fae7e1c0a8ead2b56c3ea037489a7b82915a/src/language-css/utils.js#L118-L126

This one should not report, I think.

**Comment by sindresorhus** [comment]
> This one should not report, I think.

👍

**Comment by fisker** [comment]
So, let's only check `.include()` is in a `do/while`, `while/do`, `for` and another `function`, what do you think?

**Comment by sindresorhus** [comment]
Sounds good
