### ISSUE TITLE
prefer-string-slice makes a breaking change for negative lengths

### ISSUE THREAD

**Issue by sherlock1982** [sindresorhus/eslint-plugin-unicorn#700]
Consider the following autofix:

`"Sample".substr(0, "Sample".lastIndexOf('/'))` returns empty string. 
Due to ECMA-262 "If length is a negative number, it is treated as 0."

Unicorn changes it to:
`"Sample".slice(0, "Sample".lastIndexOf('/'))` returns "Sampl".

I'm not sure if autofix shouldn't be breaking. 
But i think you need to be aware of this behavior.

UPD: I see that in other places it correctly added Math.Max for `substring` but `substr` seems broken.

**Comment by voxpelli** [comment]
Right, related change: #424 

Not sure if I have time to look at this right now, but maybe
