### ISSUE TITLE
no-fn-reference-in-iterator can be customized???

### ISSUE THREAD

**Issue by GuoSirius** [sindresorhus/eslint-plugin-unicorn#701]
```js

this.$refs.tree.filter(val)

```

This check is not passed. 

Can you customize prefixes or ignore them？

**Comment by GuoSirius** [comment]
```js
watch: {
    keywords(val) {
      this.$refs.tree.filter(val)
    }
}
```

**Comment by fisker** [comment]
What is  `prefixes` mean, and  what  exactly you want the option like,

**Comment by sindresorhus** [comment]
Closing for lack of answer by OP.

**Comment by GuoSirius** [comment]
[The prefix is just the part that precedes the dot](https://github.com/sindresorhus/eslint-plugin-unicorn/pull/699#issuecomment-751909395) @sindresorhus

**Comment by GuoSirius** [comment]
![image](https://user-images.githubusercontent.com/48358523/103251591-3b22a800-49b4-11eb-91ad-e5b0ce3bd4d0.png)
