### ISSUE TITLE
Pick a default `non-zero` option for `explicit-length-check`

### ISSUE THREAD

**Issue by EvgenyOrekhov** [sindresorhus/eslint-plugin-unicorn#702]
https://github.com/sindresorhus/eslint-plugin-unicorn/blob/f1ced468120686263a45a9993d2f02343f70c6f3/docs/rules/explicit-length-check.md#non-zero-comparisons

I suggest picking a default value for the `non-zero` option.

## not-equal

Pros:

1. `!== 0` is the inverse of `=== 0`, like "is it not empty?" and "is it empty?"
2. `!== 0` does not perform type coercion (considering that the general consensus is that implicit type coercion is bad)

Cons:

1. If `array.length` is `undefined`, `array.length !== 0` would evaluate to `true`, which is incorrect if we are asking "is it not empty?"

## greater-than

Pros:

1. If `array.length` is `undefined`, `array.length > 0` evaluates to `false`, which is "more correct" than the `!== 0` case
2. (subjective) A positive question in a condition is more readable than a negative question, like `is it populated?` for `> 0` vs `is it not empty?` for `!== 0`

Cons:

1. Performs type coercion (this actually might be good in this case, see pro # 1)

## greater-than-or-equal

Pros:

1. same as for greater-than
2. same as for greater-than

Cons:

1. same as for greater-than
2. (unconfirmed) More mentally demanding because it actually has two conditions in one expression (`greater than 1 OR equal to 1`)
3. (unconfirmed) Used less often than `!== 0` or `> 0`

I didn't perform a thorough analysis when I started using `!== 0` in my code, and now I think that actually `> 0` is a better option.

**Comment by ryaxc** [comment]
Not sure if this would be lintable but wouldn't `(Array.isArray(arr) && arr.length !== 0)` solve your first problem of `undefined`?  The `> 0` makes sense but I'm not experienced enough to know whether that type coercion could produce unintended side-effects.  Using `isArray` would seem far more accurate anyways.

**Comment by EvgenyOrekhov** [comment]
@ryaxc Your example is not polymorphic. There are other types than `Array` that could have `length`.

**Comment by sindresorhus** [comment]
I agree. I prefer `greater-than` as default.

**Comment by ryaxc** [comment]
Assuming type coercion isn't a problem, then it makes sense if we're dealing with `differentTypes.length` then `> 0` should be close enough.  
I suppose any concern I'd have would be if we were concerned about type; then I would think we should also require (or at least recommend) explicit `isArray` (or whatever) or `typeof` included as part of any `!==` usage.  
Basically, if you don't care about type, don't care about type.  If you care about it, then actually care about it.  Hopefully the lint rule which doesn't care about type won't invalidate situations when type should matter.  If a lint rule prefers greater-than but I need to be more explicit and use not-equal (especially more than a one-off instance); then we should question whether to enable the rule.  (IE: Rules for the sake of rules don't necessarily bring value.)
Note: These are general opinions; again, I have only scratched the surface with this sort of use in javascript and a bit more in python and haven't encountered an abundance of problems either way.

**Comment by papb** [comment]
@ryaxc I agree. Perhaps the following is doable?

Enforce `something.length > 0` **unless**:
* There is a preceding `Array.isArray(something) &&` check
* Or there is a preceding `typeof something === 'string' &&` check

**Comment by EvgenyOrekhov** [comment]
@sindresorhus Is this accepted? I want to try implementing it.

**Comment by sindresorhus** [comment]
Yes, this is accepted. `greater-than`.
