### ISSUE TITLE
`no-keyword-prefix`: This rule never enabled?

### ISSUE THREAD

**Issue by fisker** [sindresorhus/eslint-plugin-unicorn#714]
It is set to `off` since beginning https://github.com/sindresorhus/eslint-plugin-unicorn/blame/1f4413dbacc2d06f15826350e7eba8bd432e0de4/index.js#L37

**Comment by yakov116** [comment]
While I won't use this rule personally, I'm happy to host it here if you can commit to maintain it. I think it should be `"off"` by default in the recommended config though.

_Originally posted by @sindresorhus in https://github.com/sindresorhus/eslint-plugin-unicorn/pull/282#issuecomment-497803142_

**Comment by fisker** [comment]
@yakov116  Thanks!
