### ISSUE TITLE
Should we allow `reason` as error name?

### ISSUE THREAD

**Issue by fisker** [sindresorhus/eslint-plugin-unicorn#715]
[`catch-error-name`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/master/docs/rules/catch-error-name.md) rule only allow `error` by default.

MDN use a lot of `reason` for promise, [`Promise.prototype.catch() parameter onRejected`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/catch#Parameters) [`Promise.allSettled() Return value
`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/allSettled#Return_value)

I changed [`reason` to `rejectedError`](https://github.com/fisker/promise-synchronizer/commit/9d180ca6c9ab883125c3c26a17d95bbf1f066b18#diff-1fdf421c05c1140f6d71444ea2b27638R19) because `error` is used :)

Maybe we could allow `reason` and `fooReason` for `promise.then/catch` by default?

If this is not accept, I'm going to update my personal config to allow it with [options.ignore](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/master/docs/rules/catch-error-name.md#ignore).

**Comment by sindresorhus** [comment]
I don't really see the point of using `reason`. Yes, it's used in some technical docs, but in 99.9% cases, it's an error, so I think it's more readable to use `error` to make that clear.

**Comment by fisker** [comment]
Okay, there is `options.ignore` anyway.
