### ISSUE TITLE
`no-useless-undefined`: `undefined` removed from compare functions

### ISSUE THREAD

**Issue by fisker** [sindresorhus/eslint-plugin-unicorn#728]
```js
test('should be undefined', t => {
	t.is(foo, undefined);
})
```

```js
if (Object.is(foo, undefined)) {}
```

We are not breaking things, but removing `undefined` seems weird

In `ava`, `t.is(foo)` is also passed.

Funny thing, `Object.is(foo)` and `Object.is()` returns true.

Question: should we ignore them?

**Comment by papb** [comment]
I agree it definitely looks super weird. I would not like that in my code.

However at least it is not breaking...

**Comment by fisker** [comment]
Any function or property call has `is`/`not`/`equal`/`be`/`same`?

**Comment by fisker** [comment]
Ignore or remove auto-fix?

**Comment by papb** [comment]
I like the idea of ignoring the rule on calls named `is`, `equal`, `equals`, `isEqual` (and possibly others) if they are being called with exactly 2 parameters, I guess?

**Comment by fisker** [comment]
Can't do with `2 parameters`, possible `expect(foo).toBe(undefined)`, by name I mean contains `is` any where.

**Comment by papb** [comment]
Hmm, so 1 or 2 parameters.

And by containing `is` I assume considering camelCase separations only, right? So that we don't accidentally ignore names such as `fisker(foo, undefined)` since it contains `is`

**Comment by fisker** [comment]
That's why I propose, just remove `auto-fix`, if you really want, we still have suggestion and you can also `eslint-disable`.

**Comment by papb** [comment]
I personally prefer ignoring calls with 1 or 2 parameters whose name contain `is`, `equal`, `equals` or `be` as a whole "camelCase section".
