### ISSUE TITLE
`no-useless-undefined`: optional parameters

### ISSUE THREAD

**Issue by EvgenyOrekhov** [sindresorhus/eslint-plugin-unicorn#731]
Very often in my code I use `undefined` for highlighting optional parameters in function signatures, e. g.

```js
function f(a, b, c = undefined) {
  // ...
}
```

It makes it clear that `a` and `b` are required, and `c` is optional.

Also, declaring a default value affects the `.length` property of a function:

```js
((a, b, c) => {}).length // 3
((a, b, c = undefined) => {}).length // 2
```

which can alter the behavior of the code in some cases (for example when using Ramda's [`curry()`](https://ramdajs.com/docs/#curry)).

Also, I use the same approach when using parameter destructuring:

```js
function f({ a, b, c = undefined }) {
  // ...
}
```

which also makes it clear which properties are required and which ones are optional.

I know that I can use `// eslint-disable` directives for those cases, but I use this pattern pretty often, and I would like to have an option for the `no-useless-undefined` rule to allow those cases.

**Comment by snowteamer** [comment]
I also had a short conversation with **fisker** on this topic in https://github.com/sindresorhus/eslint-plugin-unicorn/issues/683. Then I decided to try and use `/* optional */` inline comments to replace the occurences of `= undefined` in my codebase, but I am still in the process and have not enough hindsight yet to list the possible downsides.

Anyway, I wouldn't disagree if this case was not considered definetely useless and exempted from the rule, or if it was controlled by an option as you suggested.

However, many Unicorn rules don't have any optional parameter for simplicity, which is also valuable... so I don't have a definitive opinion on this question.

**Comment by sindresorhus** [comment]
I’m 👎 on adding an option for this. We cannot add options for every obscure use-case. In this case, there are other ways to indicate it’s optional. Either with a comment or using TypeScript.
