### ISSUE TITLE
Rule proposal: `prefer-regexp-test`

### ISSUE THREAD

**Issue by brettz9** [sindresorhus/eslint-plugin-unicorn#732]
Prefer `RegExp.prototype.test` over `String.prototype.match` for truthiness checks of (inline) regexes.

- [Performance](https://stackoverflow.com/a/10940138/271577)
- More semantically clear at a glance how the result is expected to be used. Admittedly, newcomers may think "match" sounds more like it would be a truthy check than "test", but at least for those familiar with the language details, it is more confined and clear as to intent.

## Fail

```js
if (str.match(/hasTheMagic/)) {
}
```

```js
const func = str.match(/hasTheMagic/) ? process(str) : null;
```

## Pass

```js
if ((/hasTheMagic/).test(str)) {
}
```

```js
const func = (/hasTheMagic/).test(str) ? process(str) : null;
```

```js
const matches = str.match(/hasTheMagic/);
```

(The following passes given that changing to `test` could be problematic since it could contain a global regex and such expressions passed to `test` (as with `exec`) behave non-deterministically due to `lastIndex` incrementing)
```js
if (str.match(hasTheMagicRegex)) {
}
```

Apologies this is not a "funded" request with PR planned--just if you felt it fit.

**Comment by sindresorhus** [comment]
We discussed this recently: https://github.com/sindresorhus/eslint-plugin-unicorn/issues/713#issuecomment-625990579

Should also handle `exec`.

I think it should be named `prefer-regexp-test`.

**Comment by brettz9** [comment]
Yeah, "no-match-for-truthiness" sounds a bit like an old comic book line :-)

**Comment by sindresorhus** [comment]
This is accepted.

**Comment by fisker** [comment]
I want add some failed cases

```js
foo = !!string.match(/regex/)
```

```js
foo = !!/regex/.exec(string)
```

```js
foo = Boolean(string.match(/regex/))
```

```js
foo = Boolean(/regex/.exec(string))
```

**Comment by ElvenMonky** [comment]
Well the problem is that RegExp.test is not stateless when used with g flag. So every time you want to reuse same RegExp for both RegExp.test and String.match calls (and also want to skip including matching groups), you are in trouble.

**Comment by ElvenMonky** [comment]
https://stackoverflow.com/questions/1520800/why-does-a-regexp-with-global-flag-give-wrong-results
