### ISSUE TITLE
prefer-number-properties: apply to isNaN() and isFinite() only

### ISSUE THREAD

**Issue by teppeis** [sindresorhus/eslint-plugin-unicorn#734]
In order to minimize lint errors, I want an option to apply [prefer-number-properties](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/master/docs/rules/prefer-number-properties.md) 
 only to `isNaN()` and `isFinite()`.

- Exactry same
  - `Number.parseInt()` and `parseInt()`
  - `Number.parseFloat()` and `parseFloat()`
  - `Number.NaN` and `NaN`
- Slightly different (`Number.*` is preferable)
  - `Number.isNaN()` and `isNaN()`
  - `Number.isFinite()` and `isFinite()`

**Comment by papb** [comment]
Wouldn't it be better to just fix these errors? What is essentially different between `isNaN` and `parseInt` that makes you want them treated differently?

**Comment by teppeis** [comment]
@papb Because there is no strong reason to change `parseInt` to `Number.parseInt`.

**Comment by fisker** [comment]
We already offered suggestion, if you want fix them, just click to apply, we won't auto fix them.

**Comment by sindresorhus** [comment]
> Because there is no strong reason to change parseInt to Number.parseInt.

Consistency and less globals.

**Comment by teppeis** [comment]
ok, thanks.
