### ISSUE TITLE
Rule proposal: disabling reason

### ISSUE THREAD

**Issue by dartess** [sindresorhus/eslint-plugin-unicorn#740]
for eslint 7:

> Configuration comments can include descriptions to explain why the comment is necessary. The description must occur after the configuration and is separated from the configuration by two or more consecutive - characters. For example:

> // eslint-disable-next-line no-console -- Here's a description about why this configuration is necessary.

It would be great to be able to oblige the developer to write a comment after disabling eslint

**Comment by sindresorhus** [comment]
This seems like a rule that should be in ESLint itself. Can you propose it over at https://github.com/eslint/eslint first? If they decline it, we can continue it here.

**Comment by dartess** [comment]
Sure!
(It seemed to me that such a rule in the main repository would look very hardcore. But i will try.)

**Comment by dartess** [comment]
I was redirected to eslint-plugin-eslint-comments plugin. It looks logical. Opened the issue there.

Thanks, I think this issue is better to close for now.

Just in case links: https://github.com/mysticatea/eslint-plugin-eslint-comments/issues/47

**Comment by dartess** [comment]
upd: yes, it's almost done in that repo.
thanks for the help!
