### ISSUE TITLE
`no-for-loop` rule could use smarter element variable name in autofix

### ISSUE THREAD

**Issue by bmish** [sindresorhus/eslint-plugin-unicorn#743]
If the loop is iterating an array with a plural name (such as `plugins`), the generated element variable in the autofix could use the singular version of the array name (`plugin`), instead of just the generic name `element`.

Original code:

```js
for (let i = 0; i < plugins.length; i++) {
  console.log(plugins[i]);
}
```

After autofix:

```js
for (const element of plugins) {
  console.log(element);
}
```

Desired autofix:

```js
for (const plugin of plugins) {
  console.log(plugin);
}
```

**Comment by fisker** [comment]
PR welcome.

**Comment by snowteamer** [comment]
It would be really nice, however please keep in mind that lemmatization of arbitrary plural forms is not easy and usually requires an external dependency, which we probably do not want.

Still, we could try handling most cases with a few rules and a few mappings between known irregular plurals and their singular form, falling back to the default `element` replacement if we are not sure.

However, the autofix could introduce misspelled variable names if applied without enough checking upfront, which I think is very important to avoid.
