### ISSUE TITLE
`unicorn/better-regex` produces unreadable regex

### ISSUE THREAD

**Issue by fregante** [sindresorhus/eslint-plugin-unicorn#769]
The rule is useful in some situations: https://github.com/xojs/xo/issues/227

But counterproductive in others: https://github.com/DmitrySoshnikov/regexp-tree/issues/208

> ```js
> /http:\/\/[^/]+\/pull\/commits/gi
> ```
> 
> 
> 👆 Readable
> ```js
> /ht{2}p:\/{2}[^/]+\/pul{2}\/com{2}its/gi
> ```
> 
> 
> 👆 Nonsense, longer

Can this specific `regexp-tree` transform be disabled?

**Comment by sindresorhus** [comment]
I agree. We should disable that transform.

**Comment by Nimisha94** [comment]
Hi! I would like to give this a shot.

**Comment by fisker** [comment]
This  might  need fix  in `regexp-tree`

**Comment by Nimisha94** [comment]
I think @fregante has opened an [issue](https://github.com/DmitrySoshnikov/regexp-tree/issues/208) in `regexp-tree`. I'm assuming this issue is to disable `regexp-tree` [here](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/5bf60cc39801c5426152717f2e027517f11268ab/rules/better-regex.js#L31). Lmk if this is not the case.

**Comment by fisker** [comment]
You can try.

**Comment by hrithiksh101** [comment]
Is the issue resolved , i would also like to work on the problem

**Comment by Nimisha94** [comment]
@hrithiksh101 I didn't get a chance to work on this issue. You can go ahead and give it a shot. Thanks

**Comment by brettz9** [comment]
With `charClassToSingleChar` being the item to add to the blacklist, what Unicorn option name is desired?

**Comment by fisker** [comment]
`combineCharacterClasses`?

**Comment by brettz9** [comment]
Sorry, I really confused things.

This should really be about disabling repeated patterns (not character classes), so I have changed the name and code accordingly. However, the transform in `regexp-tree` no longer applies with just 2 or 3 anyways. It seems to take 4 repeating items to trigger the rule, so I'm not sure the original issue reported here is as of much concern. But in any case, if the option is desired, I've amended the PR in a way that I think makes sense and  is passing tests so far (finishing integration now).

**Comment by fisker** [comment]
I think it's because `http` is shorter than `ht{2}p`

**Comment by fisker** [comment]
Can you change your PR, only add test for this case, and we can close.

**Comment by brettz9** [comment]
Yeah, it was a reasonable change. But if y'all still want the option, I think the PR now should work (and I see it passed all tests).

**Comment by fisker** [comment]
Let's not add unwanted options, if someone run into other issue, we'll discuss. Unless you find something unreadable.

**Comment by fisker** [comment]
On https://npm.runkit.com/regexp-tree

```js
var regexpTree = require("regexp-tree")
regexpTree.optimize(/http:\/\/[^/]+\/pull\/commits/gi).toRegExp()
```

Still 

```js
/ht{2}p:\/{2}[^\/]+\/pul{2}\/com{2}its/gi
```

**Comment by brettz9** [comment]
Ok, but we're using `toString()` which doesn't give that.

**Comment by fisker** [comment]
Haha, you are write, so strange.

**Comment by brettz9** [comment]
Since it is still currently working, I'm pushing now with the test in the OP (showing it is not optimized regardless). I've kept the old branch if you decide you do want it after all. (Personally, I'd prefer an `advanced` option which allows passing in whatever blacklist or whitelist one wants.)

**Comment by fisker** [comment]
I like that, but it's rejected in previous discussion.
