### ISSUE TITLE
NPM package out of date

### ISSUE THREAD

**Issue by RobertWHurst** [sindresorhus/eslint-plugin-unicorn#77]
Hi @sindresorhus! Just noticed that the NPM package does not contain all of the rules present in the repo at the time of writing this. Is it possible to slate a new release with the new features?

Thanks for putting this together. It's a great little module 🍻

**Comment by sindresorhus** [comment]
We'll do a release when some more rules land. It has to be a major release, so not to keen on doing releases too often.

**Comment by RobertWHurst** [comment]
@sindresorhus Okie dokie. Thanks!

**Comment by pastelsky** [comment]
@sindresorhus any plans of updating the npm package, now that this repo has 2-3x more rules than the latest npm package?

**Comment by sindresorhus** [comment]
Yes, soon.
