### ISSUE TITLE
Unsafe replacement with .startsWith() when doing xo --fix

### ISSUE THREAD

**Issue by timlesallen** [sindresorhus/eslint-plugin-unicorn#782]
`/^NN|VB/.test(partOfSpeech`) →  `partOfSpeech.startsWith('NN|VB')`

This actually broke my code. :)

I hope I'm filing this in the right place.  Or should it rather be under `xo`?

**Comment by fisker** [comment]
This is the right place.

**Comment by fisker** [comment]
Would you like to send a PR fix this? This is easy one, just add `|` to https://github.com/sindresorhus/eslint-plugin-unicorn/blob/459408580b953cfd9940d4d2a0df0f397f537739/rules/prefer-starts-ends-with.js#L14

**Comment by timlesallen** [comment]
@fisker Ok will do.

**Comment by timlesallen** [comment]
@fisker There you go :) https://github.com/sindresorhus/eslint-plugin-unicorn/pull/783
