### ISSUE TITLE
Allow initial underscore in `filename-case` rule

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/eslint-plugin-unicorn#79]
Reasoning: https://github.com/sindresorhus/xo/issues/172

I think it makes sense. Many ecosystems use `_` to mean a helper. We should just strip it before comparing the name.

**Comment by jfmengels** [comment]
So should we allow it only at the start of the file name (what I'd probably go for), or also at the end?

**Comment by sindresorhus** [comment]
Start only.

**Comment by SamVerschueren** [comment]
Might be missing something here, but isn't it already the case? https://github.com/sindresorhus/eslint-plugin-unicorn/blob/master/test/filename-case.js#L63

**Comment by sindresorhus** [comment]
Yes, was fixed in https://github.com/sindresorhus/eslint-plugin-unicorn/commit/87663a4f0db07e093adecb15f08db7f32d652de3.
