### ISSUE TITLE
better-regex and smart quotes

### ISSUE THREAD

**Issue by klimashkin** [sindresorhus/eslint-plugin-unicorn#791]
Hi!

`better-regex` wants to replace 
`text.replace(/[\u201C\u201D\u201E\u201F\u2033\u2036]/g, '"'); // Replace smart quotes`
with
`text.replace(/[\u201C-\u201F\u2033\u2036]/g, '"'); // Replace smart quotes`

But I don't think that is equivalent. Is it?

**Comment by fisker** [comment]
```js
'\u201C\u201D\u201E\u201F\u2033\u2036'.replace(/[\u201C\u201D\u201E\u201F\u2033\u2036]/g, '"');
""""""""
'\u201C\u201D\u201E\u201F\u2033\u2036'.replace(/[\u201C-\u201F\u2033\u2036]/g, '"');
""""""""
```
