### ISSUE TITLE
ParentNode.append breaks on IE

### ISSUE THREAD

**Issue by kahoot-karl** [sindresorhus/eslint-plugin-unicorn#800]
The rule correcting appendChild to append breaks on Internet explorer:

https://developer.mozilla.org/es/docs/Web/API/ParentNode/append

As far as I know, there's no good polyfilling options

**Comment by sindresorhus** [comment]
You can turn off the rule if you need to target IE.

**Comment by futpib** [comment]
https://github.com/msn0/mdn-polyfills may be a good polyfilling option
