### ISSUE TITLE
change import-index rule

### ISSUE THREAD

**Issue by jimmywarting** [sindresorhus/eslint-plugin-unicorn#802]
> Enforce importing index files with .

I don't support this rule. it's a foot gun when you wish to convert your code to es6 modules that have no support for extensionless searching. if anything it should enforce `const m = require('./index.js')`

https://github.com/nodejs/modules/blob/master/doc/archive/plan-for-new-modules-implementation.md

**Comment by sindresorhus** [comment]
You are using it for something it was not intended. It was made to enforce good CommonJS practices. That being said, I'm happy to make it possible to enforce the name too.

**Comment by jimmywarting** [comment]
yea, i would like that. I'm not in charge of using import or CommonJS. It's a package i'm helping out with.
i would like to use import but that is a major undertaking. i just wanted to use `./index.js` so that the resolver don't have to guess and make it easier to later change to import syntax if they ever go that route.

just came here since the linter complained about using it.

**Comment by shrpne** [comment]
+1 here, full path imports are per ES modules spec.
So this rule should not be included in `unicorn/recommended`

**Comment by sindresorhus** [comment]
This rule will no longer be in the recommended preset in the next version.

As for enforcing `index.js`, use the `eslint-plugin-import` plugin: https://github.com/xojs/xo/blob/5f02a3ea69e496f7e145a9c6ea9960d1df85886c/config/plugins.js#L183-L194
