### ISSUE TITLE
WINDOWS Error: EPERM: operation not permitted, open

### ISSUE THREAD

**Issue by mmakrzem** [sindresorhus/eslint-plugin-unicorn#803]
I updated from v20.1.0 to v21.0.0 and now when I try to lint my source code, I'm getting the following error. ESLint no longer works:

    Oops! Something went wrong! :(
    
    ESLint: 7.5.0
    
    Error: EPERM: operation not permitted, open 'D:\mwc\src\app\AppPlot.ts'
    npm ERR! code ELIFECYCLE
    npm ERR! errno 2
    npm ERR! @marek/mwc@2020.1.3 lint: `eslint -c .eslintrc.js --fix --ext .ts,.tsx ./src`
    npm ERR! Exit status 2
    npm ERR!
    npm ERR! Failed at the @marek/mwc@2020.1.3 lint script.
    npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
    
    npm ERR! A complete log of this run can be found in:
    npm ERR!     C:\Users\Marek\AppData\Roaming\npm-cache\_logs\2020-07-31T16_50_04_330Z-debug.log

**Comment by sindresorhus** [comment]
Please include the full error (with stack trace).

**Comment by mmakrzem** [comment]
> Please include the full error (with stack trace).

0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Marek\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'lint'
1 verbose cli ]
2 info using npm@6.14.6
3 info using node@v12.18.1
4 verbose run-script [ 'prelint', 'lint', 'postlint' ]
5 info lifecycle @marek/mwc@2020.1.3~prelint: @marek/mwc@2020.1.3
6 info lifecycle @marek/mwc@2020.1.3~lint: @marek/mwc@2020.1.3
7 verbose lifecycle @marek/mwc@2020.1.3~lint: unsafe-perm in lifecycle true
8 verbose lifecycle @marek/mwc@2020.1.3~lint: PATH: C:\Users\Marek\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\mwc\node_modules\.bin;C:\TS3D\HOOPS_Exchange_Publish_2020_U1\bin\win64;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;c:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\;c:\Program Files\Microsoft SQL Server\100\Tools\Binn\;c:\Program Files\Microsoft SQL Server\100\DTS\Binn\;C:\Program Files\ffmpeg\bin;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Microsoft VS Code Insiders\bin;C:\Program Files\Perforce\;C:\Program Files\Git\cmd;C:\Program Files (x86)\Autodesk\Backburner\;C:\Program Files\nodejs\;C:\Program Files\dotnet\;C:\Users\Marek\AppData\Local\Programs\Python\Python36-32\Scripts\;C:\Users\Marek\AppData\Local\Programs\Python\Python36-32\;C:\Users\Marek\AppData\Local\Microsoft\WindowsApps;C:\Users\Marek\.windows-build-tools\python27\;C:\Users\Marek\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\Users\Marek\AppData\Roaming\npm\node_modules\windows-build-tools\node_modules\.bin;C:\Users\Marek\AppData\Roaming\npm\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Perforce\DVCS\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Git\cmd;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;c:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\;c:\Program Files\Microsoft SQL Server\100\Tools\Binn\;c:\Program Files\Microsoft SQL Server\100\DTS\Binn\;C:\Program Files\Perforce;C:\Program Files\ffmpeg\bin;C:\Program Files\nodejs\;C:\Program Files\Microsoft VS Code Insiders\bin;C:\Users\Marek\AppData\Local\Microsoft\WindowsApps;C:\Users\Marek\AppData\Local\Google\Cloud SDK\google-cloud-sdk\bin;C:\Users\Marek\AppData\Roaming\npm;C:\Users\Marek\.dotnet\tools
9 verbose lifecycle @marek/mwc@2020.1.3~lint: CWD: D:\mwc
10 silly lifecycle @marek/mwc@2020.1.3~lint: Args: [ '/d /s /c', 'eslint -c .eslintrc.js --fix --ext .ts,.tsx ./src' ]
11 silly lifecycle @marek/mwc@2020.1.3~lint: Returned: code: 2  signal: null
12 info lifecycle @marek/mwc@2020.1.3~lint: Failed to exec lint script
13 verbose stack Error: @marek/mwc@2020.1.3 lint: `eslint -c .eslintrc.js --fix --ext .ts,.tsx ./src`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\Marek\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\Marek\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid @marek/mwc@2020.1.3
15 verbose cwd D:\mwc
16 verbose Windows_NT 10.0.18362
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Marek\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "lint"
18 verbose node v12.18.1
19 verbose npm  v6.14.6
20 error code ELIFECYCLE
21 error errno 2
22 error @marek/mwc@2020.1.3 lint: `eslint -c .eslintrc.js --fix --ext .ts,.tsx ./src`
22 error Exit status 2
23 error Failed at the @marek/mwc@2020.1.3 lint script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]

**Comment by mmakrzem** [comment]
@sindresorhus  let me know if there is any other thing that you need from me.

**Comment by sindresorhus** [comment]
There's still not enough information for us to look into this. I suggest doing some debugging yourself. Like trying to disable rules one by one until you can narrow it down. It's also possible this is not a problem with this plugin, but rather upgrading this plugin, caused other upgrades as a side-effect, which is the culprit.
