### ISSUE TITLE
Rule proposal: `no-native-addon-dependencies`

### ISSUE THREAD

**Issue by silverwind** [sindresorhus/eslint-plugin-unicorn#808]
It is often desirable for portability and general stability to not have any native addons in the direct or indirect  dependencies. If these cases could be detected reliably and fast, a rule could be created.

## Fail
```js
import 'node-sass'; /* error: module `node-sass` contains native addons */
import 'gulp-sass'; /* error: dependency `node-sass` of `gulp-sass` contains native addons */
```

## Pass
```js
import 'sass';
import 'gulp-dart-sass';
```

**Comment by papb** [comment]
Fantastic idea! How about `no-platform-specific-imports`?

**Comment by silverwind** [comment]
I think I still prefer the name `no-native-import`. For example, I have [a module](https://github.com/silverwind/default-gateway) that has platform-specific functionality while still being pure JS.

**Comment by papb** [comment]
@silverwind ah, yes, of course. You're right :facepalm: actually now that you say it, I see it's clearly not unusual for cross-platform modules require platform specific code (so that they accomodate for each platform). Sorry for the noise :sweat_smile:

**Comment by sindresorhus** [comment]
I would prefer `no-native-addon-dependencies`. The "import" word would not work as it's about indirect dependencies too.

**Comment by silverwind** [comment]
Terminology of "addons" seems good. It's also what [Node uses in its docs](https://nodejs.org/api/addons.html).

**Comment by silverwind** [comment]
I do have to raise one argument against the rule: Some dependencies may never be imported and a linter rule would miss addons in those. For such cases a `find node_modules -type f -name "*.node"` would be more reliable.

**Comment by fisker** [comment]
This?

https://eslint.org/docs/rules/no-restricted-imports

**Comment by silverwind** [comment]
@fisker that's a simple denylist-based approach, the proposed rule would be more automatic in detection of native addons.

I actually think that unless there is a surefire way to detect native addons (`require.resolve` is not suitable because many modules have JS wrappers), the implementation would be too tricky and the proposal should probably be denied.

**Comment by sindresorhus** [comment]
I think this rule would be a better fit for https://github.com/mysticatea/eslint-plugin-node. I would recommend opening an issue there. The maintainer there might have some good idea on how to solve this.
