### ISSUE TITLE
number-literal-case breaks with bigints

### ISSUE THREAD

**Issue by hayes** [sindresorhus/eslint-plugin-unicorn#812]
There isn't a good way to write hex big int literals with this rule enabled.

`0x7Fn` is marked as an error presumably because of the lower case `n`.

**Comment by fisker** [comment]
It was  fixed long time ago #490, are you using old version?

**Comment by fisker** [comment]
Ah, maybe you are using a old version of Node.js? Maybe there is actually something wrong in that rule.

Can you share what version of Node.js and what parser  you are using? That can help

**Comment by hayes** [comment]
Sorry for the delayed response. and thanks for the quick reply @fisker!

I dug into it a bit more, and I am seeing the same thing with multiple versions of node (14.9.0,  12.18.3).  All my direct dependencies are up to date (but possible some nested dependencies are not), but there is only one version of eslint-plugin-unicorn and it is 21.0.0.

Looking at the actual rule, the issue seems to be that for BigInts when it grabs the bigint value for a bigint hex literal here https://github.com/sindresorhus/eslint-plugin-unicorn/blob/master/rules/number-literal-case.js#L16, it is a base 10 string rather than a hex string.  (eg. `0x7fn` will be `'127'`) which means the "fixed" version it compares against will be `127n`.

**Comment by fisker** [comment]
Located the problem, broken on `@typescript-eslint/parser`, is this the parser you use?

**Comment by hayes** [comment]
yup, it is!

**Comment by fisker** [comment]
Fixed in #815
