### ISSUE TITLE
Rule proposal: Collapsible if-statements

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/eslint-plugin-unicorn#819]
The rule should identify nested if-statements that can be combined into one.

Would be useful if the rule could be auto-fixable.

>
> Instead of:
> 
> ```ts
> if (foo) {
>     if (bar) {
>         // ...
>     }
> }
> ```
> 
> Prefer:
> 
> ```ts
> if (foo && bar) {
>     // ...
> }
> ```

From: https://github.com/typescript-eslint/typescript-eslint/issues/279

**Comment by sindresorhus** [comment]
Accepted. PR welcome.

**Comment by fisker** [comment]
Rule name? `collapse-if`?

**Comment by fregante** [comment]
This can only work if it’s not followed by `else`

**Comment by fisker** [comment]
I think [this comment](https://github.com/typescript-eslint/typescript-eslint/issues/279#issuecomment-463791071) make sense, let's name it as `no-lonely-if` too, hope it will merge to core someday.

**Comment by fregante** [comment]
Hasn’t eslint stopped adding rules to core?

**Comment by fisker** [comment]
No, but @sindresorhus made this proposal here. I guess he want have this rule in `unicorn` first?

**Comment by fisker** [comment]
Anyway, the rule is ready https://github.com/sindresorhus/eslint-plugin-unicorn/pull/936

**Comment by fregante** [comment]
According to their [rule suggestion issue template](https://github.com/eslint/eslint/issues/new?assignees=&labels=triage%2C+rule%2C+feature&template=NEW_RULE.md&title=):

> New rules must be related to ECMAScript features added within the last 12 months

But I suppose this rule could still be accepted as a _modification_ of the existing one.

**Comment by sindresorhus** [comment]
> No, but @sindresorhus made this proposal here. I guess he want have this rule in unicorn first?

Yeah, I have given up bothering. The process there is way too slow and they reject almost everything anyway.
