### ISSUE TITLE
Ignore index.ts on "filename-case" by default

### ISSUE THREAD

**Issue by ash-r1** [sindresorhus/eslint-plugin-unicorn#824]
As the document said, `index.js` is ignored by the `filename-case` rule, how about `index.ts` (**.TS** instead of **.JS**)?

**Comment by sindresorhus** [comment]
Sure. `.tsx` too.

**Comment by fisker** [comment]
`inde.vue` too

**Comment by fisker** [comment]
`.cjs` and `.mjs` too?
