### ISSUE TITLE
Add  `fn` > `function_` in `prevent-abbreviations`

### ISSUE THREAD

**Issue by fregante** [sindresorhus/eslint-plugin-unicorn#831]
I thought fn->function_ existed at some point?

https://github.com/sindresorhus/eslint-plugin-unicorn/blob/a0b4abad2011537aacef8a25fd950c468a8a1120/rules/prevent-abbreviations.js

Also what about `i > index`? 😏

**Comment by fisker** [comment]
👍 for `fn->function` and `func-function`,



`i > index` is metioned in the original proposal

https://github.com/sindresorhus/eslint-plugin-unicorn/issues/169

**Comment by sindresorhus** [comment]
> i > index is metioned in the original proposal #169

Let's just do it. It's easy to disable if not wanted.

**Comment by fregante** [comment]
I was only half joking 😁 how would j be handled in nested for loops?

**Comment by sindresorhus** [comment]
`index2`

**Comment by futpib** [comment]
`index_`
