### ISSUE TITLE
Integration tests

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/eslint-plugin-unicorn#84]
We should run all the rules using ESLint against a huge amount of code to ensure it never crashes. We could include the source of some larger projects.

I usually manually run master against AVA to as an ensurance, but I forgot this time.

This could have prevented https://github.com/sindresorhus/eslint-plugin-unicorn/issues/81 and https://github.com/sindresorhus/eslint-plugin-unicorn/issues/82.

**Comment by SamVerschueren** [comment]
Does anyone has any idea on what tools we can use here? How can we set this up? Like to help getting this done.

**Comment by sindresorhus** [comment]
Some prior art:

- https://github.com/standard/standard/blob/6dd2c056e96b40d8a69df110062f5b2473d74eba/test/clone.js
- https://github.com/eslint/eslint-canary
- https://github.com/nodejs/citgm
- https://github.com/bahmutov/dont-break

Could be a script that reads a hard-coded list of repos to check out and test. We could even have it as a Travis cron-job that runs every week.

**Comment by SamVerschueren** [comment]
Looking into this as we speak. Cloning a/multiple repositories is pretty easy. I'm just not sure how to run XO or ESLint with the local version of `eslint-plugin-unicorn`. I tried running `./node_modules/.bin/xo --extend=./index.js` but that doesn't seem to work. I always get the following error

> Error: Cannot find module 'eslint-config-index.js'

// @jfmengels

**Comment by sindresorhus** [comment]
Probably easiest to use ESLint directly. Have a sharable config with https://github.com/sindresorhus/eslint-plugin-unicorn#recommended-config somewhere and reference it in ESLint with `$ eslint --config /absolute/path/to/config`.

**Comment by SamVerschueren** [comment]
The thing is that it doesn't look like we can use relative paths in the eslint config.

**Comment by sindresorhus** [comment]
Not sure why that's a problem or where you would need to use relative paths?

How I would do it:

- Create a shareable config package with a package.json, index.js with https://github.com/sindresorhus/eslint-plugin-unicorn#recommended-config and give it a name like `eslint-config-unicorn-tester` or something. This package should be bundled in the package tester package, let's call it `unicorn-tester`.
- `unicorn-tester` should copy/link the local `eslint-plugin-unicorn` version into `node_modules` of  `eslint-config-unicorn-tester`
- `unicorn-tester` then calls `$ eslint --config=/absolute/path/to/eslint-config-unicorn-tester` with the `cwd` being the project to be tested with `eslint-plugin-unicorn`.

**Comment by SamVerschueren** [comment]
You really mean creating those packages separately and publish on npm right? Not just a directory in the tests folder here? Just to make sure I understand everything correctly :).

**Comment by sindresorhus** [comment]
No, just bundle them here. I don't really see much value in having them on npm, do you?

**Comment by SamVerschueren** [comment]
I think it might be nice to have all the logic in separate packages to remove the amount of code here. That way, this module only focusses on the specific rules, not all the bloat to run the integration tests.

But let's just start with adding the logic here and see where that goes. We can always pull it out later.
