### ISSUE TITLE
Allow `_` as a name in `catch-error-name` rule if it's not used

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/eslint-plugin-unicorn#87]
Thought of it when I saw: https://github.com/avajs/ava/pull/1265/files#diff-b72e3e25f31d6b3c3e5f40b5991dc5f6R43

Sometimes you don't need the error and you should be able to name it `_` to ignore it. This is a common pattern many use and it's used in some ESLint core rules too I think.

// @novemberborn

**Comment by jfmengels** [comment]
Should we have `_` as an exception, or should the user be able to specify the names that should be allowed? I prefer the latter option, especially as it can be kind of confusing with people who use Lodash/underscore a lot.

**Comment by novemberborn** [comment]
> Should we have _ as an exception, or should the user be able to specify the names that should be allowed? I prefer the latter option, especially as it can be kind of confusing with people who use Lodash/underscore a lot.

Perhaps allow any number of underscores?

**Comment by sindresorhus** [comment]
> Perhaps allow any number of underscores?

I like that idea.

**Comment by SamVerschueren** [comment]
What's the easiest way to detect if a variable (identifier) is used inside a block? At first, I checked if the catch block was empty, if that was the case then `_` is allowed. But that's not 100% correct as it should be allowed as well whenever `_` is not used inside that block. Looking for some leads here :).

**Comment by jfmengels** [comment]
@SamVerschueren You could use https://github.com/jfmengels/eslint-ast-utils/blob/master/readme.md#astutilscontainsidentifiername-node

**Comment by SamVerschueren** [comment]
Nice! Thanks :)
