### ISSUE TITLE
Definition for rule 'unicorn/prefer-math-trunc' was not found

### ISSUE THREAD

**Issue by kkmuffme** [sindresorhus/eslint-plugin-unicorn#871]
After updating to v23.0.0 and adding `"unicorn/prefer-math-trunc": "error",` to my eslint config I get:
>Definition for rule 'unicorn/prefer-math-trunc' was not found

The issue is only with `prefer-math-trunc`, all other rules work correcetly (I have all unicorn rules in my eslint config)

The issue happens with all/any code I test.

**Comment by sindresorhus** [comment]
Sounds like a caching issue on your end.

**Comment by kkmuffme** [comment]
Hm, any idea which cache? 
I'm really out of ideas for this unfortunately and could really need some help.

When I remove the `prefer-math-trunc` rule setting from my eslint conf file, I still get the error (which means it's loaded by default by eslint-unicorn, which is good to know that it's there)

I can see that the prefer-math-trunc rule is there in: (correctly)
- /usr/lib/node_modules/eslint-plugin-unicorn/index.js
- /usr/lib/node_modules/eslint-plugin-unicorn/rules/prefer-math-trunc.js

I already tried uninstalling & reinstalling unicorn, but the issue persists.

**Comment by kkmuffme** [comment]
Found the issue. Something in npm changed, which meant the npm global path changed, thus --resolve-plugins-relative-to in eslint had the wrong path.

Now using:
`--resolve-plugins-relative-to "$(npm root -g)"` to avoid this issue
