### ISSUE TITLE
Best practice for using `useRef` alongside `eslint(unicorn/no-null)`

### ISSUE THREAD

**Issue by el1f** [sindresorhus/eslint-plugin-unicorn#888]
The correct usage of `useRef` with typescript requires its initialization with a `null` value but having this rule active doesn't allow using it. What's the best practice in this case?

**Comment by fisker** [comment]
I think we can make an exception for it.

**Comment by el1f** [comment]
This was quicker than expected! Thanks a lot guys! :D

**Comment by tiagoporto** [comment]
PR is merged but is not available in version `23.0.0`, when a new version will be published?

**Comment by tiagoporto** [comment]
Fixed on version 24.0.0
