### ISSUE TITLE
eslint-unicorn breaks eslint no-unused-vars exported

### ISSUE THREAD

**Issue by kkmuffme** [sindresorhus/eslint-plugin-unicorn#892]
When using unicorn/recommended, the eslint no-unused-vars "exported" does not work anymore, and reports "exported" vars/functions as unused.

>error 'helloWorld' is assigned a value but never used no-unused-vars

.eslintrc.json

```json
{
    "plugins": [
        "unicorn"
    ],
    "parserOptions": {
        "ecmaVersion": 6
    },
    "env": {
        "browser": true
    },
    "extends": [
        "eslint:recommended",
        "plugin:unicorn/recommended"
    ]
}
```

Simplest case to reproduce the issue:

```js
/* exported helloWorld */

var helloWorld = 'hello';
```

eslint@7.12.0
eslint-plugin-unicorn@23.0.0

**Comment by kkmuffme** [comment]
Apparently the issue is that unicorn changes the sourceType and ecmaFeature.globalReturn values, which break this rule (as outlined here: https://eslint.org/docs/rules/no-unused-vars#exported)

Manually changing it back, solves this issue:

```json
{
    "plugins": [
        "unicorn"
    ],
    "parserOptions": {
        "ecmaVersion": 6,
        "sourceType": "script",
        "ecmaFeatures": {
            "globalReturn": false
        }
    },
    "env": {
        "browser": true
    },
    "extends": [
        "eslint:recommended",
        "plugin:unicorn/recommended"
    ]
}
```

Would it be possible that you document this hidden, but impactful change somewhere prominently in the readme?

**Comment by fisker** [comment]
"Note:" in this section https://github.com/sindresorhus/eslint-plugin-unicorn#recommended-config

**Comment by kkmuffme** [comment]
There it says:
>Note: This config will also enable the correct parser options and environment.

To conclude that this will change the sourceType and set globalReturn true is really, really far fetched. Some clarifications on what it does actually set would be termendously helpful.

Especially, since I am unsure why these are the "correct" parser options?
Why does unicode require (!) sourceType module and globalReturn true? This isn't really necessary for unicode to work correctly, is it?

**Comment by sindresorhus** [comment]
> Especially, since I am unsure why these are the "correct" parser options?
Why does unicode require (!) sourceType module and globalReturn true? This isn't really necessary for unicode to work correctly, is it?

It's the **recommended** preset. It's the config we recommend. Our focus is modern, readable, and strict code. If you disagree, you can just override it like you did.

As for why, because it makes rules stricter and prepares for ESM modules. For example, I plan to move all my packages to ESM this year.
