### ISSUE TITLE
Cannot find rule in readme `no-unreadable-array-destructuring`

### ISSUE THREAD

**Issue by AuthorProxy** [sindresorhus/eslint-plugin-unicorn#898]
This rule https://github.com/sindresorhus/eslint-plugin-unicorn/blob/master/docs/rules/no-unreadable-array-destructuring.md
doesn't exist in the rules list https://github.com/sindresorhus/eslint-plugin-unicorn

**Comment by fisker** [comment]
Yes, it exists  https://github.com/sindresorhus/eslint-plugin-unicorn/blob/07dadf52a14142ade44900c10467b5a74f7b613d/index.js#L46

**Comment by fisker** [comment]
And in readme.md L62 & L128
