### ISSUE TITLE
Prevent passing a function directly to iterator methods

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/eslint-plugin-unicorn#91]
You have a dependency:

```js
module.exports = x => x + 1;
```

You use it like this (which many do):

```js
const unicorn = require('unicorn');

[1, 2, 3].map(unicorn);
//=> [2, 3, 4]
```

The `unicorn` module now does a minor version that adds another argument:

```js
module.exports = (x, y) => x + (y ? y : 1);
```

Your code will now return something different and probably break for users:

```js
const unicorn = require('unicorn');

[1, 2, 3].map(unicorn);
//=> [2, 3, 5]
```

Instead, you should do:

```js
const unicorn = require('unicorn');

[1, 2, 3].map(x => unicorn(x));
//=> [2, 3, 4]
```

---

This would have prevented: https://github.com/avajs/ava/pull/1343

---

It should apply to:

- Array#map
- Array#forEach
- Array#every
- Array#filter
- Array#find
- Array#some
- Map#forEach
- Set#forEach

Anything I missed?

**Comment by SamVerschueren** [comment]
Yes please! I really need and want this :).
