### ISSUE TITLE
Incorrect autofix for prefer-math-trunc rule

### ISSUE THREAD

**Issue by bmish** [sindresorhus/eslint-plugin-unicorn#911]
eslint-plugin-unicorn@23.0.0

Before:

```js
// Very basic hash implementation that mimics Java's hash function, used for generating unique ids for aggregate items
// Found here: https://stackoverflow.com/questions/7616461/generate-a-hash-from-string-in-javascript-jquery
export function generateHash(input) {
  let hash = 0;
  for (let i = 0; i < input.length; i++) {
    const char = input.charCodeAt(i);
    hash = (hash << 5) - hash + char;
    hash |= 0; // Convert to 32bit integer
  }
  return hash;
}
```

Example result (correct):

```
generateHash('abc123;')
-1207861333
```

After autofix by [unicorn/prefer-math-trunc](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/v23.0.0/docs/rules/prefer-math-trunc.md):

```js
// Very basic hash implementation that mimics Java's hash function, used for generating unique ids for aggregate items
// Found here: https://stackoverflow.com/questions/7616461/generate-a-hash-from-string-in-javascript-jquery
export function generateHash(input) {
  let hash = 0;
  for (let i = 0; i < input.length; i++) {
    const char = input.charCodeAt(i);
    hash = (hash << 5) - hash + char;
    hash = Math.trunc(hash); // Convert to 32bit integer
  }
  return hash;
}
```

Example result (after autofix, incorrect):

```
generateHash('abc123;')
3087105963
```

Looks related to #862.

**Comment by fisker** [comment]
```js
3087105963 | 0         // -> -1207861333
Math.trunc(3087105963) // -> 3087105963
```

**Comment by fisker** [comment]
I think you posted the wrong result

`|= 0` version result `-1207861333`, `Math.trunc` version result `3087105963`.

Anyway, still bug.

**Comment by bmish** [comment]
Thanks, I fixed the results in my description.

**Comment by papb** [comment]
Hmm, it seems in this case the code really intends to use the 32-bit behavior from `| 0` instead of wanting `Math.trunc`. To me this is a correct use case for `// eslint-disable-line`. I am not sure if the autofix should be removed or not though.

**Comment by sindresorhus** [comment]
> Completely remove autofix from this rule

If we go with this, we would not remove it though. Just turn it into a suggestion instead.

**Comment by papb** [comment]
@sindresorhus Ah, yes, I forgot that suggestions exists for this!

**Comment by arnog** [comment]
I would strongly suggest changing this rule to be a warning rather than an autofix. Silently transforming the code in such a way that it behaves differently than it did before the transformation seems ill considered, even if the transformation is fine in "99%" of the cases. I had to debug a rather large code base that was broken after applying **xo** to it because of this rule. Not fun. 

Furthermore, if the general policy is that autofix rules can change the semantic of the codebase (without warning) and therefore potentially introduce subtle (or not) bugs, I would reconsider using any of these rules at all, which would be a shame.

**Comment by sindresorhus** [comment]
Lets turn the auto-fixer into a suggestion.

**Comment by sindresorhus** [comment]
// @noftaly

**Comment by noftaly** [comment]
Is the suggestion only for the bitwise OR with 0 (`| 0`) or all cases?

**Comment by arnog** [comment]
I think it's only for `| 0`. Are there other cases where the expression is transformed into `Math.trunc()`? In general, the idea would be that no transformation should return a result different than what it replaces.

**Comment by noftaly** [comment]
> I think it's only for | 0. Are there other cases where the expression is transformed into Math.trunc()? In general, the idea would be that no transformation should return a result different than what it replaces.

Yes, it also does it for `~~x`, `x >> 0`, `x << 0` and `x ^ 0`.

So I've done the fix locally (only for `| 0`), but I'm not sure how to update the test. I'll open the PR anyway and we'll figure this out there!

**Comment by sindresorhus** [comment]
Fixed in https://github.com/sindresorhus/eslint-plugin-unicorn/releases/tag/v26.0.1
