### ISSUE TITLE
Improve option naming

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/eslint-plugin-unicorn#942]
I don't think we should use `whitelist`/`blacklist` type naming. They have negative connotations for some.

whitelist => allowList
blacklist => denyList

This applies to:

- `blacklist` option in `no-keyword-prefix`
- `whitelist` option in `prevent-abbreviations`
- `extendDefaultWhitelist` option in `prevent-abbreviations`

---

I'm not really interested in discussing the merits of this. It's the right thing to do.

https://thenextweb.com/dd/2020/07/13/linux-kernel-will-no-longer-use-terms-blacklist-and-slave/

**Comment by fisker** [comment]
Rename default branch to `main`?

**Comment by sindresorhus** [comment]
> Rename default branch to main?

GitHub promised they would come with a feature to automate this, so I'm waiting for that.

**Comment by fregante** [comment]
Why `List`? It could just be allow/deny, include/exclude, etc.

**Comment by sindresorhus** [comment]
@fregante That was just the recommended replacement when I read about it.

---

> prevent-abbreviations: except/allowed

Yeah, `allowed` would work there. What would `extendDefaultWhitelist` be then?

> no-keyword-prefix: keywords (i.e. the keywords that are not allowed)

👍

**Comment by fregante** [comment]
Not as clear probably, but

- extendDefaultList
- extendDefaultAllowedList
- extendDefaults

**Comment by sindresorhus** [comment]
> extendDefaultList
extendDefaultAllowedList

Why `*List`? 😛

**Comment by fisker** [comment]
When I send #1164, I forgot this issue, `allowed` was suggested for `prevent-abbreviations`, but I guess `allowList` is fine.
