### ISSUE TITLE
Broken autofix with `better-regex` and multiple optional spaces

### ISSUE THREAD

**Issue by Cherry** [sindresorhus/eslint-plugin-unicorn#994]
The following throws a ` /\s?\s?/ can be optimized to /\s?{2}/       unicorn/better-regex`

```js
const regex = /\s?\s?/;
```

which auto-fixes to:

```js
const regex = /\s?{2}/;
```

This isn't valid though, and throws a parsing error with `Nothing to repeat`. `\s{0,2}` would be a safer auto-fix here I think, allowing for 0-2 of the previous token. The `{0,2}` fix is done as expected with `/a?a?/`, so it seems `\s` is being handled differently.

Further investigation shows that this looks to be an issue with the `regexp-tree` module:
```js
const {optimize} = require('regexp-tree');
const result = optimize(/\s?\s?/);
/*
_ast: {
    type: 'RegExp',
    body: { type: 'Alternative', expressions: [Array] },
    flags: ''
  },
  _source: null,
  _string: '/\\s?{2}/',
  _regexp: null,
  _extra: null
*/
```
Opened an issue on that repo: https://github.com/DmitrySoshnikov/regexp-tree/issues/216

**Comment by sindresorhus** [comment]
If you can figure out which transform that causes this, it might be possible to disable that specific transform in the mean time: https://github.com/sindresorhus/eslint-plugin-unicorn/blob/ade13accb4b78a8171f297234eae67318be2cde3/rules/better-regex.js#L34

**Comment by Cherry** [comment]
I can confirm it's the `combineRepeatingPatterns` transform that's doing this:

```js
const {optimize} = require('regexp-tree');
const result = optimize(/\s?\s?/, undefined, {
	blacklist: ['combineRepeatingPatterns']
});
/*
TransformResult {
  _ast: {
    type: 'RegExp',
    body: { type: 'Alternative', expressions: [Array] },
    flags: ''
  },
  _source: null,
  _string: '/\\s?\\s?/',
  _regexp: null,
  _extra: null
}
*/
```

Disabling this transform will disable lots of other useful transforms though unfortunately, such as `/ddddddddd/` to `/d{9}/`.

**Comment by Cherry** [comment]
As per my comment at https://github.com/DmitrySoshnikov/regexp-tree/issues/216#issuecomment-761860979, this bug seems to be wider impacting and affects things like `/\w?\w?/` too - seemingly any recurring optional character classes.

I'd recommend adding this transform to the ignoreList for now until it can be addressed upstream.
