### ISSUE TITLE
Broken autofix in prefer-string-slice with optional chaining

### ISSUE THREAD

**Issue by stonegray** [sindresorhus/eslint-plugin-unicorn#999]
When fixing code with the `prefer-string-slice` rule, code which contains the optional chaining operator can break, as the operator is discarded in the output.

This occurs when using the recommended rules.

**Example input and configuration**
```js
const foo = {};
console.log(foo.bar?.substring(2));
```
```json eslintrc
{
	"plugins": [
		"unicorn"
	],
	"parserOptions": {
		"ecmaVersion": 2020
	},
	"rules": {
		"unicorn/prefer-string-slice": "error"
	}
}
```

Expected output after the auto fix runs is `foo.bar?.slice(2)`, and the program should output `undefined`.

Observed output does not retain optional chaining operator, and after fixing is `foo.bar.slice(2)`. This causes the above program to throw an error on execution instead of outputting `undefined`.

Resources:
* [Optional chaining operator on MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining)
* [OptionalExpression Specification](https://tc39.es/ecma262/#prod-OptionalExpression)
* [Feature support](https://node.green/#ES2020-features-optional-chaining-operator-----) (tldr: all current Node versions)

**Comment by sindresorhus** [comment]
Thanks for reporting. We should probably go through all our rules and ensure they work with optional chaining and `??` and add tests.
